-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  telefono text,
  correo text,
  comentarios text,
  rol_responsable text,
  fecha_creacion timestamp without time zone DEFAULT now(),
  creado_por uuid,
  favorito boolean NOT NULL DEFAULT false,
  estatus text NOT NULL DEFAULT 'activo'::text CHECK (estatus = ANY (ARRAY['activo'::text, 'seguimiento'::text, 'problema'::text, 'inactivo'::text])),
  ultima_interaccion timestamp with time zone,
  origen_registro text,
  horario_laboral text,
  razon_social text,
  rfc text,
  nombre_norm text,
  razon_social_norm text,
  activo boolean NOT NULL DEFAULT true,
  requiere_revision boolean NOT NULL DEFAULT false,
  calidad_datos text NOT NULL DEFAULT 'normal'::text CHECK (calidad_datos = ANY (ARRAY['normal'::text, 'sospechoso'::text, 'validado'::text, 'duplicado'::text, 'archivado'::text])),
  CONSTRAINT clientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  nombre_archivo text NOT NULL,
  url_pdf text NOT NULL,
  tipo_documento text,
  sistema text,
  fecha_subida timestamp without time zone DEFAULT now(),
  fecha_creacion_doc date,
  inicio_vigencia date,
  fin_vigencia date,
  fecha_alerta date,
  modo_vigencia text,
  estado text DEFAULT 'activo'::text,
  eliminado boolean DEFAULT false,
  eliminado_en timestamp without time zone,
  eliminado_por uuid,
  subido_por uuid,
  nombre_archivo_norm text,
  hash_sha256 text,
  tamano_bytes bigint,
  mime_type text NOT NULL DEFAULT 'application/pdf'::text,
  version integer NOT NULL DEFAULT 1,
  documento_base text,
  es_actual boolean NOT NULL DEFAULT true,
  estado_vigencia text,
  storage_path text,
  version_comercial text,
  tipo_licencia text,
  usuarios text,
  empresas_info text,
  lote text,
  numero_serie text,
  verificador text,
  empresa_certificado text,
  texto_extraido text,
  lectura_pdf_ok boolean NOT NULL DEFAULT false,
  lectura_pdf_error text,
  sistema_norm text,
  sistema_norm2 text,
  sistema_confianza integer,
  fecha_referencia date,
  fecha_referencia_fuente text,
  candidato_borrado boolean DEFAULT false,
  motivo_revision text,
  fecha_fuente text,
  requiere_revision boolean DEFAULT false,
  pedido_num bigint,
  pedido_tipo text,
  conservar boolean DEFAULT false,
  hash_archivo text,
  origen_carga text,
  fecha_clasificacion timestamp with time zone,
  pdf_text text,
  CONSTRAINT documentos_pkey PRIMARY KEY (id),
  CONSTRAINT documentos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.bitacora (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid,
  accion text,
  documento_id uuid,
  cliente_id uuid,
  fecha timestamp without time zone DEFAULT now(),
  detalle jsonb,
  visibilidad text DEFAULT 'interna'::text,
  tipo text DEFAULT 'nota_interna'::text,
  CONSTRAINT bitacora_pkey PRIMARY KEY (id)
);
CREATE TABLE public.perfiles (
  id uuid NOT NULL,
  nombre text,
  rol text NOT NULL DEFAULT 'soporte'::text CHECK (rol = ANY (ARRAY['admin'::text, 'ventas'::text, 'soporte'::text])),
  creado_en timestamp without time zone DEFAULT now(),
  tema text NOT NULL DEFAULT 'system'::text CHECK (tema = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
  preferencias jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT perfiles_pkey PRIMARY KEY (id),
  CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  documento_id uuid,
  titulo text NOT NULL,
  descripcion text,
  prioridad text NOT NULL DEFAULT 'media'::text CHECK (prioridad = ANY (ARRAY['baja'::text, 'media'::text, 'alta'::text, 'urgente'::text])),
  estado text NOT NULL DEFAULT 'abierto'::text CHECK (estado = ANY (ARRAY['abierto'::text, 'en_proceso'::text, 'esperando_cliente'::text, 'resuelto'::text, 'cerrado'::text])),
  tipo text NOT NULL DEFAULT 'soporte'::text CHECK (tipo = ANY (ARRAY['soporte'::text, 'renovacion'::text, 'facturacion'::text, 'configuracion'::text])),
  asignado_a uuid,
  creado_por uuid,
  fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
  fecha_actualizacion timestamp with time zone NOT NULL DEFAULT now(),
  fecha_cierre timestamp with time zone,
  origen text DEFAULT 'dashboard'::text,
  responsable_id uuid,
  asignado_en timestamp with time zone,
  primera_respuesta_en timestamp with time zone,
  impacto text,
  afecta_a text,
  desde_cuando text,
  ultimo_cambio text,
  horario_contacto text,
  contexto_adicional text,
  canal text,
  adjuntos jsonb NOT NULL DEFAULT '[]'::jsonb,
  evidencia_count integer NOT NULL DEFAULT 0,
  solicitud_soporte_id uuid,
  folio text,
  token_publico text,
  token_publico_expira timestamp with time zone,
  correo_cliente text,
  nombre_cliente_contacto text,
  timeline_publica jsonb DEFAULT '[]'::jsonb,
  empresa_capturada text,
  nombre_capturado text,
  correo_capturado text,
  telefono_capturado text,
  cliente_id_sugerido uuid,
  contacto_id_sugerido uuid,
  match_nivel text,
  match_score integer,
  match_confirmado boolean NOT NULL DEFAULT false,
  contacto_confirmado boolean NOT NULL DEFAULT false,
  contacto_es_nuevo boolean NOT NULL DEFAULT false,
  requiere_consolidacion boolean NOT NULL DEFAULT false,
  contacto_id uuid,
  sla_policy text,
  sla_first_response_deadline timestamp with time zone,
  sla_resolution_deadline timestamp with time zone,
  sla_breached_first_response boolean NOT NULL DEFAULT false,
  sla_breached_resolution boolean NOT NULL DEFAULT false,
  triage_score integer,
  next_action_hint text,
  horario_desde time without time zone,
  horario_hasta time without time zone,
  horario_notas text,
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT tickets_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT tickets_documento_id_fkey FOREIGN KEY (documento_id) REFERENCES public.documentos(id),
  CONSTRAINT tickets_asignado_a_fkey FOREIGN KEY (asignado_a) REFERENCES auth.users(id),
  CONSTRAINT tickets_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id),
  CONSTRAINT tickets_cliente_id_sugerido_fkey FOREIGN KEY (cliente_id_sugerido) REFERENCES public.clientes(id),
  CONSTRAINT tickets_contacto_id_sugerido_fkey FOREIGN KEY (contacto_id_sugerido) REFERENCES public.clientes_contactos(id),
  CONSTRAINT tickets_solicitud_soporte_id_fkey FOREIGN KEY (solicitud_soporte_id) REFERENCES public.solicitudes_soporte(id)
);
CREATE TABLE public.ticket_archivos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  nombre_archivo text NOT NULL,
  url_archivo text NOT NULL,
  mime_type text,
  subido_por uuid,
  fecha_subida timestamp with time zone NOT NULL DEFAULT now(),
  tamano_bytes bigint,
  CONSTRAINT ticket_archivos_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_archivos_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES auth.users(id),
  CONSTRAINT ticket_archivos_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id)
);
CREATE TABLE public.clientes_usuarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  rol text NOT NULL CHECK (rol = ANY (ARRAY['owner'::text, 'editor'::text, 'viewer'::text])),
  CONSTRAINT clientes_usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_usuarios_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT clientes_usuarios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);
CREATE TABLE public.documentos_borrado_vdi_backup (
  id uuid,
  cliente_id uuid,
  nombre_archivo text,
  url_pdf text,
  tipo_documento text,
  sistema text,
  fecha_subida timestamp without time zone,
  fecha_creacion_doc date,
  inicio_vigencia date,
  fin_vigencia date,
  fecha_alerta date,
  modo_vigencia text,
  estado text,
  eliminado boolean,
  eliminado_en timestamp without time zone,
  eliminado_por uuid,
  subido_por uuid,
  nombre_archivo_norm text,
  hash_sha256 text,
  tamano_bytes bigint,
  mime_type text,
  version integer,
  documento_base text,
  es_actual boolean,
  estado_vigencia text,
  storage_path text,
  version_comercial text,
  tipo_licencia text,
  usuarios text,
  empresas_info text,
  lote text,
  numero_serie text,
  verificador text,
  empresa_certificado text,
  texto_extraido text,
  lectura_pdf_ok boolean,
  lectura_pdf_error text,
  sistema_norm text,
  sistema_norm2 text
);
CREATE TABLE public.auditoria_storage_manual (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fecha timestamp without time zone DEFAULT now(),
  nota text,
  archivos integer,
  bytes bigint,
  CONSTRAINT auditoria_storage_manual_pkey PRIMARY KEY (id)
);
CREATE TABLE public.auditoria_borrado_storage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fecha timestamp without time zone DEFAULT now(),
  lote text,
  origen text,
  paths_count integer,
  nota text,
  CONSTRAINT auditoria_borrado_storage_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cliente_aliases (
  cliente_id uuid,
  alias text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alias_norm text,
  tipo text NOT NULL DEFAULT 'manual'::text,
  confianza numeric NOT NULL DEFAULT 1,
  activo boolean NOT NULL DEFAULT true,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TABLE public.solicitudes_alta (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  telefono text,
  correo text,
  contacto text,
  comentarios text,
  estatus text NOT NULL DEFAULT 'pendiente'::text CHECK (estatus = ANY (ARRAY['pendiente'::text, 'procesando'::text, 'aprobada'::text, 'rechazada'::text])),
  origen text DEFAULT 'alta.html'::text,
  ip text,
  user_agent text,
  archivos_count integer DEFAULT 0,
  observaciones_internas text,
  cliente_id uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  procesado_en timestamp with time zone,
  contacto_principal_nombre text,
  contacto_principal_puesto text,
  contacto_principal_correo text,
  contacto_principal_telefono text,
  contacto_principal_whatsapp text,
  metodo_contacto_preferido text,
  horario_contacto text,
  cumpleanos date,
  archivos jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_peso bigint NOT NULL DEFAULT 0,
  cumpleanos_contacto date,
  contacto_alterno_nombre text,
  contacto_alterno_puesto text,
  contacto_alterno_correo text,
  contacto_alterno_telefono text,
  contacto_id uuid,
  horario_laboral text,
  cliente_id_sugerido uuid,
  contacto_id_sugerido uuid,
  match_nivel text,
  match_score numeric,
  match_razones jsonb NOT NULL DEFAULT '[]'::jsonb,
  requiere_revision boolean NOT NULL DEFAULT true,
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT solicitudes_alta_pkey PRIMARY KEY (id),
  CONSTRAINT solicitudes_alta_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT solicitudes_alta_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT solicitudes_alta_cliente_id_sugerido_fkey FOREIGN KEY (cliente_id_sugerido) REFERENCES public.clientes(id),
  CONSTRAINT solicitudes_alta_contacto_id_sugerido_fkey FOREIGN KEY (contacto_id_sugerido) REFERENCES public.clientes_contactos(id)
);
CREATE TABLE public.solicitud_archivos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  solicitud_id uuid NOT NULL,
  nombre_archivo text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  tamano_bytes bigint,
  tipo_detectado text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT solicitud_archivos_pkey PRIMARY KEY (id),
  CONSTRAINT solicitud_archivos_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_soporte(id)
);
CREATE TABLE public.solicitudes_soporte (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folio text UNIQUE,
  nombre text NOT NULL,
  empresa text NOT NULL,
  correo text,
  telefono text,
  categoria text,
  sistema text,
  objetivo text,
  titulo text NOT NULL,
  descripcion text NOT NULL,
  impacto text,
  prioridad text,
  canal text,
  voz text,
  cliente_id uuid,
  ticket_id uuid,
  origen text DEFAULT 'soporte_publico'::text,
  estatus text DEFAULT 'nuevo'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contacto_id uuid,
  desde_cuando text,
  afecta_a text,
  ultimo_cambio text,
  horario_contacto text,
  contexto_adicional text,
  archivos_count integer NOT NULL DEFAULT 0,
  total_peso bigint NOT NULL DEFAULT 0,
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  empresa_capturada text,
  nombre_capturado text,
  correo_capturado text,
  telefono_capturado text,
  cliente_id_sugerido uuid,
  contacto_id_sugerido uuid,
  match_nivel text,
  match_score integer,
  match_confirmado boolean NOT NULL DEFAULT false,
  contacto_confirmado boolean NOT NULL DEFAULT false,
  contacto_es_nuevo boolean NOT NULL DEFAULT false,
  requiere_consolidacion boolean NOT NULL DEFAULT false,
  horario_desde time without time zone,
  horario_hasta time without time zone,
  horario_notas text,
  CONSTRAINT solicitudes_soporte_pkey PRIMARY KEY (id),
  CONSTRAINT solicitudes_soporte_contacto_id_sugerido_fkey FOREIGN KEY (contacto_id_sugerido) REFERENCES public.clientes_contactos(id),
  CONSTRAINT solicitudes_soporte_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT solicitudes_soporte_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT solicitudes_soporte_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT solicitudes_soporte_cliente_id_sugerido_fkey FOREIGN KEY (cliente_id_sugerido) REFERENCES public.clientes(id)
);
CREATE TABLE public.clientes_contactos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  nombre text NOT NULL,
  puesto text,
  correo text,
  telefono text,
  whatsapp text,
  metodo_contacto_preferido text CHECK (metodo_contacto_preferido IS NULL OR (metodo_contacto_preferido = ANY (ARRAY['correo'::text, 'telefono'::text, 'whatsapp'::text]))),
  es_principal boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true,
  datos_confirmados_en timestamp with time zone,
  datos_verificacion_vence_en timestamp with time zone,
  datos_verificacion_estatus text DEFAULT 'pendiente'::text CHECK (datos_verificacion_estatus = ANY (ARRAY['pendiente'::text, 'confirmado'::text, 'vencido'::text, 'requiere_revision'::text])),
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  cumpleanos date,
  origen_alta text,
  ultima_interaccion_en timestamp with time zone,
  notas text,
  horario_laboral text,
  CONSTRAINT clientes_contactos_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_contactos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.clientes_contacto_historial (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contacto_id uuid NOT NULL,
  cliente_id uuid NOT NULL,
  nombre text,
  puesto text,
  correo text,
  telefono text,
  whatsapp text,
  metodo_contacto_preferido text,
  accion text NOT NULL DEFAULT 'confirmacion'::text CHECK (accion = ANY (ARRAY['confirmacion'::text, 'edicion'::text, 'alta_nuevo_contacto'::text, 'alta_aprobada'::text, 'alta_aprobada_alterno'::text, 'registro_aprobado'::text, 'registro_actualizado'::text])),
  origen text DEFAULT 'soporte_publico'::text,
  creado_en timestamp with time zone DEFAULT now(),
  ip text,
  user_agent text,
  CONSTRAINT clientes_contacto_historial_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_contacto_historial_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT clientes_contacto_historial_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.solicitudes_registro (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  contacto_id uuid,
  empresa text NOT NULL,
  correo_empresa text,
  telefono_empresa text,
  contacto_nombre text NOT NULL,
  contacto_puesto text,
  contacto_correo text,
  contacto_telefono text,
  contacto_whatsapp text,
  metodo_contacto_preferido text,
  horario_contacto text,
  cumpleanos_contacto date,
  contacto_alterno_nombre text,
  contacto_alterno_puesto text,
  contacto_alterno_correo text,
  contacto_alterno_telefono text,
  comentarios text,
  origen text DEFAULT 'registro_publico'::text,
  estatus text NOT NULL DEFAULT 'pendiente'::text CHECK (estatus = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])),
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  horario_laboral text,
  cliente_id_sugerido uuid,
  contacto_id_sugerido uuid,
  match_nivel text,
  match_score numeric,
  match_razones jsonb NOT NULL DEFAULT '[]'::jsonb,
  requiere_revision boolean NOT NULL DEFAULT true,
  ip text,
  user_agent text,
  CONSTRAINT solicitudes_registro_pkey PRIMARY KEY (id),
  CONSTRAINT solicitudes_registro_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT solicitudes_registro_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT solicitudes_registro_cliente_id_sugerido_fkey FOREIGN KEY (cliente_id_sugerido) REFERENCES public.clientes(id),
  CONSTRAINT solicitudes_registro_contacto_id_sugerido_fkey FOREIGN KEY (contacto_id_sugerido) REFERENCES public.clientes_contactos(id)
);
CREATE TABLE public.avisos_globales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  titulo text NOT NULL,
  mensaje text NOT NULL,
  severidad text NOT NULL DEFAULT 'warn'::text CHECK (severidad = ANY (ARRAY['info'::text, 'warn'::text, 'danger'::text])),
  activo boolean NOT NULL DEFAULT true,
  mostrar_en_soporte boolean NOT NULL DEFAULT true,
  mostrar_en_dashboard boolean NOT NULL DEFAULT true,
  inicio_publicacion timestamp with time zone NOT NULL DEFAULT now(),
  fin_publicacion timestamp with time zone,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT avisos_globales_pkey PRIMARY KEY (id),
  CONSTRAINT avisos_globales_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ticket_portal_logs (
  id bigint NOT NULL DEFAULT nextval('ticket_portal_logs_id_seq'::regclass),
  ticket_id uuid,
  folio text,
  evento text NOT NULL,
  ip text,
  user_agent text,
  detalle jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ticket_portal_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rate_limit_events (
  id bigint NOT NULL DEFAULT nextval('rate_limit_events_id_seq'::regclass),
  scope text NOT NULL,
  key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rate_limit_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cliente_sistemas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  sistema text NOT NULL,
  tipo_solicitud_default text,
  version_sistema text,
  version_windows text,
  servidor_o_equipo text,
  observaciones text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_por uuid,
  system_key text,
  entorno text CHECK (entorno = ANY (ARRAY['escritorio'::text, 'nube'::text, 'mixto'::text, 'servidor'::text])),
  version_sql text,
  tipo_instalacion text,
  ruta_empresa text,
  respaldo_ubicacion text,
  ultimo_mantenimiento timestamp with time zone,
  activo boolean DEFAULT true,
  respaldo_frecuencia text,
  ultimo_respaldo timestamp with time zone,
  origen text,
  ultima_revision_en timestamp with time zone,
  CONSTRAINT cliente_sistemas_pkey PRIMARY KEY (id),
  CONSTRAINT cliente_sistemas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT cliente_sistemas_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ticket_folios (
  prefix text NOT NULL,
  last_value bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ticket_folios_pkey PRIMARY KEY (prefix)
);
CREATE TABLE public.archivos_ticket (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  solicitud_id uuid,
  origen text NOT NULL CHECK (origen = ANY (ARRAY['solicitud'::text, 'ticket'::text, 'portal'::text, 'interno'::text])),
  visibilidad text NOT NULL DEFAULT 'interna'::text CHECK (visibilidad = ANY (ARRAY['publica'::text, 'interna'::text])),
  nombre_archivo text NOT NULL,
  storage_path text NOT NULL,
  url_firma text,
  mime_type text,
  tamano_bytes bigint,
  subido_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT archivos_ticket_pkey PRIMARY KEY (id),
  CONSTRAINT archivos_ticket_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT archivos_ticket_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_soporte(id),
  CONSTRAINT archivos_ticket_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ticket_eventos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  autor_tipo text NOT NULL CHECK (autor_tipo = ANY (ARRAY['cliente'::text, 'soporte'::text, 'sistema'::text])),
  visibilidad text NOT NULL DEFAULT 'publica'::text CHECK (visibilidad = ANY (ARRAY['publica'::text, 'interna'::text])),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['mensaje'::text, 'estado'::text, 'nota'::text, 'archivo'::text, 'sistema'::text, 'asignacion'::text, 'sla'::text])),
  texto text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ticket_eventos_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_eventos_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT ticket_eventos_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ticket_respuestas_rapidas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  scope text NOT NULL DEFAULT 'global'::text CHECK (scope = ANY (ARRAY['global'::text, 'cliente'::text, 'contacto'::text])),
  modo text NOT NULL CHECK (modo = ANY (ARRAY['seguimiento'::text, 'nota'::text, 'solucion'::text])),
  titulo text NOT NULL,
  texto text NOT NULL,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  variables jsonb DEFAULT '[]'::jsonb,
  categoria text,
  contacto_id uuid,
  CONSTRAINT ticket_respuestas_rapidas_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_respuestas_rapidas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT ticket_respuestas_rapidas_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT ticket_respuestas_rapidas_contacto_cliente_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id),
  CONSTRAINT ticket_respuestas_rapidas_contacto_cliente_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes_contactos(cliente_id)
);
CREATE TABLE public.cliente_accesos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  contacto_id uuid,
  tipo text NOT NULL DEFAULT 'anydesk'::text,
  valor text NOT NULL,
  etiqueta text,
  notas text,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_por uuid,
  CONSTRAINT cliente_accesos_pkey PRIMARY KEY (id),
  CONSTRAINT cliente_accesos_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES auth.users(id),
  CONSTRAINT cliente_accesos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT cliente_accesos_contacto_id_fkey FOREIGN KEY (contacto_id) REFERENCES public.clientes_contactos(id)
);
CREATE TABLE public.edge_idempotency (
  idempotency_key text NOT NULL,
  action text NOT NULL,
  resource_id uuid,
  request_hash text NOT NULL,
  status text NOT NULL DEFAULT 'processing'::text CHECK (status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])),
  response jsonb,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT edge_idempotency_pkey PRIMARY KEY (idempotency_key)
);
CREATE TABLE public.ticket_match_decisiones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  solicitud_soporte_id uuid,
  empresa_capturada text,
  nombre_capturado text,
  correo_capturado text,
  telefono_capturado text,
  cliente_id_sugerido uuid,
  contacto_id_sugerido uuid,
  cliente_nombre_sugerido text,
  contacto_nombre_sugerido text,
  score numeric,
  nivel text NOT NULL DEFAULT 'ninguno'::text CHECK (nivel = ANY (ARRAY['alto'::text, 'medio'::text, 'bajo'::text, 'ninguno'::text])),
  razones jsonb NOT NULL DEFAULT '[]'::jsonb,
  decision text NOT NULL DEFAULT 'pendiente'::text CHECK (decision = ANY (ARRAY['pendiente'::text, 'aceptado'::text, 'rechazado'::text, 'creado_cliente'::text, 'creado_contacto'::text, 'merge'::text, 'ignorado'::text])),
  decidido_por uuid,
  decidido_en timestamp with time zone,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ticket_match_decisiones_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_match_decisiones_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT ticket_match_decisiones_solicitud_soporte_id_fkey FOREIGN KEY (solicitud_soporte_id) REFERENCES public.solicitudes_soporte(id),
  CONSTRAINT ticket_match_decisiones_cliente_id_sugerido_fkey FOREIGN KEY (cliente_id_sugerido) REFERENCES public.clientes(id),
  CONSTRAINT ticket_match_decisiones_contacto_id_sugerido_fkey FOREIGN KEY (contacto_id_sugerido) REFERENCES public.clientes_contactos(id)
);