import{createClient}from"https://esm.sh/@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}});
const env=(k:string)=>{const v=Deno.env.get(k);if(!v)throw new Error(`${k} required`);return v};
const admin=()=>createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"));
const clean=(v:unknown,max=3000)=>String(v||"").trim().replace(/\s+/g," ").slice(0,max);
const digits=(v:unknown)=>String(v||"").replace(/\D+/g,"");
const mail=(v:unknown)=>clean(v,180).toLowerCase();
const norm=(v:unknown)=>String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim();
const ACRO=new Map([["contpaqi","CONTPAQi"],["xml","XML"],["cfdi","CFDI"],["sat","SAT"],["sql","SQL"],["rfc","RFC"],["uuid","UUID"],["pdf","PDF"],["pac","PAC"],["api","API"],["iva","IVA"],["isr","ISR"],["imss","IMSS"],["infonavit","INFONAVIT"],["anydesk","AnyDesk"],["teamviewer","TeamViewer"],["windows","Windows"],["excel","Excel"],["ui","UI"]]);
const word=(w:string)=>{const x=clean(w,80),k=x.toLowerCase();if(!k)return"";if(ACRO.has(k))return ACRO.get(k)||x;if(/^\d+$/.test(x))return x;return k[0].toUpperCase()+k.slice(1)};
const human=(v:unknown)=>clean(v,180).split(" ").map(word).filter(Boolean).join(" ");
const now=()=>new Date().toISOString();
const uuidOk=(v:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);

async function actor(s:any,req:Request){const jwt=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!jwt)throw new Response(JSON.stringify({error:"Falta sesión"}),{status:401,headers:{...cors,"Content-Type":"application/json"}});const{data,error}=await s.auth.getUser(jwt);if(error||!data?.user)throw new Response(JSON.stringify({error:"Sesión inválida"}),{status:401,headers:{...cors,"Content-Type":"application/json"}});const{data:perfil}=await s.from("perfiles").select("id,rol,nombre").eq("id",data.user.id).maybeSingle();const rol=String(perfil?.rol||"").toLowerCase();if(!["admin","soporte","superadmin"].includes(rol))throw new Response(JSON.stringify({error:"No autorizado"}),{status:403,headers:{...cors,"Content-Type":"application/json"}});return{uid:data.user.id,rol,nombre:perfil?.nombre||data.user.email||"Soporte"}}
async function bitacora(s:any,accion:string,cliente_id:string|null,detalle:Record<string,unknown>){try{await s.from("bitacora").insert({accion,cliente_id,detalle,visibilidad:"interna",tipo:"nota_interna"})}catch{}}
async function findCliente(s:any,row:any){const correo=mail(row?.correo_empresa),tel=digits(row?.telefono_empresa),n=norm(row?.empresa);if(correo){const q=await s.from("clientes").select("id,nombre,correo,telefono").eq("correo",correo).limit(1).maybeSingle();if(q.data)return q.data}if(tel){const q=await s.from("clientes").select("id,nombre,correo,telefono").eq("telefono",tel).limit(1).maybeSingle();if(q.data)return q.data}if(n){const q=await s.from("clientes").select("id,nombre,correo,telefono").limit(600);if(!q.error){const hit=(q.data||[]).find((x:any)=>norm(x.nombre)===n);if(hit)return hit}}return null}
async function ensureCliente(s:any,row:any,forced:string|null){if(forced){const q=await s.from("clientes").select("id,nombre,correo,telefono").eq("id",forced).maybeSingle();if(q.error)throw new Error(q.error.message);if(!q.data)throw new Error("Cliente seleccionado no existe");await s.from("clientes").update({correo:mail(row?.correo_empresa)||q.data.correo||null,telefono:digits(row?.telefono_empresa)||q.data.telefono||null,horario_laboral:clean(row?.horario_laboral,240)||null,ultima_interaccion:now(),requiere_revision:false}).eq("id",forced);return q.data}const hit=await findCliente(s,row);if(hit){await s.from("clientes").update({correo:mail(row?.correo_empresa)||hit.correo||null,telefono:digits(row?.telefono_empresa)||hit.telefono||null,horario_laboral:clean(row?.horario_laboral,240)||null,ultima_interaccion:now(),requiere_revision:false}).eq("id",hit.id);return hit}const ins=await s.from("clientes").insert({nombre:human(row?.empresa)||"Cliente",correo:mail(row?.correo_empresa)||null,telefono:digits(row?.telefono_empresa)||null,comentarios:clean(row?.comentarios)||null,rol_responsable:"soporte",estatus:"activo",origen_registro:"registro_aprobado",horario_laboral:clean(row?.horario_laboral,240)||null,ultima_interaccion:now(),requiere_revision:false}).select("id,nombre,correo,telefono").single();if(ins.error)throw new Error(ins.error.message);return ins.data}
async function findContacto(s:any,row:any,cliente_id:string,alt=false){const correo=mail(alt?row?.contacto_alterno_correo:row?.contacto_correo),tel=digits(alt?row?.contacto_alterno_telefono:row?.contacto_telefono);if(!correo&&!tel)return null;const q=await s.from("clientes_contactos").select("id,nombre,correo,telefono,cliente_id").eq("cliente_id",cliente_id).limit(120);if(q.error)throw new Error(q.error.message);return(q.data||[]).find((x:any)=>(correo&&mail(x.correo)===correo)||(tel&&digits(x.telefono)===tel))||null}
async function ensurePrincipal(s:any,row:any,cliente_id:string,forced:string|null){if(forced){const q=await s.from("clientes_contactos").select("id,nombre,correo,telefono,cliente_id").eq("id",forced).maybeSingle();if(q.error)throw new Error(q.error.message);if(!q.data)throw new Error("Contacto seleccionado no existe");if(String(q.data.cliente_id)!==String(cliente_id))throw new Error("El contacto seleccionado no pertenece al cliente");const up=await s.from("clientes_contactos").update({nombre:human(row?.contacto_nombre)||q.data.nombre,puesto:human(row?.contacto_puesto)||null,correo:mail(row?.contacto_correo)||q.data.correo||null,telefono:digits(row?.contacto_telefono)||q.data.telefono||null,whatsapp:digits(row?.contacto_whatsapp)||digits(row?.contacto_telefono)||null,metodo_contacto_preferido:clean(row?.metodo_contacto_preferido,80)||null,horario_laboral:clean(row?.horario_contacto,240)||null,cumpleanos:row?.cumpleanos_contacto||null,datos_confirmados_en:now(),datos_verificacion_estatus:"confirmado",ultima_interaccion_en:now(),activo:true,actualizado_en:now()}).eq("id",forced);if(up.error)throw new Error(up.error.message);return{contacto:q.data,accion:"registro_actualizado"}}const hit=await findContacto(s,row,cliente_id,false);if(hit){const up=await s.from("clientes_contactos").update({nombre:human(row?.contacto_nombre)||hit.nombre,puesto:human(row?.contacto_puesto)||null,correo:mail(row?.contacto_correo)||hit.correo||null,telefono:digits(row?.contacto_telefono)||hit.telefono||null,whatsapp:digits(row?.contacto_whatsapp)||digits(row?.contacto_telefono)||null,metodo_contacto_preferido:clean(row?.metodo_contacto_preferido,80)||null,horario_laboral:clean(row?.horario_contacto,240)||null,cumpleanos:row?.cumpleanos_contacto||null,datos_confirmados_en:now(),datos_verificacion_estatus:"confirmado",ultima_interaccion_en:now(),activo:true,actualizado_en:now()}).eq("id",hit.id);if(up.error)throw new Error(up.error.message);return{contacto:hit,accion:"registro_actualizado"}}const ins=await s.from("clientes_contactos").insert({cliente_id,nombre:human(row?.contacto_nombre)||"Contacto",puesto:human(row?.contacto_puesto)||null,correo:mail(row?.contacto_correo)||null,telefono:digits(row?.contacto_telefono)||null,whatsapp:digits(row?.contacto_whatsapp)||digits(row?.contacto_telefono)||null,metodo_contacto_preferido:clean(row?.metodo_contacto_preferido,80)||null,horario_laboral:clean(row?.horario_contacto,240)||null,cumpleanos:row?.cumpleanos_contacto||null,es_principal:true,activo:true,origen_alta:"registro_aprobado",datos_confirmados_en:now(),datos_verificacion_estatus:"confirmado",ultima_interaccion_en:now(),notas:clean(row?.comentarios)||null}).select("id,nombre,correo,telefono,cliente_id").single();if(ins.error)throw new Error(ins.error.message);return{contacto:ins.data,accion:"registro_aprobado"}}
async function ensureAlterno(s:any,row:any,cliente_id:string){if(!(row?.contacto_alterno_nombre||row?.contacto_alterno_correo||row?.contacto_alterno_telefono))return null;const hit=await findContacto(s,row,cliente_id,true);if(hit)return{contacto:hit,accion:"registro_actualizado"};const ins=await s.from("clientes_contactos").insert({cliente_id,nombre:human(row?.contacto_alterno_nombre)||"Contacto adicional",puesto:human(row?.contacto_alterno_puesto)||null,correo:mail(row?.contacto_alterno_correo)||null,telefono:digits(row?.contacto_alterno_telefono)||null,whatsapp:digits(row?.contacto_alterno_telefono)||null,metodo_contacto_preferido:null,es_principal:false,activo:true,origen_alta:"registro_aprobado",datos_confirmados_en:now(),datos_verificacion_estatus:"confirmado",ultima_interaccion_en:now(),notas:"Contacto adicional registrado desde solicitud de registro"}).select("id,nombre,correo,telefono,cliente_id").single();if(ins.error)throw new Error(ins.error.message);return{contacto:ins.data,accion:"registro_aprobado"}}
async function hist(s:any,row:any,cliente_id:string,contacto_id:string,accion:string,alt=false){const h=await s.from("clientes_contacto_historial").insert({contacto_id,cliente_id,nombre:alt?row?.contacto_alterno_nombre:row?.contacto_nombre,puesto:alt?row?.contacto_alterno_puesto:row?.contacto_puesto,correo:alt?row?.contacto_alterno_correo:row?.contacto_correo,telefono:alt?row?.contacto_alterno_telefono:row?.contacto_telefono,whatsapp:alt?row?.contacto_alterno_telefono:(row?.contacto_whatsapp||row?.contacto_telefono),metodo_contacto_preferido:alt?null:row?.metodo_contacto_preferido,accion,origen:"registro_aprobado"});if(h.error){console.error("REGISTRO_HISTORIAL_ERROR",h.error.message);await bitacora(s,"solicitud_registro_historial_error",cliente_id,{contacto_id,accion,error:h.error.message})}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Método no permitido"},405);const s=admin();try{const a=await actor(s,req);const body=await req.json().catch(()=>({}));const id=clean(body?.solicitud_id,80),action=clean(body?.action,20)||"approve";if(!uuidOk(id))return json({error:"solicitud_id inválido"},400);const{data:row,error}=await s.from("solicitudes_registro").select("*").eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!row)return json({error:"Solicitud no encontrada"},404);if(action==="reject"){if(String(row.estatus||"pendiente").toLowerCase()!=="pendiente")return json({error:"La solicitud ya fue procesada"},409);const up=await s.from("solicitudes_registro").update({estatus:"rechazada",requiere_revision:false,actualizado_en:now()}).eq("id",id);if(up.error)throw new Error(up.error.message);await bitacora(s,"solicitud_registro_rechazada",row.cliente_id||row.cliente_id_sugerido||null,{solicitud_id:id,actor_id:a.uid,actor:a.nombre});return json({ok:true,action:"reject",solicitud_id:id,estatus:"rechazada"})}if(action!=="approve")return json({error:"Acción no soportada"},400);if(String(row.estatus||"pendiente").toLowerCase()!=="pendiente")return json({error:"La solicitud ya fue procesada"},409);const useSuggested=body?.use_suggested===true||body?.use_suggested==="true",nivel=String(row.match_nivel||"").toLowerCase(),allowAutoSuggested=nivel==="alto"||useSuggested;
const forcedCliente=clean(body?.cliente_id)||clean(row.cliente_id)||(allowAutoSuggested?clean(row.cliente_id_sugerido):"")||null;
const forcedContacto=clean(body?.contacto_id)||clean(row.contacto_id)||(allowAutoSuggested?clean(row.contacto_id_sugerido):"")||null;
const cliente=await ensureCliente(s,row,forcedCliente),main=await ensurePrincipal(s,row,cliente.id,forcedContacto),alt=await ensureAlterno(s,row,cliente.id);
await hist(s,row,cliente.id,main.contacto.id,main.accion,false);if(alt?.contacto?.id)await hist(s,row,cliente.id,alt.contacto.id,alt.accion,true);
const up=await s.from("solicitudes_registro").update({estatus:"aprobada",cliente_id:cliente.id,contacto_id:main.contacto.id,requiere_revision:false,actualizado_en:now()}).eq("id",id);if(up.error)throw new Error(up.error.message);
await bitacora(s,"solicitud_registro_aprobada",cliente.id,{solicitud_id:id,cliente_id:cliente.id,contacto_id:main.contacto.id,contacto_alterno_id:alt?.contacto?.id||null,actor_id:a.uid,actor:a.nombre,match_nivel:row.match_nivel||null,match_score:row.match_score||null,cliente_id_sugerido:row.cliente_id_sugerido||null,contacto_id_sugerido:row.contacto_id_sugerido||null,accion_contacto:main.accion});
return json({ok:true,action:"approve",solicitud_id:id,estatus:"aprobada",cliente_id:cliente.id,contacto_id:main.contacto.id,contacto_alterno_id:alt?.contacto?.id||null,accion_contacto:main.accion})}catch(e){if(e instanceof Response)return e;return json({error:e instanceof Error?e.message:"Error inesperado"},500)}});