import { supabase as s, guardSession, logAction, msg, fmt } from "./supabase.js";
import { $, toast, show, hide, esc, norm, debounce, bindModal, initAppRail, setAppRole, initAppPanel, setRailOpenCount } from "./global.js";
const ST={rows:[],current:null,busy:false};

const statusCls=v=>norm(v)==="aprobada"?"ok":norm(v)==="rechazada"?"bad":"warn";
const isPend=v=>norm(v)==="pendiente";
const byId=id=>ST.rows.find(x=>String(x.id)===String(id))||null;
const filesOf=r=>Array.isArray(r?.archivos)?r.archivos:[];
const rowText=r=>`${r?.nombre||""} ${r?.correo||""} ${r?.telefono||""} ${r?.estatus||""} ${r?.contacto||""} ${r?.comentarios||""}`;
const canApprove=r=>!!r&&isPend(r.estatus)&&!r.cliente_id;
const setBusy=v=>{ST.busy=!!v;$("#approveBtn")&&( $("#approveBtn").disabled=ST.busy );$("#rejectBtn")&&( $("#rejectBtn").disabled=ST.busy );$("#refreshBtn")&&( $("#refreshBtn").disabled=ST.busy )};

const queryRows=()=>{const q=norm($("#q")?.value),f=norm($("#fStatus")?.value);return ST.rows.filter(r=>(!q||norm(rowText(r)).includes(q))&&(!f||norm(r.estatus)===f))};

const renderKpis=()=>{$("#kTotal").textContent=ST.rows.length;$("#kPend").textContent=ST.rows.filter(x=>isPend(x.estatus)).length;$("#kAprob").textContent=ST.rows.filter(x=>norm(x.estatus)==="aprobada").length};

const rowCard=r=>`<article class="item alta-row" data-id="${esc(String(r.id))}"><div class="alta-main"><div><div class="alta-name">${esc(r.nombre||"Sin nombre")}</div><div class="alta-sub">${esc(r.correo||"Sin correo")} · ${esc(r.telefono||"Sin teléfono")}</div></div><div class="alta-files">${filesOf(r).slice(0,4).map(f=>`<span class="file-pill">📎 ${esc(f.nombre||f.name||"archivo")}</span>`).join("")}</div></div><div class="alta-meta"><span class="pill ${statusCls(r.estatus)}">${esc(r.estatus||"pendiente")}</span><div class="alta-sub">${r.creado_en?esc(new Date(r.creado_en).toLocaleString("es-MX")):""}</div><div class="alta-sub">${esc(r.contacto||r.comentarios||"")}</div></div><div class="alta-actions"><button class="mini" data-act="view" data-id="${esc(String(r.id))}">Ver</button>${isPend(r.estatus)?`<button class="mini" data-act="approve" data-id="${esc(String(r.id))}">Aprobar</button><button class="mini" data-act="reject" data-id="${esc(String(r.id))}">Rechazar</button>`:""}</div></article>`;

const render=()=>{const rows=queryRows();renderKpis();$("#list").innerHTML=rows.length?rows.map(rowCard).join(""):`<div class="empty-state">No hay solicitudes con esos filtros.</div>`};

const detailHtml=r=>`<div class="box"><div class="k">Correo</div><div class="v small">${esc(r.correo||"—")}</div></div><div class="box"><div class="k">Teléfono</div><div class="v small">${esc(r.telefono||"—")}</div></div><div class="box"><div class="k">Contacto</div><div class="v small">${esc(r.contacto||"—")}</div></div><div class="box"><div class="k">Estatus</div><div class="v small">${esc(r.estatus||"pendiente")}</div></div><div class="box"><div class="k">Fecha</div><div class="v small">${r.creado_en?esc(fmt(r.creado_en)||new Date(r.creado_en).toLocaleDateString("es-MX")):"—"}</div></div><div class="box"><div class="k">Cliente ligado</div><div class="v small">${esc(r.cliente_id||"—")}</div></div><div class="box" style="grid-column:1/-1"><div class="k">Comentarios</div><div class="v small">${esc(r.comentarios||"—")}</div></div>${filesOf(r).length?`<div class="box" style="grid-column:1/-1"><div class="k">Archivos</div><div class="v small alta-files">${filesOf(r).map(f=>`<span class="file-pill">📎 ${esc(f.nombre||f.name||"archivo")}</span>`).join("")}</div></div>`:""}`;

const syncDetailState=()=>{const r=ST.current;if(!r)return;$("#dTitle").textContent=r.nombre||"Solicitud";$("#detailBody").innerHTML=detailHtml(r);$("#approveBtn").disabled=ST.busy||!canApprove(r);$("#rejectBtn").disabled=ST.busy||!isPend(r.estatus);$("#detailStatus").textContent="Listo."};

const openDetail=id=>{const r=byId(id);if(!r)return;ST.current=r;syncDetailState();show("#detailModal")};
const closeDetail=()=>{ST.current=null;hide("#detailModal")};
const findExistingClient=async row=>{const q=(row?.correo||"").trim();if(q){const byMail=await s.from("clientes").select("id,nombre").eq("correo",q).limit(1).maybeSingle();if(byMail.data)return byMail.data}const name=(row?.nombre||"").trim();if(name){const byName=await s.from("clientes").select("id,nombre").eq("nombre",name).limit(1).maybeSingle();if(byName.data)return byName.data}return null};

const createClientFromRequest=async row=>await s.from("clientes").insert({nombre:row.nombre,correo:row.correo,telefono:row.telefono,comentarios:row.comentarios||"",rol_responsable:"soporte",estatus:"activo"}).select().single();

const approve=async id=>{const row=byId(id);if(!row||ST.busy)return;if(!canApprove(row))return toast(row?.cliente_id?"Ya estaba ligada a un cliente":"La solicitud ya no está pendiente","warn");setBusy(true);$("#detailStatus")&&($("#detailStatus").textContent="Creando cliente...");const existing=await findExistingClient(row);if(existing){const up=await s.from("solicitudes_alta").update({estatus:"aprobada",cliente_id:existing.id}).eq("id",id);if(up.error){setBusy(false);return toast(msg(up.error),"bad")}await logAction({accion:"solicitud_aprobada_vinculada",cliente_id:existing.id,detalle:{solicitud_id:id}}).catch(()=>{});toast("Solicitud vinculada a cliente existente","ok");await load();setBusy(false);closeDetail();return;}const ins=await createClientFromRequest(row);if(ins.error){setBusy(false);return toast(msg(ins.error),"bad")}const up=await s.from("solicitudes_alta").update({estatus:"aprobada",cliente_id:ins.data.id}).eq("id",id);if(up.error){setBusy(false);return toast(msg(up.error),"bad")}await logAction({accion:"solicitud_aprobada",cliente_id:ins.data.id,detalle:{solicitud_id:id}}).catch(()=>{});toast("Cliente creado","ok");await load();setBusy(false);closeDetail();};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
const rejectRow=async id=>{const row=byId(id);if(!row||ST.busy)return;if(!isPend(row.estatus))return toast("La solicitud ya no está pendiente","warn");setBusy(true);$("#detailStatus")&&($("#detailStatus").textContent="Rechazando solicitud...");const up=await s.from("solicitudes_alta").update({estatus:"rechazada"}).eq("id",id);if(up.error){setBusy(false);return toast(msg(up.error),"bad")}await logAction({accion:"solicitud_rechazada",detalle:{solicitud_id:id}}).catch(()=>{});toast("Solicitud rechazada","warn");await load();setBusy(false);closeDetail()};

const onListClick=async e=>{const b=e.target.closest("[data-act][data-id]");if(!b)return;const {act,id}=b.dataset;if(act==="view")openDetail(id);if(act==="approve")await approve(id);if(act==="reject")await rejectRow(id)};
const load=async()=>{const ok=await guardSession("index.html");if(!ok)return;const profile=(await s.from("perfiles").select("*").limit(1).maybeSingle()).data||{rol:"soporte"};setAppRole(profile.rol||"soporte");initAppRail("altas");initAppPanel();setRailOpenCount(0);const {data,error}=await s.from("solicitudes_alta").select("*").order("creado_en",{ascending:false});if(error)return toast(msg(error),"bad");ST.rows=data||[];render()};
const bind=()=>{$("#refreshBtn")?.addEventListener("click",load);$("#q")?.addEventListener("input",debounce(render,180));$("#fStatus")?.addEventListener("change",render);$("#list")?.addEventListener("click",onListClick);$("#closeDetail")?.addEventListener("click",closeDetail);$("#approveBtn")?.addEventListener("click",()=>ST.current&&approve(ST.current.id));$("#rejectBtn")?.addEventListener("click",()=>ST.current&&rejectRow(ST.current.id));document.addEventListener("keydown",e=>e.key==="Escape"&&!$("#detailModal")?.hasAttribute("hidden")&&closeDetail());bindModal("#detailModal",".icon-btn")};

document.addEventListener("DOMContentLoaded",()=>{bind();load().catch(err=>toast(msg(err),"bad"))});


const findExistingClient=async row=>{const mail=(row?.correo||"").trim();if(mail){const byMail=await s.from("clientes").select("id,nombre").eq("correo",mail).limit(1).maybeSingle();if(byMail.data)return byMail.data;}const name=(row?.nombre||"").trim();if(name){const byName=await s.from("clientes").select("id,nombre").eq("nombre",name).limit(1).maybeSingle();if(byName.data)return byName.data;}return null;};
