import { supabase as s, guardSession, logAction, msg, fmt } from "./supabase.js";
import { $, toast, show, hide, esc, norm, debounce, bindModal, ensureAppShell, setAppRole, setRailOpenCount, setGlobalSearchData, setBreadcrumb } from "./global.js";
const ST={rows:[],current:null,busy:false};

const statusCls=v=>norm(v)==="aprobada"?"ok":norm(v)==="rechazada"?"bad":"warn";
const isPend=v=>norm(v)==="pendiente";
const byId=id=>ST.rows.find(x=>String(x.id)===String(id))||null;
const filesOf=r=>Array.isArray(r?.archivos)?r.archivos:[];
const rowText=r=>`${r?.nombre||""} ${r?.correo||""} ${r?.telefono||""} ${r?.estatus||""} ${r?.contacto||""} ${r?.comentarios||""} ${r?.contacto_principal_nombre||""} ${r?.contacto_principal_correo||""} ${r?.contacto_principal_telefono||""} ${r?.contacto_alterno_nombre||""} ${r?.contacto_alterno_correo||""}`;
const canApprove=r=>!!r&&isPend(r.estatus)&&!r.cliente_id;
const setBusy=v=>{ST.busy=!!v;$("#approveBtn")&&( $("#approveBtn").disabled=ST.busy );$("#rejectBtn")&&( $("#rejectBtn").disabled=ST.busy );$("#refreshBtn")&&( $("#refreshBtn").disabled=ST.busy )};

const queryRows=()=>{const q=norm($("#q")?.value),f=norm($("#fStatus")?.value);return ST.rows.filter(r=>(!q||norm(rowText(r)).includes(q))&&(!f||norm(r.estatus)===f))};

const renderKpis=()=>{$("#kTotal").textContent=ST.rows.length;$("#kPend").textContent=ST.rows.filter(x=>isPend(x.estatus)).length;$("#kAprob").textContent=ST.rows.filter(x=>norm(x.estatus)==="aprobada").length};

const rowCard=r=>`<article class="item alta-row" data-id="${esc(String(r.id))}"><div class="alta-main"><div><div class="alta-name">${esc(r.nombre||"Sin nombre")}</div><div class="alta-sub">${esc(r.correo||"Sin correo")} · ${esc(r.telefono||"Sin teléfono")}</div><div class="alta-sub">${esc(r.contacto_principal_nombre||r.contacto||"Sin contacto principal")} ${r.contacto_principal_correo?`· ${esc(r.contacto_principal_correo)}`:""}</div></div><div class="alta-files">${filesOf(r).slice(0,4).map(f=>`<span class="file-pill">📎 ${esc(f.nombre||f.name||"archivo")}</span>`).join("")}</div></div><div class="alta-meta"><span class="pill ${statusCls(r.estatus)}">${esc(r.estatus||"pendiente")}</span><div class="alta-sub">${r.creado_en?esc(new Date(r.creado_en).toLocaleString("es-MX")):""}</div><div class="alta-sub">${esc(r.contacto_principal_puesto||r.comentarios||"")}</div></div><div class="alta-actions"><button class="mini" data-act="view" data-id="${esc(String(r.id))}">Ver</button>${isPend(r.estatus)?`<button class="mini" data-act="approve" data-id="${esc(String(r.id))}">Aprobar</button><button class="mini" data-act="reject" data-id="${esc(String(r.id))}">Rechazar</button>`:""}</div></article>`;

const render=()=>{const rows=queryRows();renderKpis();$("#list").innerHTML=rows.length?rows.map(rowCard).join(""):`<div class="empty-state">No hay solicitudes con esos filtros.</div>`};

const detailHtml=r=>`<div class="box"><div class="k">Correo empresa</div><div class="v small">${esc(r.correo||"—")}</div></div><div class="box"><div class="k">Teléfono empresa</div><div class="v small">${esc(r.telefono||"—")}</div></div><div class="box"><div class="k">Contacto principal</div><div class="v small">${esc(r.contacto_principal_nombre||r.contacto||"—")}</div></div><div class="box"><div class="k">Puesto contacto principal</div><div class="v small">${esc(r.contacto_principal_puesto||"—")}</div></div><div class="box"><div class="k">Correo contacto principal</div><div class="v small">${esc(r.contacto_principal_correo||"—")}</div></div><div class="box"><div class="k">Teléfono contacto principal</div><div class="v small">${esc(r.contacto_principal_telefono||"—")}</div></div><div class="box"><div class="k">Método preferido</div><div class="v small">${esc(r.metodo_contacto_preferido||"—")}</div></div><div class="box"><div class="k">Horario contacto</div><div class="v small">${esc(r.horario_contacto||"—")}</div></div><div class="box"><div class="k">Cumpleaños</div><div class="v small">${esc(r.cumpleanos_contacto||"—")}</div></div><div class="box"><div class="k">Contacto alterno</div><div class="v small">${esc(r.contacto_alterno_nombre||"—")}</div></div><div class="box"><div class="k">Correo alterno</div><div class="v small">${esc(r.contacto_alterno_correo||"—")}</div></div><div class="box"><div class="k">Teléfono alterno</div><div class="v small">${esc(r.contacto_alterno_telefono||"—")}</div></div><div class="box"><div class="k">Estatus</div><div class="v small">${esc(r.estatus||"pendiente")}</div></div><div class="box"><div class="k">Fecha</div><div class="v small">${r.creado_en?esc(fmt(r.creado_en)||new Date(r.creado_en).toLocaleDateString("es-MX")):"—"}</div></div><div class="box"><div class="k">Cliente ligado</div><div class="v small">${esc(r.cliente_id||"—")}</div></div><div class="box" style="grid-column:1/-1"><div class="k">Comentarios</div><div class="v small">${esc(r.comentarios||"—")}</div></div>${filesOf(r).length?`<div class="box" style="grid-column:1/-1"><div class="k">Archivos</div><div class="v small alta-files">${filesOf(r).map(f=>`<span class="file-pill">📎 ${esc(f.nombre||f.name||"archivo")}</span>`).join("")}</div></div>`:""}`;

const syncDetailState=()=>{const r=ST.current;if(!r)return;$("#dTitle").textContent=r.nombre||"Solicitud";$("#detailBody").innerHTML=detailHtml(r);$("#approveBtn").disabled=ST.busy||!isPend(r.estatus);$("#rejectBtn").disabled=ST.busy||!isPend(r.estatus);$("#detailStatus").textContent=isPend(r.estatus)?"Listo para crear o vincular cliente y contacto principal.":"Solicitud ya procesada."};

const openDetail=id=>{const r=byId(id);if(!r)return;ST.current=r;syncDetailState();show("#detailModal")};
const closeDetail=()=>{ST.current=null;hide("#detailModal")};
const findExistingClient=async row=>{const q=(row?.correo||"").trim();if(q){const byMail=await s.from("clientes").select("id,nombre").eq("correo",q).limit(1).maybeSingle();if(byMail.data)return byMail.data}const name=(row?.nombre||"").trim();if(name){const byName=await s.from("clientes").select("id,nombre").eq("nombre",name).limit(1).maybeSingle();if(byName.data)return byName.data}return null};
const findExistingContact=async(row,cliente_id)=>{if(!cliente_id)return null;const correo=(row?.contacto_principal_correo||"").trim(),telefono=(row?.contacto_principal_telefono||"").trim();const q=await s.from("clientes_contactos").select("id,nombre,correo,telefono").eq("cliente_id",cliente_id).limit(30);if(q.error||!q.data?.length)return null;return q.data.find(x=>(correo&&norm(x.correo||"")===norm(correo))||(telefono&&norm((x.telefono||"").replace(/\D+/g,""))===norm((telefono||"").replace(/\D+/g,""))))||null};
const createClientFromRequest=async row=>await s.from("clientes").insert({nombre:row.nombre,correo:row.correo,telefono:row.telefono,comentarios:row.comentarios||"",rol_responsable:"soporte",estatus:"activo",origen_registro:"alta_publica"}).select().single(); const createPrimaryContactFromRequest=async(row,cliente_id)=>await s.from("clientes_contactos").insert({cliente_id,nombre:row.contacto_principal_nombre||row.contacto||row.nombre||"Contacto principal",puesto:row.contacto_principal_puesto||null,correo:row.contacto_principal_correo||null,telefono:row.contacto_principal_telefono||null,whatsapp:row.contacto_principal_telefono||null,metodo_contacto_preferido:row.metodo_contacto_preferido||null,es_principal:true,activo:true,origen_alta:"alta_publica",cumpleanos:row.cumpleanos_contacto||null,notas:row.comentarios||null,ultima_interaccion_en:new Date().toISOString()}).select().single();
const createContactHistory=async(row,cliente_id,contacto_id)=>await s.from("clientes_contacto_historial").insert({contacto_id,cliente_id,nombre:row.contacto_principal_nombre||row.contacto||null,puesto:row.contacto_principal_puesto||null,correo:row.contacto_principal_correo||null,telefono:row.contacto_principal_telefono||null,whatsapp:row.contacto_principal_telefono||null,metodo_contacto_preferido:row.metodo_contacto_preferido||null,accion:"confirmacion",origen:"alta_publica"});
const findAlternateContact=async(row,cliente_id)=>{if(!cliente_id)return null;const correo=(row?.contacto_alterno_correo||"").trim(),telefono=(row?.contacto_alterno_telefono||"").trim();if(!correo&&!telefono)return null;const q=await s.from("clientes_contactos").select("id,nombre,correo,telefono").eq("cliente_id",cliente_id).limit(30);if(q.error||!q.data?.length)return null;return q.data.find(x=>(correo&&norm(x.correo||"")===norm(correo))||(telefono&&norm((x.telefono||"").replace(/\D+/g,""))===norm((telefono||"").replace(/\D+/g,""))))||null};
const createAlternateContactFromRequest=async(row,cliente_id)=>{if(!(row?.contacto_alterno_nombre||row?.contacto_alterno_correo||row?.contacto_alterno_telefono))return{data:null,error:null};return await s.from("clientes_contactos").insert({cliente_id,nombre:row.contacto_alterno_nombre||"Contacto adicional",puesto:row.contacto_alterno_puesto||null,correo:row.contacto_alterno_correo||null,telefono:row.contacto_alterno_telefono||null,whatsapp:row.contacto_alterno_telefono||null,metodo_contacto_preferido:null,es_principal:false,activo:true,origen_alta:"alta_publica",cumpleanos:null,notas:"Contacto adicional registrado desde alta pública",ultima_interaccion_en:new Date().toISOString()}).select().single()};
const createAlternateHistory=async(row,cliente_id,contacto_id)=>{if(!contacto_id)return null;return await s.from("clientes_contacto_historial").insert({contacto_id,cliente_id,nombre:row.contacto_alterno_nombre||null,puesto:row.contacto_alterno_puesto||null,correo:row.contacto_alterno_correo||null,telefono:row.contacto_alterno_telefono||null,whatsapp:row.contacto_alterno_telefono||null,metodo_contacto_preferido:null,accion:"confirmacion",origen:"alta_publica"})};
const approve=async id=>{const row=byId(id);if(!row||ST.busy)return;if(!isPend(row.estatus))return toast("La solicitud ya no está pendiente","warn");setBusy(true);$("#detailStatus")&&($("#detailStatus").textContent="Validando cliente y contactos...");const existing=await findExistingClient(row);let cliente_id=existing?.id||null,contacto_id=null,contacto_alterno_id=null;if(!cliente_id){const ins=await createClientFromRequest(row);if(ins.error){setBusy(false);return toast(msg(ins.error),"bad")}cliente_id=ins.data.id}const existingContact=await findExistingContact(row,cliente_id);if(existingContact){contacto_id=existingContact.id}else{const c=await createPrimaryContactFromRequest(row,cliente_id);if(c.error){setBusy(false);return toast(msg(c.error),"bad")}contacto_id=c.data.id;await createContactHistory(row,cliente_id,contacto_id).catch(()=>{})}const altExisting=await findAlternateContact(row,cliente_id);if(altExisting)contacto_alterno_id=altExisting.id;else{const alt=await createAlternateContactFromRequest(row,cliente_id);if(alt?.error){setBusy(false);return toast(msg(alt.error),"bad")}if(alt?.data?.id){contacto_alterno_id=alt.data.id;await createAlternateHistory(row,cliente_id,contacto_alterno_id).catch(()=>{})}}const up=await s.from("solicitudes_alta").update({estatus:"aprobada",cliente_id,contacto_id}).eq("id",id);if(up.error){setBusy(false);return toast(msg(up.error),"bad")}await logAction({accion:existing?"solicitud_aprobada_vinculada":"solicitud_aprobada",cliente_id,detalle:{solicitud_id:id,contacto_id,contacto_alterno_id}}).catch(()=>{});toast(contacto_alterno_id?(existing?"Solicitud vinculada y contactos consolidados":"Cliente y contactos creados"):(existing?"Solicitud vinculada y contacto consolidado":"Cliente y contacto principal creados"),"ok");await load();setBusy(false);closeDetail()};
const rejectRow=async id=>{const row=byId(id);if(!row||ST.busy)return;if(!isPend(row.estatus))return toast("La solicitud ya no está pendiente","warn");setBusy(true);$("#detailStatus")&&($("#detailStatus").textContent="Rechazando solicitud...");const up=await s.from("solicitudes_alta").update({estatus:"rechazada"}).eq("id",id);if(up.error){setBusy(false);return toast(msg(up.error),"bad")}await logAction({accion:"solicitud_rechazada",detalle:{solicitud_id:id}}).catch(()=>{});toast("Solicitud rechazada","warn");await load();setBusy(false);closeDetail()};

const onListClick=async e=>{const b=e.target.closest("[data-act][data-id]");if(!b)return;const {act,id}=b.dataset;if(act==="view")openDetail(id);if(act==="approve")await approve(id);if(act==="reject")await rejectRow(id)};
const load=async()=>{const ok=await guardSession("index.html");if(!ok)return;const profile=(await s.from("perfiles").select("*").limit(1).maybeSingle()).data||{rol:"soporte"};ensureAppShell({page:"altas",role:profile.rol||"soporte",title:"Altas",kicker:"Expiriti · revisión interna",actionsHtml:`<a class="mini btn-ghost" href="dashboard.html">Dashboard</a><button class="mini btn-ghost" id="refreshBtnTop" type="button">Actualizar</button><button class="mini" data-theme-toggle>🌓 <span data-theme-label>Claro</span></button>`});setAppRole(profile.rol||"soporte");setRailOpenCount(0);const {data,error}=await s.from("solicitudes_alta").select("*").order("creado_en",{ascending:false});if(error)return toast(msg(error),"bad");ST.rows=data||[];setGlobalSearchData({clientes:[],tickets:[]});setBreadcrumb([{label:"Panel",href:"dashboard.html"},{label:"Altas"}]);render()};
const bind=()=>{$("#refreshBtn")?.addEventListener("click",load);$("#refreshBtnTop")?.addEventListener("click",load);$("#q")?.addEventListener("input",debounce(render,180));$("#fStatus")?.addEventListener("change",render);$("#list")?.addEventListener("click",onListClick);$("#closeDetail")?.addEventListener("click",closeDetail);$("#approveBtn")?.addEventListener("click",()=>ST.current&&approve(ST.current.id));$("#rejectBtn")?.addEventListener("click",()=>ST.current&&rejectRow(ST.current.id));document.addEventListener("keydown",e=>e.key==="Escape"&&!$("#detailModal")?.hasAttribute("hidden")&&closeDetail());bindModal("#detailModal",".icon-btn")};

document.addEventListener("DOMContentLoaded",()=>{bind();load().catch(err=>toast(msg(err),"bad"))});
