import{supabase as s,openPdfSigned,fmt,msg,logAction}from"./supabase.js";
 
const SYSTEMS=[["CONTABILIDAD",["contabilidad","contabiliza","contab","usaconta"]],["BANCOS",["bancos"]],["NOMINAS",["nominas","nóminas","nomina"]],["XML_EN_LINEA",["xml","cfdi","xml en linea"]],["COMERCIAL_START",["comercial start","cstart","comstart"]],["COMERCIAL_PRO",["comercial pro","compro"]],["COMERCIAL_PREMIUM",["comercial premium","cpremium","compremium","premium"]],["FACTURA_ELECTRONICA",["factura electronica","factura electrónica","facturae","factura","fe"]],["EVALUA",["evalua","evalúa"]],["ANALIZA",["analiza"]],["VENDE",["vende"]],["OPTIMIZA",["optimiza"]],["ANTICIPA",["anticipa"]],["PERSONIA",["personia"]],["VPS",["vps","vpsplus","vps plus","servidor virtual","servidor"]],["VDI",["vdi","escritorio virtual"]]];
const NICE={CONTABILIDAD:"CONTPAQi Contabilidad",BANCOS:"CONTPAQi Bancos",NOMINAS:"CONTPAQi Nóminas",XML_EN_LINEA:"CONTPAQi XML en Línea",COMERCIAL_START:"CONTPAQi Comercial START",COMERCIAL_PRO:"CONTPAQi Comercial PRO",COMERCIAL_PREMIUM:"CONTPAQi Comercial PREMIUM",FACTURA_ELECTRONICA:"CONTPAQi Factura Electrónica",EVALUA:"CONTPAQi Evalúa",ANALIZA:"CONTPAQi Analiza",VENDE:"CONTPAQi Vende",OPTIMIZA:"CONTPAQi Optimiza",ANTICIPA:"CONTPAQi Anticipa",PERSONIA:"CONTPAQi Personia",VPS:"VPS",VDI:"VDI"};
const ICON={CONTABILIDAD:"📘",BANCOS:"🏦",NOMINAS:"🧾",XML_EN_LINEA:"🧷",COMERCIAL_START:"🛒",COMERCIAL_PRO:"🛍️",COMERCIAL_PREMIUM:"💼",FACTURA_ELECTRONICA:"🧾",EVALUA:"📊",ANALIZA:"📈",VENDE:"💳",OPTIMIZA:"⚙️",ANTICIPA:"⏩",PERSONIA:"👤",VPS:"🖥️",VDI:"🪟"};
const PREF_KEY="expiriti_cliente_prefs_v2",PREFS={density:"normal",maskSeries:true,autoUpload:false};

const normTxt=v=>(v||"").toString().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g," ").replace(/\s+/g," ").trim(),normFile=v=>normTxt(v).replace(/[^a-z0-9._-]+/g,"_"),tel=v=>(v||"").replace(/[^\d]/g,""),wa=v=>tel(v)?`https://wa.me/52${tel(v)}`:"#",call=v=>tel(v)?`tel:${tel(v)}`:"#",mail=v=>v?`mailto:${v}`:"#",byId=(arr,id)=>arr.find(x=>String(x.id)===String(id)),esc=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),mask=v=>{const s=(v||"").toString();return!s?"—":s.length<8?s:s.slice(0,4)+"••••"+s.slice(-4)};
const docsLive=docs=>docs.filter(x=>!x.eliminado),openTickets=tickets=>tickets.filter(t=>!["cerrado","resuelto"].includes((t.estado||"").toLowerCase())),sem=f=>!f?{t:"Sin vigencia",c:"neutral"}:(d=>d<0?{t:"Vencido",c:"bad"}:d<=30?{t:"Por vencer",c:"warn"}:{t:"Vigente",c:"ok"})(Math.ceil((new Date(f)-Date.now())/864e5));
const detectSistema=t=>{const x=normTxt(t);for(const[k,arr]of SYSTEMS)for(const a of arr)if(x.includes(normTxt(a)))return k;return""};
const parseFecha=v=>{const s=(v||"").toString().trim();if(!s)return null;let m=s.match(/(\d{4})-(\d{2})-(\d{2})/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/);if(m)return`${m[3]}-${String(m[2]).padStart(2,"0")}-${String(m[1]).padStart(2,"0")}`;m=s.match(/(\d{1,2})[-\/ ]([A-Za-zÁÉÍÓÚáéíóú]+)[-\/ ](\d{4})/);if(!m)return null;const mm={ene:1,enero:1,feb:2,febrero:2,mar:3,marzo:3,abr:4,abril:4,may:5,mayo:5,jun:6,junio:6,jul:7,julio:7,ago:8,agosto:8,sep:9,septiembre:9,set:9,oct:10,octubre:10,nov:11,noviembre:11,dic:12,diciembre:12}[normTxt(m[2]).slice(0,9)]||0;return mm?`${m[3]}-${String(mm).padStart(2,"0")}-${String(m[1]).padStart(2,"0")}`:null};
const extractData=txt=>{const g=r=>((txt.match(r)||[])[1]||"").trim(),sistemaRaw=g(/SISTEMA[:\s]*([^\n\r]+)/i)||g(/CONTPAQi[®\s]*([A-Za-zÁÉÍÓÚáéíóú+ ]+)/i);return{pdf_text:txt||"",sistema_norm:detectSistema(sistemaRaw||txt),sistema:sistemaRaw||"",version_comercial:g(/VERSI[ÓO]N[:\s]*([^\n\r]+)/i),tipo_documento:g(/TIPO(?: DOCUMENTO)?[:\s]*([^\n\r]+)/i),tipo_licencia:g(/LICENCIA[:\s]*([^\n\r]+)/i),usuarios:g(/USUARIOS[:\s]*([^\n\r]+)/i)||g(/Usuarios[:\s]*([^\n\r]+)/i),empresas_info:g(/EMPRESAS[:\s]*([^\n\r]+)/i)||g(/Empresas[:\s]*([^\n\r]+)/i),numero_serie:g(/N[ÚU]MERO DE SERIE[:\s]*([A-Z0-9\-]+)/i)||g(/SERIE ORIGEN[:\s]*([A-Z0-9\-]+)/i)||g(/SERIE[:\s]*([A-Z0-9\-]+)/i),verificador:g(/VERIFICADOR[:\s]*([A-Z0-9\-]+)/i),fin_vigencia:parseFecha(g(/VIGENCIA[:\s]*([^\n\r]+)/i)||g(/Vigencia[:\s]*([^\n\r]+)/i)),empresa_certificado:g(/EMPRESA[:\s]*([^\n\r]+)/i)||g(/RAZ[ÓO]N SOCIAL[:\s]*([^\n\r]+)/i),lectura_pdf_ok:!!txt,requiere_revision:!g(/VERIFICADOR[:\s]*([A-Z0-9\-]+)/i)&&!g(/N[ÚU]MERO DE SERIE[:\s]*([A-Z0-9\-]+)/i)}};
const ensurePdfLib=()=>new Promise((res,rej)=>{if(window.pdfjsLib)return res(window.pdfjsLib);const sc=document.createElement("script");sc.src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js";sc.onload=()=>res(window.pdfjsLib);sc.onerror=rej;document.head.appendChild(sc)});
const readPDF=async file=>{const pdfjsLib=await ensurePdfLib(),ab=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:ab}).promise;let txt="";for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();txt+=c.items.map(x=>x.str).join(" ")+"\n"}return extractData(txt)};
const existsDoc=async(clientId,nameNorm,serie="")=>{let q=s.from("documentos").select("id").eq("cliente_id",clientId).eq("eliminado",false).limit(1);q=serie?q.eq("numero_serie",serie):q.eq("nombre_archivo_norm",nameNorm);const{data}=await q;return!!data?.length};

const healthState=(docs,tickets)=>{const a=docsLive(docs),open=openTickets(tickets),urgent=open.filter(t=>t.prioridad==="urgente").length,bad=a.filter(d=>sem(d.fin_vigencia).t==="Vencido").length,warn=a.filter(d=>sem(d.fin_vigencia).t==="Por vencer").length;if(urgent||bad>=1)return{txt:"Roja",cls:"bad"};if(warn||open.some(t=>["alta","media"].includes(t.prioridad)))return{txt:"Amarilla",cls:"warn"};return{txt:"Verde",cls:"ok"}};
const criticalState=(docs,tickets)=>{const recent=tickets.filter(t=>(Date.now()-new Date(t.fecha_creacion).getTime())/864e5<=7).length,urgent=openTickets(tickets).some(t=>t.prioridad==="urgente"),expired=docsLive(docs).filter(d=>sem(d.fin_vigencia).t==="Vencido").length;return recent>=3||urgent||expired>=2};
const profileCompletion=(client,docs)=>{const checks=[!!client?.nombre,!!client?.telefono,!!client?.correo,!!client?.rol_responsable,!!client?.comentarios,docsLive(docs).length>0,docsLive(docs).some(d=>sem(d.fin_vigencia).t==="Vigente")],score=Math.round(checks.filter(Boolean).length/checks.length*100),missing=[];if(!client?.correo)missing.push("correo");if(!client?.rol_responsable)missing.push("responsable");if(!docsLive(docs).some(d=>sem(d.fin_vigencia).t==="Vigente"))missing.push("1 documento vigente");return{score,missing}};
const nextSuggestedAction=(client,docs,tickets)=>{if(!client?.correo)return"Completar correo del cliente";if(docsLive(docs).some(d=>d.requiere_revision||!d.lectura_pdf_ok))return"Revisar PDF con lectura incompleta";if(docsLive(docs).some(d=>sem(d.fin_vigencia).t==="Vencido"))return"Crear ticket de renovación";if(docsLive(docs).some(d=>sem(d.fin_vigencia).t==="Por vencer"))return"Contactar por WhatsApp para renovación";if(!client?.rol_responsable)return"Asignar responsable";return"Seguimiento normal del cliente"};

const loadPrefs=()=>{try{Object.assign(PREFS,JSON.parse(localStorage.getItem(PREF_KEY)||"{}"))}catch{};return PREFS},savePrefs=()=>localStorage.setItem(PREF_KEY,JSON.stringify(PREFS));
const loadClient=async clientId=>{const{data,error}=await s.from("clientes").select("*").eq("id",clientId).single();if(error||!data)throw new Error("Cliente no encontrado");return data};
const loadDocs=async clientId=>{const{data,error}=await s.from("documentos").select("*").eq("cliente_id",clientId).eq("eliminado",false).order("fecha_subida",{ascending:false});if(error)throw error;return data||[]};
const loadTickets=async clientId=>{const{data,error}=await s.from("tickets").select("*").eq("cliente_id",clientId).order("fecha_actualizacion",{ascending:false});if(error)throw error;return data||[]};
const loadBitacora=async clientId=>{const{data,error}=await s.from("bitacora").select("*").eq("cliente_id",clientId).order("fecha",{ascending:false}).limit(20);if(error)return[];return data||[]};

const openDoc=async(doc,clientId)=>{await logAction({accion:"abrio_pdf",documento_id:doc.id,cliente_id:clientId,detalle:{nombre_archivo:doc.nombre_archivo||"",storage_path:doc.storage_path||doc.url_pdf||""}}).catch(()=>{});await openPdfSigned(doc.storage_path||doc.url_pdf,8)};
const uploadClientPdf=async({clientId,file,data,userId,vigI,vigF,origenCarga,clientName})=>{const clean=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_").replace(/[^a-zA-Z0-9._()-]/g,""),nameNorm=normFile(file.name),serie=data.numero_serie||"";if(await existsDoc(clientId,nameNorm,serie))throw new Error("Ese PDF ya existe para este cliente.");const path=`${clientId}/${Date.now()}_${clean}`,up=await s.storage.from("certificados").upload(path,file,{upsert:false,contentType:"application/pdf"});if(up.error)throw up.error;const payload={cliente_id:clientId,nombre_archivo:file.name,nombre_archivo_norm:nameNorm,url_pdf:path,storage_path:path,sistema:data.sistema||"",sistema_norm:data.sistema_norm||detectSistema(file.name),version_comercial:data.version_comercial||null,tipo_documento:data.tipo_documento||null,tipo_licencia:data.tipo_licencia||null,usuarios:data.usuarios||null,empresas_info:data.empresas_info||null,numero_serie:data.numero_serie||null,verificador:data.verificador||null,inicio_vigencia:vigI||null,fin_vigencia:data.fin_vigencia||vigF||null,empresa_certificado:data.empresa_certificado||clientName||null,pdf_text:data.pdf_text||null,texto_extraido:data.pdf_text||null,subido_por:userId,tamano_bytes:file.size||null,mime_type:file.type||"application/pdf",lectura_pdf_ok:!!data.lectura_pdf_ok,lectura_pdf_error:data.lectura_pdf_error||null,requiere_revision:!!data.requiere_revision,origen_carga:origenCarga||"cliente.html"},ins=await s.from("documentos").insert(payload).select("*").single();if(ins.error){try{await s.storage.from("certificados").remove([path])}catch{};throw ins.error}await logAction({accion:"subio_pdf",documento_id:ins.data.id,cliente_id:clientId,detalle:{nombre_archivo:file.name,sistema:ins.data.sistema_norm||ins.data.sistema||"",origen_carga:payload.origen_carga}}).catch(()=>{});return ins.data};
const saveTicket=async({clientId,docId,titulo,descripcion,tipo,prioridad,userId,files=[]})=>{const payload={cliente_id:clientId,documento_id:docId||null,titulo,descripcion,tipo,prioridad,creado_por:userId,origen:"cliente.html"},res=await s.from("tickets").insert(payload).select("*").single();if(res.error)throw res.error;for(const file of files){const clean=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_").replace(/[^a-zA-Z0-9._()-]/g,""),path=`tickets/${clientId}/${res.data.id}/${Date.now()}_${clean}`,up=await s.storage.from("certificados").upload(path,file,{upsert:false,contentType:file.type||"application/octet-stream"});if(up.error)continue;await s.from("ticket_archivos").insert({ticket_id:res.data.id,nombre_archivo:file.name,url_archivo:path,mime_type:file.type||null,subido_por:userId})}await logAction({accion:"creo_ticket",documento_id:docId||null,cliente_id:clientId,detalle:{titulo,prioridad,tipo,adjuntos:files.length}}).catch(()=>{});return res.data};
const saveCRM=async(clientId,payload)=>{const {error}=await s.from("clientes").update(payload).eq("id",clientId);if(error)throw error;await logAction({accion:"actualizo_crm",cliente_id:clientId,detalle:{estatus:payload.estatus,favorito:payload.favorito,responsable:payload.rol_responsable||""}}).catch(()=>{});return payload};

export{SYSTEMS,NICE,ICON,PREFS,normTxt,normFile,tel,wa,call,mail,byId,esc,mask,docsLive,openTickets,sem,detectSistema,parseFecha,extractData,ensurePdfLib,readPDF,existsDoc,healthState,criticalState,profileCompletion,nextSuggestedAction,loadPrefs,savePrefs,loadClient,loadDocs,loadTickets,loadBitacora,openDoc,uploadClientPdf,saveTicket,saveCRM,fmt,msg};
