import{supabase as s,guardSession,logout,openPdfSigned,fmt,msg,getProfile,logAction}from"./supabase.js";
import{$,$$,toast,show,hide,copyTxt}from"./global.js";
import{PREFS,normTxt,wa,readPDF,uploadClientPdf,saveTicket as saveTicketCore,saveCRM as saveCRMCore}from"./cliente.core.js";
import{renderHeader,renderStats,renderSystems,renderDocs,renderTicketsMini,renderTimeline,renderBitacora,renderRenewals,renderChecklist,renderCRM,previewUpload,renderTicketFiles,renderAccess}from"./cliente.ui.js";

const qp=new URLSearchParams(location.search),CLIENT_ID=qp.get("id")||localStorage.getItem("expiriti_last_client")||"",PREF_KEY="expiriti_cliente_prefs_v2",ACCESS_KEY=id=>`expiriti_access_${id}`;
let USER=null,PROFILE=null,CLIENT=null,DOCS=[],TICKETS=[],BIT=[],CURRENT_SYS="",CURRENT_VIEW="cards",PICKED_FILE=null,PICKED_DATA=null,TICKET_FILES=[];

const docsLive=()=>DOCS.filter(x=>!x.eliminado),byId=(arr,id)=>arr.find(x=>String(x.id)===String(id)),canAccess=()=>["soporte","admin"].includes((PROFILE?.rol||"soporte").toLowerCase());
const setCurrentSys=v=>CURRENT_SYS=v||"",setView=v=>CURRENT_VIEW=v||"cards";
const loadPrefs=()=>{try{Object.assign(PREFS,JSON.parse(localStorage.getItem(PREF_KEY)||"{}"))}catch{}applyPrefsUI()},savePrefs=()=>{localStorage.setItem(PREF_KEY,JSON.stringify(PREFS));applyPrefsUI()};
const applyPrefsUI=()=>{document.body.classList.toggle("compact",PREFS.density==="compact"||CURRENT_VIEW==="compact");$("#prefMaskSeries")&&($("#prefMaskSeries").checked=!!PREFS.maskSeries);$("#prefAutoUpload")&&($("#prefAutoUpload").checked=!!PREFS.autoUpload);$$("[data-view]").forEach(b=>b.classList.toggle("active",(b.dataset.view||"")===(CURRENT_VIEW||"cards")))};
const setTab=name=>{$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));$$(".panel").forEach(p=>p.classList.toggle("active",p.id===`panel-${name}`));$$(".tab-panel").forEach(p=>p.classList.toggle("hidden",p.id!==`panel-${name}`))};
const openDrawer=id=>show(id.startsWith("#")?id:`#${id}`),closeDrawer=id=>hide(id.startsWith("#")?id:`#${id}`);
const applyRoleUI=()=>{document.body.dataset.role=(PROFILE?.rol||"soporte").toLowerCase()};

const loadClient=async()=>{const{data,error}=await s.from("clientes").select("*").eq("id",CLIENT_ID).single();if(error||!data){toast("Cliente no encontrado","bad");location.href="dashboard.html";return}CLIENT=data};
const loadDocs=async()=>{const{data,error}=await s.from("documentos").select("*").eq("cliente_id",CLIENT_ID).eq("eliminado",false).order("fecha_subida",{ascending:false});if(error)throw error;DOCS=data||[]};
const loadTickets=async()=>{const{data,error}=await s.from("tickets").select("*").eq("cliente_id",CLIENT_ID).order("fecha_actualizacion",{ascending:false});if(error)throw error;TICKETS=data||[]};
const loadBitacora=async()=>{const{data,error}=await s.from("bitacora").select("*").eq("cliente_id",CLIENT_ID).order("fecha",{ascending:false}).limit(40);BIT=error?[]:(data||[])};
const bootData=async()=>Promise.all([loadClient(),loadDocs(),loadTickets(),loadBitacora()]);

const loadAccess=()=>{if(!canAccess())return renderAccess({acc:{}});let d={};try{d=JSON.parse(localStorage.getItem(ACCESS_KEY(CLIENT_ID))||"{}")}catch{}renderAccess({acc:d})};
const saveAccess=async()=>{if(!canAccess())return $("#accessStatus")&&($("#accessStatus").textContent="Sin permisos.");const payload={vps:$("#accVps")?.value.trim()||"",rdpPort:$("#accRdpPort")?.value.trim()||"",user:$("#accUser")?.value.trim()||"",pass:$("#accPass")?.value.trim()||"",anydesk:$("#accAnydesk")?.value.trim()||"",extra:$("#accExtra")?.value.trim()||"",notes:$("#accNotes")?.value.trim()||"",updatedAt:new Date().toISOString(),updatedBy:USER?.id||null};localStorage.setItem(ACCESS_KEY(CLIENT_ID),JSON.stringify(payload));$("#accessStatus")&&($("#accessStatus").textContent="Accesos guardados.");await logAction({accion:"actualizo_accesos",cliente_id:CLIENT_ID,detalle:{vps:!!payload.vps,rdp:!!payload.rdpPort,user:!!payload.user,anydesk:!!payload.anydesk}}).catch(()=>{});toast("Accesos guardados","ok")};

const renderAll=()=>{renderHeader({CLIENT,CLIENT_ID,PREFS,DOCS,TICKETS});renderStats({DOCS,TICKETS});renderSystems({DOCS,CURRENT_SYS,setCurrentSys,renderDocs:()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer})});renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer});renderTicketsMini({TICKETS});renderTimeline({DOCS,TICKETS,BIT});renderBitacora({BIT});renderRenewals({DOCS,CLIENT,openDoc,openTicketDrawer});renderChecklist({CLIENT,DOCS,TICKETS});renderCRM({CLIENT});loadAccess();applyPrefsUI()};

const openDoc=async id=>{const d=byId(DOCS,id);if(!d)return;await logAction({accion:"abrio_pdf",documento_id:d.id,cliente_id:CLIENT_ID,detalle:{nombre_archivo:d.nombre_archivo||"",storage_path:d.storage_path||d.url_pdf||""}}).catch(()=>{});await openPdfSigned(d.storage_path||d.url_pdf,8).catch(err=>toast(msg(err),"bad"))};
const onPickFile=async file=>{if(!file||!/\.pdf$/i.test(file.name))return toast("Solo PDFs","warn");PICKED_FILE=file;$("#fileName")&&($("#fileName").textContent=file.name);$("#uploadStatus")&&($("#uploadStatus").textContent="Leyendo PDF...");try{PICKED_DATA=await readPDF(file);previewUpload(PICKED_DATA);$("#uploadStatus")&&($("#uploadStatus").textContent="PDF leído correctamente.")}catch(err){PICKED_DATA={lectura_pdf_ok:false,requiere_revision:true,lectura_pdf_error:msg(err)};previewUpload(PICKED_DATA);$("#uploadStatus")&&($("#uploadStatus").textContent=`No se pudo leer completo. Puedes subirlo igual. ${msg(err)}`)}};
const clearUpload=()=>{PICKED_FILE=null;PICKED_DATA=null;$("#fileInput")&&($("#fileInput").value="");$("#vigInicio")&&($("#vigInicio").value="");$("#vigFin")&&($("#vigFin").value="");$("#origenCarga")&&($("#origenCarga").value="");$("#fileName")&&($("#fileName").textContent="Ningún archivo seleccionado");previewUpload({})};
const uploadFile=async()=>{if(!PICKED_FILE)return toast("Selecciona un PDF.","warn");$("#uploadStatus")&&($("#uploadStatus").textContent="Subiendo...");try{const ins=await uploadClientPdf({clientId:CLIENT_ID,file:PICKED_FILE,data:PICKED_DATA||{},userId:USER.id,vigI:$("#vigInicio")?.value||null,vigF:$("#vigFin")?.value||null,origenCarga:$("#origenCarga")?.value.trim()||"cliente.html",clientName:CLIENT?.nombre||""});DOCS.unshift(ins);clearUpload();$("#uploadStatus")&&($("#uploadStatus").textContent="PDF guardado.");await loadBitacora();renderAll();toast("PDF guardado","ok");}catch(err){$("#uploadStatus")&&($("#uploadStatus").textContent=msg(err));toast(msg(err),"bad");}};

const renderTicketFilesWrap=()=>{renderTicketFiles(TICKET_FILES);$$("[data-del-ticket-file]").forEach(b=>b.onclick=()=>{TICKET_FILES.splice(+b.dataset.delTicketFile,1);renderTicketFilesWrap()})};
const openTicketDrawer=(docId=null)=>{$("#tCliente")&&($("#tCliente").value=CLIENT?.nombre||"");$("#tTitulo")&&($("#tTitulo").value="");$("#tDesc")&&($("#tDesc").value="");$("#tTipo")&&($("#tTipo").value=docId?"renovacion":"soporte");$("#tPrioridad")&&($("#tPrioridad").value="media");$("#ticketStatus")&&($("#ticketStatus").textContent="Listo.");$("#saveTicketBtn")&&($("#saveTicketBtn").dataset.docId=docId||"");TICKET_FILES=[];renderTicketFilesWrap();openDrawer("#ticketDrawer")};
const uploadTicketAttachments=async ticketId=>{if(!TICKET_FILES.length)return;for(const file of TICKET_FILES){const clean=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_").replace(/[^a-zA-Z0-9._()-]/g,""),path=`tickets/${CLIENT_ID}/${ticketId}/${Date.now()}_${clean}`,up=await s.storage.from("certificados").upload(path,file,{upsert:false,contentType:file.type||"application/octet-stream"});if(up.error)continue;await s.from("ticket_archivos").insert({ticket_id:ticketId,nombre_archivo:file.name,url_archivo:path,mime_type:file.type||null,subido_por:USER.id}).catch(()=>{})}};
const saveTicket=async()=>{const titulo=$("#tTitulo")?.value.trim()||"";if(!titulo)return $("#ticketStatus")&&($("#ticketStatus").textContent="El título es obligatorio.");$("#ticketStatus")&&($("#ticketStatus").textContent="Guardando...");try{const data=await saveTicketCore({clientId:CLIENT_ID,docId:$("#saveTicketBtn")?.dataset.docId||null,titulo,descripcion:$("#tDesc")?.value.trim()||"",tipo:$("#tTipo")?.value||"soporte",prioridad:$("#tPrioridad")?.value||"media",userId:USER.id,files:TICKET_FILES});TICKETS.unshift(data);TICKET_FILES=[];renderTicketFilesWrap();$("#ticketStatus")&&($("#ticketStatus").textContent="Ticket creado.");closeDrawer("#ticketDrawer");await Promise.all([loadTickets(),loadBitacora()]);renderAll();toast("Ticket creado","ok");}catch(err){$("#ticketStatus")&&($("#ticketStatus").textContent=msg(err));}};

const saveCRM=async()=>{const payload={nombre:$("#cNombreEdit")?.value.trim()||"",rol_responsable:$("#cResponsable")?.value.trim()||"",correo:$("#cCorreo")?.value.trim()||"",telefono:$("#cTelefono")?.value.trim()||"",estatus:$("#cEstadoEdit")?.value||"activo",favorito:!!$("#cFavorito")?.checked,comentarios:$("#cComentarios")?.value||"",ultima_interaccion:new Date().toISOString()};try{await saveCRMCore(CLIENT_ID,payload);Object.assign(CLIENT,payload);await loadBitacora();renderAll();toast("CRM guardado","ok");}catch(err){toast(msg(err),"bad");}};
const bindTabs=()=>$$(".tab").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
const bindView=()=>$$("[data-view]").forEach(b=>b.onclick=()=>{setView(b.dataset.view||"cards");applyPrefsUI()});
const bindPrefs=()=>{$$("[data-pref-density]").forEach(b=>b.onclick=()=>{PREFS.density=b.dataset.prefDensity||b.dataset.prefdensity||"normal";savePrefs()});$("#prefMaskSeries")&&($("#prefMaskSeries").onchange=e=>{PREFS.maskSeries=e.target.checked;savePrefs();renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer})});$("#prefAutoUpload")&&($("#prefAutoUpload").onchange=e=>{PREFS.autoUpload=e.target.checked;savePrefs()})};
const bindUpload=()=>{$("#toggleUploadBtn")&&($("#toggleUploadBtn").onclick=()=>$("#uploadCard")?.classList.toggle("hidden"));$("#closeUploadBtn")&&($("#closeUploadBtn").onclick=()=>$("#uploadCard")?.classList.add("hidden"));$("#clearUploadBtn")&&($("#clearUploadBtn").onclick=clearUpload);$("#uploadBtn")&&($("#uploadBtn").onclick=uploadFile);$("#dropZone")&&($("#dropZone").onclick=()=>$("#fileInput")?.click());$("#fileInput")&&($("#fileInput").onchange=e=>onPickFile(e.target.files?.[0]));const dz=$("#dropZone");if(dz){dz.ondragover=e=>{e.preventDefault();dz.classList.add("drag")};dz.ondragleave=()=>dz.classList.remove("drag");dz.ondrop=e=>{e.preventDefault();dz.classList.remove("drag");onPickFile(e.dataTransfer.files?.[0])}}};
const bindDrawers=()=>{$("#prefsBtn")&&($("#prefsBtn").onclick=()=>openDrawer("#prefsDrawer"));$("#closePrefsBtn")&&($("#closePrefsBtn").onclick=()=>closeDrawer("#prefsDrawer"));$("#openRenewBtn")&&($("#openRenewBtn").onclick=()=>openDrawer("#renewDrawer"));$("#openRenewBtn2")&&($("#openRenewBtn2").onclick=()=>openDrawer("#renewDrawer"));$("#closeRenewBtn")&&($("#closeRenewBtn").onclick=()=>closeDrawer("#renewDrawer"));$("#openNewTicketBtn")&&($("#openNewTicketBtn").onclick=()=>openTicketDrawer());$("#closeTicketBtn")&&($("#closeTicketBtn").onclick=()=>closeDrawer("#ticketDrawer"))};
const bindAccess=()=>{$("#saveAccessBtn")&&($("#saveAccessBtn").onclick=saveAccess);$("#copyAccVps")&&($("#copyAccVps").onclick=()=>copyTxt($("#accVps")?.value||"","VPS copiado"));$("#copyAccUser")&&($("#copyAccUser").onclick=()=>copyTxt($("#accUser")?.value||"","Usuario copiado"));$("#copyAccPass")&&($("#copyAccPass").onclick=()=>copyTxt($("#accPass")?.value||"","Password copiado"));$("#copyAccAnydesk")&&($("#copyAccAnydesk").onclick=()=>copyTxt($("#accAnydesk")?.value||"","AnyDesk copiado"))};
const bindActions=()=>{$("#logoutBtn")&&($("#logoutBtn").onclick=()=>logout("index.html"));$("#refreshBtn")&&($("#refreshBtn").onclick=async()=>{await bootData();renderAll()});$("#copyNameBtn")&&($("#copyNameBtn").onclick=()=>copyTxt(CLIENT?.nombre||"","Nombre copiado"));$("#copyIdBtn")&&($("#copyIdBtn").onclick=()=>copyTxt(CLIENT_ID,"ID copiado"));$("#openLatestBtn")&&($("#openLatestBtn").onclick=()=>docsLive()[0]?openDoc(docsLive()[0].id):toast("No hay PDFs","warn"));$("#saveTicketBtn")&&($("#saveTicketBtn").onclick=saveTicket);$("#saveCRMBtn")&&($("#saveCRMBtn").onclick=saveCRM);$("#searchInput")&&($("#searchInput").oninput=()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}));$("#statusFilter")&&($("#statusFilter").onchange=()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}));$("#reviewFilter")&&($("#reviewFilter").onchange=()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}));$("#ticketFiles")&&($("#ticketFiles").onchange=e=>{TICKET_FILES=[...TICKET_FILES,...[...(e.target.files||[])]];e.target.value="";renderTicketFilesWrap()});$("#mbtnTickets")&&($("#mbtnTickets").onclick=()=>location.href=`tickets.html?cliente_id=${CLIENT_ID}`);$("#mbtnUpload")&&($("#mbtnUpload").onclick=()=>$("#uploadCard")?.classList.toggle("hidden"));$("#mbtnNewTicket")&&($("#mbtnNewTicket").onclick=()=>openTicketDrawer());$("#mbtnRenew")&&($("#mbtnRenew").onclick=()=>openDrawer("#renewDrawer"));$("#mbtnPrefs")&&($("#mbtnPrefs").onclick=()=>openDrawer("#prefsDrawer"))};
const bind=()=>{bindTabs();bindView();bindPrefs();bindUpload();bindDrawers();bindAccess();bindActions()};

const init=async()=>{if(!CLIENT_ID){location.href="dashboard.html";return}loadPrefs();const auth=await guardSession("index.html");if(!auth)return;USER=auth.user;PROFILE=await getProfile().catch(()=>null);applyRoleUI();bind();await bootData();renderAll();if(PREFS.autoUpload)$("#uploadCard")?.classList.remove("hidden")};

init().catch(err=>{console.error(err);toast(`Cliente error: ${msg(err)}`,"bad")});
