import{supabase as s,guardSession,logout,openPdfSigned,fmt,msg,getProfile,logAction}from"./supabase.js";
import{$,$$,qp,toast,show,hide,copyTxt,debounce,setAppRole,setRailOpenCount,pushRecentClient,ensureAppShell,setGlobalSearchData,setBreadcrumb,esc}from"./global.js";
import{PREFS,normTxt,wa,readPDF,uploadClientPdf,saveTicket as saveTicketCore,saveCRM as saveCRMCore}from"./cliente.core.js";
import{ensureClientUISkeleton,renderHeader,renderStats,renderSystems,renderDocs,renderTicketsMini,renderTimeline,renderBitacora,renderRenewals,renderChecklist,renderCRM,previewUpload,renderTicketFiles,renderAccess,renderContacts}from"./cliente.ui.js";
 
const CLIENT_ID=qp("id")||localStorage.getItem("expiriti_last_client")||"",PREF_KEY="expiriti_cliente_prefs_v2",ACCESS_KEY=id=>`expiriti_access_${id}`;
let USER=null,PROFILE=null,CLIENT=null,DOCS=[],TICKETS=[],BIT=[],CONTACTS=[],CURRENT_SYS="",CURRENT_VIEW="cards",PICKED_FILE=null,PICKED_DATA=null,TICKET_FILES=[];
let CLIENT_SYSTEMS=[];
const clSystemIconHtml=name=>{const fake={sistema:name||""};return typeof systemLogoHtml==="function"?systemLogoHtml(fake):`<span>${name||"Sistema"}</span>`};
const loadClientSystems=async clienteId=>{if(!clienteId)return[];const {data,error}=await s.from("cliente_sistemas").select("*").eq("cliente_id",clienteId).eq("activo",true).order("sistema",{ascending:true});if(error)return[];return Array.isArray(data)?data:[]};
const renderClientSystems=()=>{const box=$("#clSystemsList");if(!box)return;box.innerHTML=CLIENT_SYSTEMS.length?CLIENT_SYSTEMS.map(x=>`<div class="cl-system-item"><div class="cl-system-head"><div class="cl-system-title">${clSystemIconHtml(x.sistema)}<span>${esc(x.sistema||"Sistema")}</span></div><div class="cl-system-actions"><button class="mini btn-ghost" type="button" data-cl-sys-edit="${x.id}">Editar</button></div></div><div class="cl-system-meta"><span class="tag">${esc(x.tipo_solicitud_default||"Sin tipo default")}</span>${x.version_sistema?`<span class="tag">Versión ${esc(x.version_sistema)}</span>`:""}${x.version_windows?`<span class="tag">${esc(x.version_windows)}</span>`:""}${x.servidor_o_equipo?`<span class="tag">${esc(x.servidor_o_equipo)}</span>`:""}</div>${x.observaciones?`<div class="cl-system-notes">${esc(x.observaciones)}</div>`:""}</div>`).join(""):`<div class="empty-state">Sin sistemas registrados para este cliente.</div>`};
const openClientSystemPanel=rec=>{$("#clSysId")&&($("#clSysId").value=rec?.id||"");$("#clSysName")&&($("#clSysName").value=rec?.sistema||"");$("#clSysTypeDefault")&&($("#clSysTypeDefault").value=rec?.tipo_solicitud_default||"");$("#clSysVersion")&&($("#clSysVersion").value=rec?.version_sistema||"");$("#clSysWindows")&&($("#clSysWindows").value=rec?.version_windows||"");$("#clSysHost")&&($("#clSysHost").value=rec?.servidor_o_equipo||"");$("#clSysOrigin")&&($("#clSysOrigin").value=rec?.origen||"cliente");$("#clSysNotes")&&($("#clSysNotes").value=rec?.observaciones||"");$("#clSystemOverlay")&&($("#clSystemOverlay").hidden=false,document.body.classList.add("modal-open"))};
const closeClientSystemPanel=()=>{$("#clSystemOverlay")&&($("#clSystemOverlay").hidden=true,document.body.classList.remove("modal-open"))};
const saveClientSystem=async clienteId=>{if(!clienteId)return toast("Falta cliente.","warn");const id=$("#clSysId")?.value||"",payload={cliente_id:clienteId,sistema:($("#clSysName")?.value||"").trim(),tipo_solicitud_default:($("#clSysTypeDefault")?.value||"").trim()||null,version_sistema:($("#clSysVersion")?.value||"").trim()||null,version_windows:($("#clSysWindows")?.value||"").trim()||null,servidor_o_equipo:($("#clSysHost")?.value||"").trim()||null,origen:($("#clSysOrigin")?.value||"").trim()||"cliente",observaciones:($("#clSysNotes")?.value||"").trim()||null,ultima_revision_en:new Date().toISOString(),actualizado_por:(await s.auth.getUser()).data.user?.id||null};if(!payload.sistema)return toast("Falta el nombre del sistema.","warn");const q=id?s.from("cliente_sistemas").update(payload).eq("id",id):s.from("cliente_sistemas").insert(payload);const {error}=await q;if(error)return toast(msg(error),"bad");closeClientSystemPanel();CLIENT_SYSTEMS=await loadClientSystems(clienteId);renderClientSystems();toast("Sistema guardado","ok")};
const esc=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const detectClientSystemKey=t=>{const x=normTxt(`${t?.sistema||""}`);if(x.includes("contabilidad")||x.includes("contabiliza")||x.includes("contab"))return"CONTABILIDAD";if(x.includes("bancos"))return"BANCOS";if(x.includes("nominas")||x.includes("nóminas")||x.includes("nomina"))return"NOMINAS";if(x.includes("xml en linea")||x.includes("xml"))return"XML_EN_LINEA";if(x.includes("comercial premium"))return"COMERCIAL_PREMIUM";if(x.includes("comercial pro"))return"COMERCIAL_PRO";if(x.includes("comercial start"))return"COMERCIAL_START";if(x.includes("factura"))return"FACTURA_ELECTRONICA";if(x.includes("evalua"))return"EVALUA";if(x.includes("analiza"))return"ANALIZA";if(x.includes("vende"))return"VENDE";if(x.includes("optimiza"))return"OPTIMIZA";if(x.includes("anticipa"))return"ANTICIPA";if(x.includes("personia"))return"PERSONIA";return""};
const CLIENT_SYS_LOGO={CONTABILIDAD:"../IMG/contabilidad (1).webp",BANCOS:"../IMG/bancos (1).webp",NOMINAS:"../IMG/nominas (1).webp",XML_EN_LINEA:"../IMG/factura (1).webp",COMERCIAL_START:"../IMG/comercialstart (1).webp",COMERCIAL_PRO:"../IMG/comercialpro (1).webp",COMERCIAL_PREMIUM:"../IMG/comercialpremium (1).webp",FACTURA_ELECTRONICA:"../IMG/factura (1).webp",EVALUA:"../IMG/evalua (1).webp",ANALIZA:"../IMG/analiza (1).webp",VENDE:"../IMG/vende (3).webp",OPTIMIZA:"../IMG/optimiza (1).webp",ANTICIPA:"../IMG/anticipa (1).webp",PERSONIA:"../IMG/personia (2).webp"};
const systemLogoHtml=t=>{const k=detectClientSystemKey(t),src=CLIENT_SYS_LOGO[k]||"",label=t?.sistema||k||"Sistema";return src?`<span class="tk-system-chip"><img src="${src}" alt="${esc(label)}" class="tk-system-logo"><span>${esc(label)}</span></span>`:`<span>${esc(label)}</span>`};

const docsLive=()=>DOCS.filter(x=>!x.eliminado),byId=(arr,id)=>arr.find(x=>String(x.id)===String(id)),canAccess=()=>["soporte","admin"].includes((PROFILE?.rol||"soporte").toLowerCase());
const setCurrentSys=v=>CURRENT_SYS=v||"",setView=v=>CURRENT_VIEW=v||"cards";
const loadPrefs=()=>{try{Object.assign(PREFS,JSON.parse(localStorage.getItem(PREF_KEY)||"{}"))}catch{}applyPrefsUI()},savePrefs=()=>{localStorage.setItem(PREF_KEY,JSON.stringify(PREFS));applyPrefsUI()};
const applyPrefsUI=()=>{document.body.classList.toggle("compact",PREFS.density==="compact"||CURRENT_VIEW==="compact");$("#prefMaskSeries")&&($("#prefMaskSeries").checked=!!PREFS.maskSeries);$("#prefAutoUpload")&&($("#prefAutoUpload").checked=!!PREFS.autoUpload);$$("[data-view]").forEach(b=>b.classList.toggle("active",(b.dataset.view||"")===(CURRENT_VIEW||"cards")))};
const setTab=name=>{$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));$$(".tab-panel").forEach(p=>{const on=p.id===`panel-${name}`;p.classList.toggle("active",on);p.classList.toggle("hidden",!on)})};
const openDrawer=id=>show(id.startsWith("#")?id:`#${id}`),closeDrawer=id=>hide(id.startsWith("#")?id:`#${id}`);
const applyRoleUI=()=>{document.body.dataset.role=(PROFILE?.rol||"soporte").toLowerCase()};
const contactBestChannel=c=>{const pref=norm(c?.canal_preferido||"");if(pref==="whatsapp")return"WhatsApp";if(pref==="telefono")return"Llamada";if(pref==="correo")return"Correo";if(c?.telefono)return"WhatsApp o llamada";if(c?.correo)return"Correo";return"—"};
const contactCard=c=>`<div class="item"><div class="item-top"><div><div class="item-title">${esc(c?.nombre||"Sin nombre")}${c?.es_principal?` <span class="tag ok">Principal</span>`:""}${c?.favorito?` <span class="tag info">Frecuente</span>`:""}</div><div class="item-meta">${esc(c?.puesto||"Sin puesto")} · ${esc(contactBestChannel(c))}</div></div><div class="toolbar row-actions"><button class="mini btn-ghost" type="button" data-copy="${esc(c?.correo||"")}">Copiar correo</button><button class="mini btn-ghost" type="button" data-copy="${esc(c?.telefono||"")}">Copiar teléfono</button><button class="mini btn-ghost" type="button" data-new-ticket-contact="${esc(c?.id||"")}">Nuevo ticket</button></div></div><div class="chips">${c?.correo?`<span class="tag">${esc(c.correo)}</span>`:""}${c?.telefono?`<span class="tag">${esc(c.telefono)}</span>`:""}${c?.horario_laboral?`<span class="tag info">${esc(c.horario_laboral)}</span>`:""}</div>${c?.notas?`<div class="muted-sm">${esc(c.notas)}</div>`:""}</div>`;
function renderContactosTab(contactos=[]){const box=$("#panel-contactos");if(!box)return;$("#tabContactsCount")&&($("#tabContactsCount").textContent=contactos.length);box.innerHTML=contactos.length?`<div class="stack-sm">${contactos.map(contactCard).join("")}</div>`:`<div class="empty-state">Aún no hay contactos cargados para este cliente.</div>`}
const crmSummary=(cliente,contactos=[],tickets=[])=>{const primary=contactos.find(x=>x?.es_principal)||contactos[0]||null;const open=tickets.filter(x=>!["cerrado","resuelto"].includes(norm(x?.estado||x?.status)));const urgent=open.filter(x=>norm(x?.prioridad)==="urgente");return{contacto:primary?.nombre||"Sin contacto principal",canal:contactBestChannel(primary||{}),horario:primary?.horario_laboral||cliente?.horario_laboral||"Sin horario claro",abiertos:open.length,urgentes:urgent.length,next:urgent.length?"Atender tickets urgentes":open.length?"Dar seguimiento a tickets abiertos":primary?"Mantener contexto actualizado":"Definir contacto principal"}};

const loadClient=async()=>{const{data,error}=await s.from("clientes").select("*").eq("id",CLIENT_ID).single();if(error||!data){toast("Cliente no encontrado","bad");location.href="dashboard.html";return}CLIENT=data};
const loadDocs=async()=>{const{data,error}=await s.from("documentos").select("*").eq("cliente_id",CLIENT_ID).eq("eliminado",false).order("fecha_subida",{ascending:false});if(error)throw error;DOCS=data||[]};
const loadTickets=async()=>{const{data,error}=await s.from("tickets").select("*").eq("cliente_id",CLIENT_ID).order("fecha_actualizacion",{ascending:false});if(error)throw error;TICKETS=data||[]};
const loadContacts=async()=>{const{data,error}=await s.from("clientes_contactos").select("*").eq("cliente_id",CLIENT_ID).order("es_principal",{ascending:false}).order("nombre",{ascending:true});CONTACTS=error?[]:(data||[])};
const loadBitacora=async()=>{const{data,error}=await s.from("bitacora").select("*").eq("cliente_id",CLIENT_ID).order("fecha",{ascending:false}).limit(40);BIT=error?[]:(data||[])};
const loadPrimaryData=async()=>{const rs=await Promise.allSettled([loadDocs(),loadTickets(),loadContacts()]);DOCS=rs[0]?.status==="fulfilled"?DOCS:[];TICKETS=rs[1]?.status==="fulfilled"?TICKETS:[];CONTACTS=rs[2]?.status==="fulfilled"?CONTACTS:[]};
const loadSecondaryData=async()=>{const rs=await Promise.allSettled([loadBitacora()]);BIT=rs[0]?.status==="fulfilled"?BIT:[]};
const bootData=async()=>{await loadPrimaryData();CLIENT_SYSTEMS=await loadClientSystems(CLIENT_ID);await loadSecondaryData()};

const loadAccess=()=>{if(!canAccess())return renderAccess({acc:{}});let d={};try{d=JSON.parse(localStorage.getItem(ACCESS_KEY(CLIENT_ID))||"{}")}catch{}renderAccess({acc:d})};
const saveAccess=async()=>{if(!canAccess())return $("#accessStatus")&&($("#accessStatus").textContent="Sin permisos.");const payload={vps:$("#accVps")?.value.trim()||"",rdpPort:$("#accRdpPort")?.value.trim()||"",user:$("#accUser")?.value.trim()||"",pass:$("#accPass")?.value.trim()||"",anydesk:$("#accAnydesk")?.value.trim()||"",extra:$("#accExtra")?.value.trim()||"",notes:$("#accNotes")?.value.trim()||"",updatedAt:new Date().toISOString(),updatedBy:USER?.id||null};localStorage.setItem(ACCESS_KEY(CLIENT_ID),JSON.stringify(payload));$("#accessStatus")&&($("#accessStatus").textContent="Accesos guardados localmente.");await logAction({accion:"actualizo_accesos_local",cliente_id:CLIENT_ID,detalle:{riesgo:"localStorage",vps:!!payload.vps,rdp:!!payload.rdpPort,user:!!payload.user,anydesk:!!payload.anydesk}}).catch(()=>{});toast("Accesos guardados localmente","ok")};

const renderAll=()=>{ensureClientUISkeleton({canAccess:canAccess()});renderHeader({CLIENT,CLIENT_ID,PREFS,DOCS,TICKETS,CONTACTS});renderStats({DOCS,TICKETS});renderSystems({DOCS,CURRENT_SYS,setCurrentSys,renderDocs:()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer})});renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer});renderContacts({CLIENT,CONTACTS});renderTicketsMini({TICKETS});renderTimeline({DOCS,TICKETS,BIT});renderBitacora({BIT});renderRenewals({DOCS,CLIENT,openDoc,openTicketDrawer});renderChecklist({CLIENT,DOCS,TICKETS,CONTACTS});renderCRM({CLIENT});renderClientSystems();loadAccess();applyPrefsUI();setTab($(".tab.active")?.dataset.tab||"docs");bindDocFilters()};

const openDoc=async id=>{const d=byId(DOCS,id);if(!d)return;await logAction({accion:"abrio_pdf",documento_id:d.id,cliente_id:CLIENT_ID,detalle:{nombre_archivo:d.nombre_archivo||"",storage_path:d.storage_path||d.url_pdf||""}}).catch(()=>{});await openPdfSigned(d.storage_path||d.url_pdf,8).catch(err=>toast(msg(err),"bad"))};
const onPickFile=async file=>{if(!file||!/\.pdf$/i.test(file.name))return toast("Solo PDFs","warn");PICKED_FILE=file;$("#fileName")&&($("#fileName").textContent=file.name);$("#uploadStatus")&&($("#uploadStatus").textContent="Leyendo PDF...");try{PICKED_DATA=await readPDF(file);previewUpload(PICKED_DATA);$("#uploadStatus")&&($("#uploadStatus").textContent="PDF leído correctamente.")}catch(err){PICKED_DATA={lectura_pdf_ok:false,requiere_revision:true,lectura_pdf_error:msg(err)};previewUpload(PICKED_DATA);$("#uploadStatus")&&($("#uploadStatus").textContent=`No se pudo leer completo. Puedes subirlo igual. ${msg(err)}`)}};
const clearUpload=()=>{PICKED_FILE=null;PICKED_DATA=null;$("#fileInput")&&($("#fileInput").value="");$("#vigInicio")&&($("#vigInicio").value="");$("#vigFin")&&($("#vigFin").value="");$("#origenCarga")&&($("#origenCarga").value="");$("#fileName")&&($("#fileName").textContent="Ningún archivo seleccionado");previewUpload({})};
const uploadFile=async()=>{if(!PICKED_FILE)return toast("Selecciona un PDF.","warn");$("#uploadStatus")&&($("#uploadStatus").textContent="Subiendo...");try{const ins=await uploadClientPdf({clientId:CLIENT_ID,file:PICKED_FILE,data:PICKED_DATA||{},userId:USER.id,vigI:$("#vigInicio")?.value||null,vigF:$("#vigFin")?.value||null,origenCarga:$("#origenCarga")?.value.trim()||"cliente.html",clientName:CLIENT?.nombre||""});DOCS.unshift(ins);clearUpload();$("#uploadStatus")&&($("#uploadStatus").textContent="PDF guardado.");await loadBitacora();renderAll();renderTacticalRefresh();toast("PDF guardado","ok");}catch(err){$("#uploadStatus")&&($("#uploadStatus").textContent=msg(err));toast(msg(err),"bad");}};

const renderTicketFilesWrap=()=>{renderTicketFiles(TICKET_FILES);$$("[data-del-ticket-file]").forEach(b=>b.onclick=()=>{TICKET_FILES.splice(+b.dataset.delTicketFile,1);renderTicketFilesWrap()})};
const openTicketDrawer=(docId=null)=>{$("#tCliente")&&($("#tCliente").value=CLIENT?.nombre||"");$("#tTitulo")&&($("#tTitulo").value="");$("#tDesc")&&($("#tDesc").value="");$("#tTipo")&&($("#tTipo").value=docId?"renovacion":"soporte");$("#tPrioridad")&&($("#tPrioridad").value="media");$("#ticketStatus")&&($("#ticketStatus").textContent="Listo.");$("#saveTicketBtn")&&($("#saveTicketBtn").dataset.docId=docId||"");TICKET_FILES=[];renderTicketFilesWrap();openDrawer("#ticketDrawer")};

const saveTicket=async()=>{const titulo=$("#tTitulo")?.value.trim()||"";if(!titulo)return $("#ticketStatus")&&($("#ticketStatus").textContent="El título es obligatorio.");$("#ticketStatus")&&($("#ticketStatus").textContent="Guardando...");try{const data=await saveTicketCore({clientId:CLIENT_ID,docId:$("#saveTicketBtn")?.dataset.docId||null,titulo,descripcion:$("#tDesc")?.value.trim()||"",tipo:$("#tTipo")?.value||"soporte",prioridad:$("#tPrioridad")?.value||"media",userId:USER.id,files:TICKET_FILES});TICKETS.unshift(data);TICKET_FILES=[];renderTicketFilesWrap();$("#ticketStatus")&&($("#ticketStatus").textContent="Ticket creado.");closeDrawer("#ticketDrawer");await Promise.all([loadTickets(),loadBitacora()]);renderAll();renderTacticalRefresh();toast("Ticket creado","ok");}catch(err){$("#ticketStatus")&&($("#ticketStatus").textContent=msg(err));}};

const saveCRM=async()=>{const payload={nombre:$("#cNombreEdit")?.value.trim()||"",rol_responsable:$("#cResponsable")?.value.trim()||"",correo:$("#cCorreo")?.value.trim()||"",telefono:$("#cTelefono")?.value.trim()||"",estatus:$("#cEstadoEdit")?.value||"activo",favorito:!!$("#cFavorito")?.checked,comentarios:$("#cComentarios")?.value||"",ultima_interaccion:new Date().toISOString()};try{await saveCRMCore(CLIENT_ID,payload);Object.assign(CLIENT,payload);await loadBitacora();renderAll();toast("CRM guardado","ok");}catch(err){toast(msg(err),"bad");}};
const bindTabs=()=>$$(".tab").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
const bindView=()=>$$("[data-view]").forEach(b=>b.onclick=()=>{setView(b.dataset.view||"cards");applyPrefsUI();renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer})});
const bindPrefs=()=>{$$("[data-pref-density]").forEach(b=>b.onclick=()=>{PREFS.density=b.dataset.prefDensity||b.dataset.prefdensity||"normal";savePrefs()});$("#prefMaskSeries")&&($("#prefMaskSeries").onchange=e=>{PREFS.maskSeries=e.target.checked;savePrefs();renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer})});$("#prefAutoUpload")&&($("#prefAutoUpload").onchange=e=>{PREFS.autoUpload=e.target.checked;savePrefs()})};
const bindUpload=()=>{$("#toggleUploadBtn")&&($("#toggleUploadBtn").onclick=()=>$("#uploadCard")?.classList.toggle("hidden"));$("#closeUploadBtn")&&($("#closeUploadBtn").onclick=()=>$("#uploadCard")?.classList.add("hidden"));$("#clearUploadBtn")&&($("#clearUploadBtn").onclick=clearUpload);$("#uploadBtn")&&($("#uploadBtn").onclick=uploadFile);$("#dropZone")&&($("#dropZone").onclick=()=>$("#fileInput")?.click());$("#fileInput")&&($("#fileInput").onchange=e=>onPickFile(e.target.files?.[0]));const dz=$("#dropZone");if(dz){dz.ondragover=e=>{e.preventDefault();dz.classList.add("drag")};dz.ondragleave=()=>dz.classList.remove("drag");dz.ondrop=e=>{e.preventDefault();dz.classList.remove("drag");onPickFile(e.dataTransfer.files?.[0])}}};
const bindDrawers=()=>{$("#prefsBtn")&&($("#prefsBtn").onclick=()=>openDrawer("#prefsDrawer"));$("#closePrefsBtn")&&($("#closePrefsBtn").onclick=()=>closeDrawer("#prefsDrawer"));$("#openRenewBtn")&&($("#openRenewBtn").onclick=()=>openDrawer("#renewDrawer"));$("#openRenewBtn2")&&($("#openRenewBtn2").onclick=()=>openDrawer("#renewDrawer"));$("#closeRenewBtn")&&($("#closeRenewBtn").onclick=()=>closeDrawer("#renewDrawer"));$("#openNewTicketBtn")&&($("#openNewTicketBtn").onclick=()=>openTicketDrawer());$("#closeTicketBtn")&&($("#closeTicketBtn").onclick=()=>closeDrawer("#ticketDrawer"))};
const bindAccess=()=>{$("#saveAccessBtn")&&($("#saveAccessBtn").onclick=saveAccess);$("#copyAccVps")&&($("#copyAccVps").onclick=()=>copyTxt($("#accVps")?.value||"","VPS copiado"));$("#copyAccUser")&&($("#copyAccUser").onclick=()=>copyTxt($("#accUser")?.value||"","Usuario copiado"));$("#copyAccPass")&&($("#copyAccPass").onclick=()=>copyTxt($("#accPass")?.value||"","Password copiado"));$("#copyAccAnydesk")&&($("#copyAccAnydesk").onclick=()=>copyTxt($("#accAnydesk")?.value||"","AnyDesk copiado"))};
const bindActions=()=>{$("#logoutBtn")&&($("#logoutBtn").onclick=()=>logout("index.html"));$("#refreshBtn")&&($("#refreshBtn").onclick=async()=>{await loadClient();await loadPrimaryData();setBreadcrumb([{label:"Panel",href:"dashboard.html"},{label:CLIENT?.nombre||"Cliente"}]);setGlobalSearchData({clientes:[CLIENT],tickets:TICKETS});renderAll();bind();bindDocFilters();queueMicrotask(async()=>{await loadSecondaryData();renderSecondary()})});$("#copyNameBtn")&&($("#copyNameBtn").onclick=()=>copyTxt(CLIENT?.nombre||"","Nombre copiado"));$("#copyIdBtn")&&($("#copyIdBtn").onclick=()=>copyTxt(CLIENT_ID,"ID copiado"));$("#openLatestBtn")&&($("#openLatestBtn").onclick=()=>docsLive()[0]?openDoc(docsLive()[0].id):toast("No hay PDFs","warn"));$("#saveTicketBtn")&&($("#saveTicketBtn").onclick=saveTicket);$("#saveCRMBtn")&&($("#saveCRMBtn").onclick=saveCRM);$("#searchInput")&&($("#searchInput").oninput=()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}));$("#statusFilter")&&($("#statusFilter").onchange=()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}));$("#reviewFilter")&&($("#reviewFilter").onchange=()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}));$("#ticketFiles")&&($("#ticketFiles").onchange=e=>{TICKET_FILES=[...TICKET_FILES,...Array.from(e.target.files||[])];e.target.value="";renderTicketFilesWrap()});$("#mbtnTickets")&&($("#mbtnTickets").onclick=()=>location.href=`tickets.html?cliente_id=${CLIENT_ID}`);$("#mbtnUpload")&&($("#mbtnUpload").onclick=()=>$("#uploadCard")?.classList.toggle("hidden"));$("#mbtnNewTicket")&&($("#mbtnNewTicket").onclick=()=>openTicketDrawer());$("#mbtnRenew")&&($("#mbtnRenew").onclick=()=>openDrawer("#renewDrawer"));$("#mbtnPrefs")&&($("#mbtnPrefs").onclick=()=>openDrawer("#prefsDrawer"))};
const bind=()=>{bindTabs();bindView();bindPrefs();bindUpload();bindDrawers();bindAccess();bindActions();$("#clAddSystemBtn")&&($("#clAddSystemBtn").onclick=()=>openClientSystemPanel(null));$("#clSystemClose")&&($("#clSystemClose").onclick=closeClientSystemPanel);$("#clSystemCancel")&&($("#clSystemCancel").onclick=closeClientSystemPanel);$("#clSystemSave")&&($("#clSystemSave").onclick=()=>saveClientSystem(CLIENT_ID));$("#clSystemOverlay")&&$("#clSystemOverlay").addEventListener("click",e=>{if(e.target.id==="clSystemOverlay")closeClientSystemPanel()});document.addEventListener("click",e=>{const b=e.target.closest("[data-cl-sys-edit]");if(!b)return;const row=CLIENT_SYSTEMS.find(x=>String(x.id)===String(b.dataset.clSysEdit));if(row)openClientSystemPanel(row)})};


const bindDocFilters=()=>{const rer=debounce(()=>renderDocs({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer}),180);$("#searchInput")&&($("#searchInput").oninput=rer);$("#statusFilter")&&($("#statusFilter").onchange=rer);$("#reviewFilter")&&($("#reviewFilter").onchange=rer)};
const warmClientView=()=>{ensureClientUISkeleton({canAccess:canAccess()});renderHeader({CLIENT,CLIENT_ID,PREFS,DOCS:[],TICKETS:[],CONTACTS:[]});renderStats({DOCS:[],TICKETS:[]});renderContacts({CLIENT,CONTACTS:[]});renderTicketsMini({TICKETS:[]});renderTimeline({DOCS:[],TICKETS:[],BIT:[]});renderBitacora({BIT:[]});renderRenewals({DOCS:[],CLIENT,openDoc,openTicketDrawer});renderChecklist({CLIENT,DOCS:[],TICKETS:[],CONTACTS:[]});renderCRM({CLIENT})};
const renderSecondary=()=>{renderTimeline({DOCS,TICKETS,BIT});renderBitacora({BIT})};
const renderTacticalRefresh=()=>{renderHeader({CLIENT,CLIENT_ID,PREFS,DOCS,TICKETS,CONTACTS});renderStats({DOCS,TICKETS});renderChecklist({CLIENT,DOCS,TICKETS,CONTACTS})};
function renderCrmTab(cliente,contactos=[],tickets=[]){const box=$("#panel-crm");if(!box)return;const s=crmSummary(cliente,contactos,tickets);box.innerHTML=`<div class="stack-sm"><div class="box"><div class="k">Contacto principal</div><div class="v small">${esc(s.contacto)}</div></div><div class="box-grid"><div class="box"><div class="k">Canal ideal</div><div class="v small">${esc(s.canal)}</div></div><div class="box"><div class="k">Horario sugerido</div><div class="v small">${esc(s.horario)}</div></div><div class="box"><div class="k">Tickets abiertos</div><div class="v small">${s.abiertos}</div></div><div class="box"><div class="k">Urgentes</div><div class="v small">${s.urgentes}</div></div></div><div class="box"><div class="k">Siguiente acción</div><div class="v small">${esc(s.next)}</div></div></div>`}

const start=async()=>{if(!CLIENT_ID){location.href="dashboard.html";return}loadPrefs();const auth=await guardSession("index.html");if(!auth)return;USER=auth.user||(await s.auth.getUser()).data.user||null;PROFILE=await getProfile().catch(()=>null);ensureAppShell({page:"cliente",role:PROFILE?.rol||"soporte",title:"Cliente",kicker:"Expiriti · vista operativa",actionsHtml:`<a class="mini btn-ghost" href="dashboard.html">Dashboard</a><a class="mini btn-ghost" id="allTicketsTopLink" href="tickets.html">Tickets</a><button class="mini btn-ghost" id="prefsBtn" type="button">Preferencias</button><button class="mini btn-ghost" id="logoutBtn" type="button">Salir</button>`});setAppRole(PROFILE?.rol||"soporte");applyRoleUI();ensureClientUISkeleton({canAccess:canAccess()});bind();await loadClient();setBreadcrumb([{label:"Panel",href:"dashboard.html"},{label:CLIENT?.nombre||"Cliente"}]);if(CLIENT?.id&&CLIENT?.nombre)pushRecentClient({id:CLIENT.id,nombre:CLIENT.nombre});setGlobalSearchData({clientes:[CLIENT],tickets:[]});warmClientView();await loadPrimaryData();setRailOpenCount((TICKETS||[]).filter(t=>!["cerrado","resuelto","closed","done","cancelado"].includes((t.estado||t.estatus||t.status||"").toLowerCase())).length);setGlobalSearchData({clientes:[CLIENT],tickets:TICKETS});renderAll();bind();bindDocFilters();queueMicrotask(async()=>{await loadSecondaryData();renderSecondary();renderTacticalRefresh()});if(PREFS.autoUpload)$("#uploadCard")?.classList.remove("hidden")};
document.addEventListener("DOMContentLoaded",()=>start().catch(err=>{console.error(err);toast(`Cliente error: ${msg(err)}`,"bad")}));

