import{$,$$,esc}from"./global.js";
import{NICE,ICON,wa,call,mail,sem,mask,detectSistema,healthState,criticalState,profileCompletion,nextSuggestedAction,getSystems,currentRows,buildTimeline}from"./cliente.core.js";
import{fmt}from"./supabase.js";

export const renderHeader=({CLIENT,CLIENT_ID,PREFS,DOCS,TICKETS})=>{["#cNombre","#subMeta"].forEach(x=>$(x)?.classList.remove("skel"));if($("#cNombre"))$("#cNombre").textContent=CLIENT?.nombre||"Cliente";if($("#subMeta"))$("#subMeta").textContent=`Creado: ${fmt(CLIENT?.fecha_creacion)||"—"} · ID: ${CLIENT_ID}`;if($("#badgeEstado"))$("#badgeEstado").textContent=`Estado: ${CLIENT?.estatus||"activo"}`;if($("#badgeCritico"))$("#badgeCritico").classList.toggle("hidden",!criticalState({DOCS,TICKETS}));const h=healthState({DOCS,TICKETS});if($("#badgeSalud")){$("#badgeSalud").textContent=`Salud: ${h.txt}`;$("#badgeSalud").className=`badge-pill ${h.cls}`.trim()}if($("#cResponsableView"))$("#cResponsableView").textContent=CLIENT?.rol_responsable||"—";if($("#cUltima"))$("#cUltima").textContent=CLIENT?.ultima_interaccion?fmt(CLIENT.ultima_interaccion):"—";const pc=profileCompletion({CLIENT,DOCS});if($("#profileScore"))$("#profileScore").textContent=`${pc.score}%`;if($("#nextAction"))$("#nextAction").textContent=nextSuggestedAction({CLIENT,DOCS,TICKETS});if($("#waBtn"))$("#waBtn").href=wa(CLIENT?.telefono);if($("#callBtn"))$("#callBtn").href=call(CLIENT?.telefono);if($("#mailBtn"))$("#mailBtn").href=mail(CLIENT?.correo);if($("#allTicketsLink"))$("#allTicketsLink").href=`tickets.html?cliente_id=${CLIENT_ID}`;if($("#allTicketsTopLink"))$("#allTicketsTopLink").href=`tickets.html?cliente_id=${CLIENT_ID}`};

export const renderStats=({DOCS,TICKETS})=>{const a=DOCS.filter(x=>!x.eliminado),ok=a.filter(d=>sem(d.fin_vigencia).t==="Vigente").length,warn=a.filter(d=>sem(d.fin_vigencia).t==="Por vencer").length,bad=a.filter(d=>sem(d.fin_vigencia).t==="Vencido").length,open=TICKETS.filter(t=>!["cerrado","resuelto"].includes((t.estado||"").toLowerCase())),urgent=open.filter(t=>t.prioridad==="urgente").length,last=a[0];if($("#kDocs"))$("#kDocs").textContent=a.length;if($("#kOk"))$("#kOk").textContent=ok;if($("#kWarn"))$("#kWarn").textContent=warn;if($("#kBad"))$("#kBad").textContent=bad;if($("#kOpenTickets"))$("#kOpenTickets").textContent=open.length;if($("#kUrgentTickets"))$("#kUrgentTickets").textContent=urgent;if($("#tabDocsCount"))$("#tabDocsCount").textContent=a.length;if($("#lastDocLabel"))$("#lastDocLabel").textContent=last?.nombre_archivo||"—";if($("#heroChips"))$("#heroChips").innerHTML=a.length?a.slice(0,4).map(d=>{const s=sem(d.fin_vigencia);return`<span class="status ${s.c}">${ICON[d.sistema_norm||detectSistema(d.sistema||d.nombre_archivo)]||"📄"} ${s.t}</span>`}).join(""):`<span class="status neutral">Sin documentos</span>`};

export const renderSystems=({DOCS,CURRENT_SYS,setCurrentSys,renderDocs})=>{const systems=getSystems({DOCS});if(!CURRENT_SYS&&systems.length)setCurrentSys(systems[0]);if(CURRENT_SYS&&!systems.includes(CURRENT_SYS))setCurrentSys("");if($("#sysChips"))$("#sysChips").innerHTML=(systems.length?`<button class="mini ${CURRENT_SYS?"ghost":""}" data-sys="">Todos</button>`:"")+systems.map(s=>`<button class="mini ${CURRENT_SYS===s?"":"ghost"}" data-sys="${s}">${ICON[s]||"📄"} ${NICE[s]||s}</button>`).join("");$$("[data-sys]").forEach(b=>b.onclick=()=>{setCurrentSys(b.dataset.sys);renderSystems({DOCS,CURRENT_SYS:b.dataset.sys,setCurrentSys,renderDocs});renderDocs()})};

export const docBadges=d=>{const st=sem(d.fin_vigencia),arr=[`<span class="status ${st.c}">${st.t}</span>`];if(d.requiere_revision)arr.push(`<span class="chip">Revisión requerida</span>`);if(d.lectura_pdf_error||d.lectura_pdf_ok===false)arr.push(`<span class="chip">Lectura PDF pendiente</span>`);if(d.es_actual)arr.push(`<span class="chip">Actual</span>`);if(d.tipo_licencia)arr.push(`<span class="chip">${esc(d.tipo_licencia)}</span>`);return arr.join("")};

export const renderDocs=({DOCS,CURRENT_SYS,PREFS,openDoc,openTicketDrawer})=>{const rows=currentRows({DOCS,CURRENT_SYS,q:$("#searchInput")?.value||"",sf:$("#statusFilter")?.value||"",rf:$("#reviewFilter")?.value||""});if($("#docsList"))$("#docsList").innerHTML=rows.length?rows.map(d=>{const sis=d.sistema_norm||detectSistema(`${d.sistema||""} ${d.nombre_archivo||""} ${d.pdf_text||""}`),serieReal=d.numero_serie||"",verReal=d.verificador||"",serie=PREFS.maskSeries?mask(serieReal):serieReal||"—",ver=PREFS.maskSeries?mask(verReal):verReal||"—",vig=d.fin_vigencia?fmt(d.fin_vigencia):"Sin vigencia",empresa=esc(d.empresa_certificado||"—"),version=d.version_comercial?` · ${esc(d.version_comercial)}`:"",tipo=d.tipo_documento?` · ${esc(d.tipo_documento)}`:"",usuarios=d.usuarios?`${esc(d.usuarios)} usuario(s)`:"—",empresas=esc(d.empresas_info||"—"),cls=`doc-card ${d.es_actual?"is-current":""} ${d.requiere_revision?"is-review":""}`.trim();return`<article class="${cls}"><div class="doc-main"><div class="doc-left"><div class="doc-top"><div class="doc-title">${ICON[sis]||"📄"} ${esc(NICE[sis]||d.sistema||"PDF")}</div>${d.es_actual?`<span class="tag ok">Actual</span>`:""}</div><div class="doc-sub">${esc(d.nombre_archivo||"PDF")}</div><div class="doc-meta">Vence: ${vig} · ${usuarios} · ${empresas}</div><div class="doc-meta">Serie: <code>${esc(serie)}</code> · Verificador: <code>${esc(ver)}</code></div><div class="doc-meta">${empresa}${version}${tipo}</div></div><div class="doc-right"><div class="doc-badges">${docBadges(d)}</div><div class="doc-actions">${serieReal?`<button class="mini btn-ghost" data-copy-serie="${esc(serieReal)}">Serie</button>`:""}${verReal?`<button class="mini btn-ghost" data-copy-ver="${esc(verReal)}">Verif</button>`:""}<button class="mini btn-ghost" data-open-doc="${d.id}">Abrir</button><button class="mini btn-brand" data-ticket-doc="${d.id}">Ticket</button></div></div></div></article>`}).join(""):`<div class="empty">No hay certificados para este filtro.</div>`;$$("[data-copy-serie]").forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.copySerie||b.dataset.copyserie||""));$$("[data-copy-ver]").forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.copyVer||b.dataset.copyver||""));$$("[data-open-doc]").forEach(b=>b.onclick=()=>openDoc(b.dataset.openDoc||b.dataset.opendoc));$$("[data-ticket-doc]").forEach(b=>b.onclick=()=>openTicketDrawer(b.dataset.ticketDoc||b.dataset.ticketdoc))};
export const renderTicketsMini=({TICKETS})=>{if($("#ticketsList"))$("#ticketsList").innerHTML=TICKETS.slice(0,6).map(t=>`<div class="item"><div class="item-title">${esc(t.titulo||"Ticket")}</div><div class="item-meta">${esc(t.tipo||"soporte")} · ${esc(t.prioridad||"media")} · ${fmt(t.fecha_actualizacion||t.fecha_creacion)||"—"}</div><div class="toolbar mt8"><span class="chip">${esc(t.estado||"abierto")}</span></div></div>`).join("")||`<div class="empty">Sin tickets</div>`};

export const renderTimeline=({DOCS,TICKETS,BIT})=>{const items=buildTimeline({DOCS,TICKETS,BIT});if($("#tabTimelineCount"))$("#tabTimelineCount").textContent=items.length;if($("#timelineList"))$("#timelineList").innerHTML=items.length?items.map(x=>`<div class="item"><div class="item-title">${esc(x.title)}</div><div class="item-meta">${fmt(x.ts)||"—"} · ${esc(x.sub||"")}</div></div>`).join(""):`<div class="empty">Sin actividad todavía</div>`};

export const renderBitacora=({BIT})=>{if($("#bitacoraList"))$("#bitacoraList").innerHTML=BIT.length?BIT.map(b=>`<div class="item"><div class="item-title">${esc(b.accion||"Acción")}</div><div class="item-meta">${fmt(b.fecha)||"—"}${b.detalle?` · ${esc(JSON.stringify(b.detalle))}`:""}</div></div>`).join(""):`<div class="empty">Sin registros recientes</div>`};

export const renderRenewals=({DOCS,CLIENT,openDoc,openTicketDrawer})=>{const rows=DOCS.filter(x=>!x.eliminado).filter(d=>["Por vencer","Vencido"].includes(sem(d.fin_vigencia).t));if($("#renewList"))$("#renewList").innerHTML=rows.length?rows.map(d=>`<div class="item"><div class="item-title">${esc(d.nombre_archivo||"Documento")}</div><div class="item-meta">${esc(NICE[d.sistema_norm]||d.sistema||"Sin sistema")} · ${d.fin_vigencia?fmt(d.fin_vigencia):"Sin vigencia"}</div><div class="toolbar mt8"><button class="mini ghost" data-open-doc="${d.id}">Abrir</button><button class="mini ghost" data-ticket-doc="${d.id}">Crear ticket</button>${CLIENT?.telefono?`<a class="mini ghost" target="_blank" href="${wa(CLIENT.telefono)}?text=${encodeURIComponent(`Hola, tu ${NICE[d.sistema_norm]||d.sistema||"sistema"} vence el ${fmt(d.fin_vigencia)}. ¿Te apoyo con la renovación?`)}">WhatsApp</a>`:""}</div></div>`).join(""):`<div class="empty">Sin alertas de renovación</div>`;if($("#renewMiniList"))$("#renewMiniList").innerHTML=rows.slice(0,3).map(d=>`<div class="item"><div class="item-title">${esc(d.nombre_archivo||"Documento")}</div><div class="item-meta">${d.fin_vigencia?fmt(d.fin_vigencia):"Sin vigencia"}</div></div>`).join("")||`<div class="empty">Sin alertas</div>`;$$("[data-open-doc]").forEach(b=>b.onclick=()=>openDoc(b.dataset.openDoc||b.dataset.opendoc));$$("[data-ticket-doc]").forEach(b=>b.onclick=()=>openTicketDrawer(b.dataset.ticketDoc||b.dataset.ticketdoc))};

export const renderChecklist=({CLIENT,DOCS,TICKETS})=>{const pc=profileCompletion({CLIENT,DOCS}),rows=[];rows.push({t:"Completitud del perfil",s:`${pc.score}%${pc.missing.length?` · falta ${pc.missing.join(", ")}`:" · completo"}`});rows.push({t:"Próxima acción sugerida",s:nextSuggestedAction({CLIENT,DOCS,TICKETS})});rows.push({t:"Tickets abiertos",s:`${TICKETS.filter(t=>!["cerrado","resuelto"].includes((t.estado||"").toLowerCase())).length} activos`});rows.push({t:"Documentos vigentes",s:`${DOCS.filter(x=>!x.eliminado).filter(d=>sem(d.fin_vigencia).t==="Vigente").length} vigentes`});if($("#quickChecklist"))$("#quickChecklist").innerHTML=rows.map(x=>`<div class="step"><span class="dot"></span><div><strong>${esc(x.t)}</strong><div class="item-meta">${esc(x.s)}</div></div></div>`).join("")};

export const renderCRM=({CLIENT})=>{if($("#cNombreEdit"))$("#cNombreEdit").value=CLIENT?.nombre||"";if($("#cResponsable"))$("#cResponsable").value=CLIENT?.rol_responsable||"";if($("#cCorreo"))$("#cCorreo").value=CLIENT?.correo||"";if($("#cTelefono"))$("#cTelefono").value=CLIENT?.telefono||"";if($("#cEstadoEdit"))$("#cEstadoEdit").value=CLIENT?.estatus||"activo";if($("#cFavorito"))$("#cFavorito").checked=!!CLIENT?.favorito;if($("#cComentarios"))$("#cComentarios").value=CLIENT?.comentarios||""};

export const previewUpload=data=>{if($("#pvSistema"))$("#pvSistema").textContent=NICE[data.sistema_norm]||data.sistema||"—";if($("#pvVersion"))$("#pvVersion").textContent=data.version_comercial||"—";if($("#pvTipo"))$("#pvTipo").textContent=data.tipo_documento||"—";if($("#pvLic"))$("#pvLic").textContent=data.tipo_licencia||"—";if($("#pvUsuarios"))$("#pvUsuarios").textContent=data.usuarios||"—";if($("#pvEmpresas"))$("#pvEmpresas").textContent=data.empresas_info||"—";if($("#pvSerie"))$("#pvSerie").textContent=data.numero_serie||"—";if($("#pvVer"))$("#pvVer").textContent=data.verificador||"—";if($("#pvEmpresa"))$("#pvEmpresa").textContent=data.empresa_certificado||"—";if($("#pvVigencia"))$("#pvVigencia").textContent=data.fin_vigencia?fmt(data.fin_vigencia):"—";if($("#pvLectura"))$("#pvLectura").textContent=data.lectura_pdf_ok?"OK":"Pendiente";if($("#pvRevision"))$("#pvRevision").textContent=data.requiere_revision?"Sí":"No"};

export const renderTicketFiles=files=>{if($("#ticketFilesList"))$("#ticketFilesList").innerHTML=files.length?files.map((f,i)=>`<div class="item"><div class="item-title">${esc(f.name)}</div><div class="item-meta">${Math.round((f.size||0)/1024)} KB · ${esc(f.type||"archivo")}</div><div class="toolbar mt8"><button class="mini ghost" data-del-ticket-file="${i}">Quitar</button></div></div>`).join(""):`<div class="empty">Sin adjuntos</div>`};

export const renderAccess=({acc})=>{if($("#accVps"))$("#accVps").value=acc?.vps||"";if($("#accRdpPort"))$("#accRdpPort").value=acc?.rdpPort||"";if($("#accUser"))$("#accUser").value=acc?.user||"";if($("#accPass"))$("#accPass").value=acc?.pass||"";if($("#accAnydesk"))$("#accAnydesk").value=acc?.anydesk||"";if($("#accExtra"))$("#accExtra").value=acc?.extra||"";if($("#accNotes"))$("#accNotes").value=acc?.notes||""};
