import{$,toast,esc}from"./global.js";

const API_BASE="https://ovfmqqqwezfdtgrtkjhf.supabase.co/functions/v1";
const QS=new URLSearchParams(location.search),folio=QS.get("folio")||"",token=QS.get("token")||"";
const fmt=v=>v?new Date(v).toLocaleString("es-MX"):"—";
const stateKey=v=>(v||"").toString().toLowerCase().trim();
const stateLabel=v=>stateKey(v)==="en_proceso"?"En revisión":stateKey(v)==="esperando_cliente"?"Esperando tu respuesta":stateKey(v)==="resuelto"?"Resuelto":stateKey(v)==="cerrado"?"Cerrado":"Recibido";
const stepMap=v=>{const s=stateKey(v);return[{k:"abierto",t:"Recibido",done:true,active:s==="abierto"},{k:"en_proceso",t:"En revisión",done:["en_proceso","esperando_cliente","resuelto","cerrado"].includes(s),active:s==="en_proceso"},{k:"esperando_cliente",t:"Esperando tu respuesta",done:["esperando_cliente","resuelto","cerrado"].includes(s),active:s==="esperando_cliente"},{k:"resuelto",t:"Resuelto",done:["resuelto","cerrado"].includes(s),active:s==="resuelto"},{k:"cerrado",t:"Cerrado",done:s==="cerrado",active:s==="cerrado"}]};
const setBasic=t=>{$("#stTitle").textContent=t?.titulo||"Seguimiento de ticket";$("#stLead").textContent="Consulta el avance de tu caso sin iniciar sesión.";$("#stFolio").textContent=t?.folio||"—";$("#stTicketTitle").textContent=t?.titulo||"—";$("#stType").textContent=t?.tipo||"—";$("#stPriority").textContent=t?.prioridad||"—";$("#stUpdated").textContent=fmt(t?.fecha_actualizacion||t?.fecha_creacion);$("#stState").textContent=stateLabel(t?.estado);$("#stChips").innerHTML=`<span class="tag">${esc(t?.folio||"Sin folio")}</span><span class="tag">${esc(stateLabel(t?.estado))}</span>${t?.prioridad?`<span class="tag">${esc(t.prioridad)}</span>`:""}`};
const renderTimeline=t=>{const steps=stepMap(t?.estado),pub=Array.isArray(t?.timeline_publica)?t.timeline_publica:[];const base=steps.map(x=>`<div class="item"><div class="item-title">${x.done?"✓":"⏳"} ${x.t}</div><div class="item-meta">${x.active?"Estado actual":x.done?"Completado":"Pendiente"}</div></div>`).join("");const extra=pub.map(x=>`<div class="item"><div class="item-title">${esc(x?.titulo||"Movimiento")}</div><div class="item-meta">${fmt(x?.fecha)}${x?.texto?` · ${esc(x.texto)}`:""}</div></div>`).join("");$("#stTimeline").innerHTML=base+extra};
const toggleReply=t=>{const on=stateKey(t?.estado)==="esperando_cliente";$("#stReplyBox")?.classList.toggle("hidden",!on);$("#stReplyStatus").textContent=on?"Adjunta aquí lo que te solicitamos para avanzar más rápido.":"Este espacio se habilita cuando el caso está esperando tu respuesta."};
const load=async()=>{if(!folio||!token){$("#stTitle").textContent="Enlace incompleto";$("#stLead").textContent="Falta folio o token.";return}try{const r=await fetch(`${API_BASE}/estado-ticket?folio=${encodeURIComponent(folio)}&token=${encodeURIComponent(token)}`);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"No se pudo consultar el ticket");setBasic(j.ticket);renderTimeline(j.ticket);toggleReply(j.ticket)}catch(ex){$("#stTitle").textContent="No pudimos abrir el seguimiento";$("#stLead").textContent=ex?.message||"Enlace inválido o expirado.";toast(ex?.message||"Error al consultar","bad")}};
const sendReply=async()=>{const txt=$("#stReplyText").value.trim(),files=$("#stReplyFiles").files||[];if(!txt&&files.length===0)return $("#stReplyStatus").textContent="Agrega un mensaje o al menos un archivo.";$("#stReplySend").disabled=true;$("#stReplyStatus").textContent="Enviando respuesta...";try{const fd=new FormData();fd.append("folio",folio);fd.append("token",token);fd.append("texto",txt);[...files].forEach(f=>fd.append("files",f));const r=await fetch(`${API_BASE}/estado-ticket-responder`,{method:"POST",body:fd});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"No se pudo enviar la respuesta");$("#stReplyText").value="";$("#stReplyFiles").value="";$("#stReplyStatus").textContent="Respuesta enviada correctamente.";toast("Respuesta enviada","ok");await load()}catch(ex){$("#stReplyStatus").textContent=ex?.message||"No se pudo enviar la respuesta.";toast(ex?.message||"Error al enviar","bad")}finally{$("#stReplySend").disabled=false}};
document.addEventListener("DOMContentLoaded",()=>{$("#stReplySend")?.addEventListener("click",sendReply);load()});
