export const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
export const esc=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
export const norm=v=>(v||"").toString().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim();
export const qp=k=>new URLSearchParams(location.search).get(k);

export const show=v=>{const el=typeof v==="string"?$(v):v;el?.classList.remove("hidden");el?.classList.add("open");el?.removeAttribute("hidden");return el};
export const hide=v=>{const el=typeof v==="string"?$(v):v;el?.classList.add("hidden");el?.classList.remove("open");el?.setAttribute("hidden","hidden");return el};

export const toggle=sel=>{$(sel)?.classList.toggle("hidden");$(sel)?.classList.toggle("open")};

export const toast=(text,type="",ms=2600)=>{const d=document.createElement("div");d.className=`toast ${type}`.trim();d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),ms)};
export const debounce=(fn,ms=220)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
export const copyTxt=(v,msg="Copiado")=>navigator.clipboard.writeText(v||"").then(()=>toast(msg,"ok")).catch(()=>toast("No se pudo copiar","bad"));

export const bindModal=(sel,closeSel=".close,.close-x,.icon-btn")=>{const m=$(sel);if(!m||m.dataset.bound)return;m.dataset.bound="1";m.addEventListener("click",e=>{if(e.target===m||e.target.closest(closeSel))hide(sel)})};

export const applyTheme=v=>{const t=v==="dark"?"dark":"light";document.documentElement.setAttribute("data-theme",t);const label=$("[data-theme-label]");if(label)label.textContent=t==="dark"?"Oscuro":"Claro";return t};
export const toggleTheme=()=>{const next=document.documentElement.getAttribute("data-theme")==="dark"?"light":"dark";localStorage.setItem("expiriti_theme",next);applyTheme(next);return next};
export const initTheme=()=>applyTheme(localStorage.getItem("expiriti_theme")||"light");

export const initThemeToggle=()=>{if(document.documentElement.dataset.themeBound)return;document.documentElement.dataset.themeBound="1";document.addEventListener("click",e=>{if(e.target.closest("[data-theme-toggle]"))toggleTheme()})};

export const initRayito=()=>{if($("#rayito"))return;const b=document.createElement("button");b.id="rayito";b.type="button";b.textContent="⚡";b.style.cssText="position:fixed;right:14px;bottom:14px;z-index:80;width:52px;height:52px;border-radius:999px;border:1px solid rgba(255,255,255,.12);background:linear-gradient(135deg,#2dd4bf,#60a5fa);color:#041018;font-size:20px;font-weight:900;box-shadow:0 12px 30px rgba(0,0,0,.22);cursor:pointer";const p=document.createElement("div");p.id="rayito-panel";p.className="panel hidden";p.style.cssText="position:fixed;right:14px;bottom:74px;width:260px;z-index:79";p.innerHTML=`<div class="list"><button class="mini" type="button">Acción 1</button><button class="mini" type="button">Acción 2</button><button class="mini" type="button">Acción 3</button></div>`;document.body.appendChild(b);document.body.appendChild(p);b.addEventListener("click",()=>toggle("#rayito-panel"))};
export const setRayitoItems=items=>{const p=$("#rayito-panel");if(!p)return;const arr=(items||[]).filter(Boolean);p.innerHTML=`<div class="list">${arr.length?arr.map((x,i)=>`<button class="mini" type="button" data-rayito="${i}">${esc(x.label||`Acción ${i+1}`)}</button>`).join(""):`<div class="mut">Sin acciones</div>`}</div>`;$$("[data-rayito]",p).forEach?.(()=>{});p.querySelectorAll("[data-rayito]").forEach(b=>b.addEventListener("click",()=>{const fn=arr[+b.dataset.rayito]?.onClick;try{fn&&fn()}catch(err){console.error(err)}}))}

document.addEventListener("DOMContentLoaded",()=>{initTheme();initThemeToggle()});
const APP_PANEL_MAP={
  infra_vps:{title:"Servidores",sub:"VPS / VDI",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Servidores</div><div class="panel-v">Consulta rápida de VPS / VDI para soporte operativo.</div></div></div><div class="panel-card"><div class="panel-kv"><div class="panel-k">Qué conviene ver aquí</div><div class="panel-v">Cliente, IP o ID, usuario, password, notas, horario de soporte, versión de Windows Server, SQL, respaldo y riesgo técnico.</div></div></div>`},
  infra_anydesk:{title:"Servidores",sub:"Accesos AnyDesk",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Accesos AnyDesk</div><div class="panel-v">Consulta rápida por cliente, alias, ID y notas internas.</div></div></div><div class="panel-card"><div class="panel-kv"><div class="panel-k">Uso sugerido</div><div class="panel-v">Úsalo para accesos recurrentes. Si el acceso cambia mucho, mejor dejarlo también en cliente.html.</div></div></div>`},
  polizas:{title:"Pólizas",sub:"Vista interna de seguimiento",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Pólizas</div><div class="panel-v">Clientes con póliza, contexto reciente y acceso rápido a seguimiento.</div></div></div>`},
  oportunidades:{title:"Ventas",sub:"Oportunidades",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Matriz de oportunidades</div><div class="panel-v">Cruce comercial entre sistemas actuales, faltantes y próxima acción.</div></div></div>`},
  renovaciones:{title:"Ventas",sub:"Renovaciones",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Renovaciones</div><div class="panel-v">Seguimiento comercial y operativo para cartera por vencer o vencida.</div></div></div>`},
  admin_tools:{title:"Admin",sub:"Herramientas",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Admin</div><div class="panel-v">Vista reservada para herramientas administrativas.</div></div></div>`},
  recent_clients:{title:"Clientes recientes",sub:"Últimos clientes vistos",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Clientes recientes</div><div class="panel-v" id="recentClientsBody">Aún no hay clientes recientes.</div></div></div>`},
  shortcuts:{title:"Atajos de teclado",sub:"Accesos rápidos globales",html:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Atajos</div><div class="panel-v">/ → Buscar<br>i d → Ir a inicio<br>i t → Ir a tickets<br>n t → Nuevo ticket<br>esc → Cerrar panel o modal<br>? → Ver esta ayuda</div></div></div>`}
};
export const pushRecentClient=client=>{try{if(!client?.id||!client?.nombre)return;const key="expiriti_recent_clients",cur=JSON.parse(localStorage.getItem(key)||"[]"),next=[{id:String(client.id),nombre:String(client.nombre)} ,...cur.filter(x=>String(x.id)!==String(client.id))].slice(0,8);localStorage.setItem(key,JSON.stringify(next))}catch{}};
export const readRecentClients=()=>{try{return JSON.parse(localStorage.getItem("expiriti_recent_clients")||"[]")}catch{return[]}};
export const setRailOpenCount=count=>{const el=$("#railOpenCount");if(el)el.textContent=String(count??0)};
export const openAppPanel=({title="Panel",sub="Vista interna",html=""}={})=>{const p=$("#appPanel"),b=$("#appPanelBackdrop");if(!p)return;$("#appPanelTitle")&&($("#appPanelTitle").textContent=title);$("#appPanelSub")&&($("#appPanelSub").textContent=sub);$("#appPanelBody")&&($("#appPanelBody").innerHTML=html);p.classList.add("open");b?.classList.add("open")};
export const closeAppPanel=()=>{$("#appPanel")?.classList.remove("open");$("#appPanelBackdrop")?.classList.remove("open")};
export const initAppPanel=()=>{if(document.documentElement.dataset.appPanelBound)return;document.documentElement.dataset.appPanelBound="1";document.addEventListener("click",e=>{if(e.target.closest("#appPanelClose")||e.target.closest("#appPanelBackdrop"))closeAppPanel();const op=e.target.closest("[data-open-panel]");if(!op)return;const key=op.dataset.openPanel;if(key==="recent_clients"){const items=readRecentClients(),html=items.length?`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Últimos clientes vistos</div><div class="panel-v">${items.map(x=>`<button class="btn" type="button" data-recent-client="${esc(x.id)}" data-recent-name="${esc(x.nombre)}">${esc(x.nombre)}</button>`).join(" ")}</div></div></div>`:`<div class="panel-card"><div class="panel-kv"><div class="panel-k">Últimos clientes vistos</div><div class="panel-v">Aún no hay clientes recientes.</div></div></div>`;return openAppPanel({title:"Clientes recientes",sub:"Últimos clientes vistos",html})}const cfg=APP_PANEL_MAP[key];if(cfg)openAppPanel(cfg)});document.addEventListener("keydown",e=>{const tag=(document.activeElement?.tagName||"").toLowerCase(),typing=["input","textarea","select"].includes(tag)||document.activeElement?.isContentEditable;if(e.key==="Escape")return closeAppPanel();if(typing&&e.key!=="/")return;if(e.key==="?"){e.preventDefault();return openAppPanel(APP_PANEL_MAP.shortcuts)}if(e.key==="/"){e.preventDefault();return document.querySelector("#searchInput,#tkSearch")?.focus()}if(e.key.toLowerCase()==="i"&&window.__exp_next_key==="d"){window.__exp_next_key="";location.href="dashboard.html";return}if(e.key.toLowerCase()==="i"&&window.__exp_next_key==="t"){window.__exp_next_key="";location.href="tickets.html";return}if(e.key.toLowerCase()==="n"&&window.__exp_next_key==="t"){window.__exp_next_key="";document.querySelector("#heroNewTicketBtn,#newTicketTopBtn,#tkNewBtn")?.click();return}if(e.key.toLowerCase()==="i"){window.__exp_next_key="";setTimeout(()=>window.__exp_next_key="",700);window.__exp_next_key="pending_i";return}if(e.key.toLowerCase()==="d"&&window.__exp_next_key==="pending_i"){window.__exp_next_key="d";return}if(e.key.toLowerCase()==="t"&&window.__exp_next_key==="pending_i"){window.__exp_next_key="t";return}if(e.key.toLowerCase()==="n"){window.__exp_next_key="";setTimeout(()=>window.__exp_next_key="",700);window.__exp_next_key="pending_n";return}if(e.key.toLowerCase()==="t"&&window.__exp_next_key==="pending_n"){window.__exp_next_key="t";return}});document.addEventListener("click",e=>{const b=e.target.closest("[data-recent-client]");if(!b)return;location.href=`cliente.html?id=${b.dataset.recentClient}`})};
export const setAppRole=role=>{const r=norm(role||"soporte"),isSupport=["soporte","support"].includes(r),isSales=["ventas","venta","sales"].includes(r),isAdmin=r==="admin";document.querySelectorAll("[data-role-only]").forEach(el=>{const need=(el.getAttribute("data-role-only")||"").split(/\s+/).filter(Boolean),ok=need.includes("admin")&&isAdmin||need.includes("soporte")&&isSupport||need.includes("ventas")&&isSales||need.includes("support")&&isSupport;el.hidden=!ok})};
export const initAppRail=page=>{const rail=$("#appRail"),scrim=$("#appScrim"),toggle=$("#railToggle");if(!rail)return;const mobile=()=>window.matchMedia("(max-width: 980px)").matches;toggle?.addEventListener("click",()=>{rail.classList.toggle("open");scrim?.classList.toggle("open",rail.classList.contains("open"))});scrim?.addEventListener("click",()=>{rail.classList.remove("open");scrim.classList.remove("open")});document.querySelectorAll("[data-rail-parent]").forEach(b=>{b.addEventListener("click",e=>{if(!mobile())return;e.preventDefault();b.closest(".rail-group")?.classList.toggle("open")})});if(page)document.querySelector(`[data-nav="${page}"]`)?.classList.add("is-active")};
