import{$,$$,toast,esc,debounce}from"./global.js";
import{createClient as C}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm";

const SB_URL="https://ovfmqqqwezfdtgrtkjhf.supabase.co",SB_KEY="sb_publishable_2ftu336Kc06w2I2iTwoIpQ_usfSTNG9",sb=C(SB_URL,SB_KEY);
const ST={files:[],sending:false,notice:null,faq:null},MAX_FILES=10,MAX_MB_FILE=20,MAX_MB_TOTAL=60,ALLOWED_EXT=["jpg","jpeg","png","webp","pdf","xml","xls","xlsx","csv","txt","zip"],ALLOWED_MIME=["image/jpeg","image/png","image/webp","application/pdf","text/xml","application/xml","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv","text/plain","application/zip","application/x-zip-compressed"];
const SUPPORT_ENDPOINT="https://ovfmqqqwezfdtgrtkjhf.supabase.co/functions/v1/submit-support";
const STATUS_PAGE="estado.html";
const human=n=>n>=1024*1024?`${(n/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`,digits=v=>(v||"").replace(/\D+/g,""),validMail=v=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),ext=f=>(f?.name?.split(".").pop()||"").toLowerCase(),fileKey=f=>`${(f.name||"").toLowerCase()}__${f.size||0}__${(f.type||"").toLowerCase()}`,total=()=>ST.files.reduce((a,f)=>a+(f.size||0),0),allowedFile=f=>ALLOWED_EXT.includes(ext(f))||ALLOWED_MIME.includes((f.type||"").toLowerCase());
const impactToPriority=v=>v==="alta"?"alta":v==="media"?"media":"baja";
const mxNow=()=>new Date(new Date().toLocaleString("en-US",{timeZone:"America/Mexico_City"}));
const inUrgentWindow=()=>{const d=mxNow(),day=d.getDay(),h=d.getHours(),m=d.getMinutes(),hm=h*60+m;if(day>=1&&day<=5)return hm>=600&&hm<1080;if(day===6)return hm>=600&&hm<840;return false};
const urgentMsg=()=>inUrgentWindow()?"Estás dentro del horario de urgencias. Si compartes el acceso remoto, podremos acelerar la revisión.":"Estás fuera del horario de urgencias. Tu caso quedará registrado y el equipo lo tomará a primera hora hábil.";
const syncUrgentUi=()=>{const on=$("#spImpact")?.value==="alta";$("#spUrgentBox")?.classList.toggle("hidden",!on);if($("#spUrgentMsg"))$("#spUrgentMsg").textContent=urgentMsg()};
const setBusy=v=>{ST.sending=!!v;$("#spSendBtn")&&($("#spSendBtn").disabled=ST.sending);$("#spDraftBtn")&&($("#spDraftBtn").disabled=ST.sending);$("#spFiles")&&($("#spFiles").disabled=ST.sending)};
const setStatus=(t,type="")=>{$("#spStatus").textContent=t;$("#spStatus").className=`mut ${type}`.trim()};
const preview=()=>{$("#pvTitle").textContent=$("#spTitle").value.trim()||"—";$("#pvSystem").textContent=$("#spSystem").value||"—";$("#pvImpact").textContent=`${$("#spImpact").selectedOptions[0]?.textContent||"—"}${$("#spSince")?.value?.trim()?` · ${$("#spSince").value.trim()}`:""}${$("#spAffected")?.selectedOptions?.[0]?.textContent?` · ${$("#spAffected").selectedOptions[0].textContent}`:""}`};
const renderFiles=()=>{const box=$("#spFilesMeta");if(!box)return;box.innerHTML=ST.files.length?ST.files.map((f,i)=>`<div class="item"><div class="item-title">${esc(f.name)}</div><div class="item-meta">${human(f.size)} · ${esc(ext(f).toUpperCase()||"ARCH")} · <button class="mini btn-ghost" type="button" data-del="${i}">Quitar</button></div></div>`).join(""):`<div class="empty-state">Sin adjuntos.</div>`};
const addFiles=list=>{const incoming=[...(list||[])],seen=new Set(ST.files.map(fileKey));let added=0,ignored=0;for(const f of incoming){if(ST.files.length>=MAX_FILES){ignored++;continue}if(!allowedFile(f)){ignored++;continue}if((f.size||0)>MAX_MB_FILE*1024*1024){ignored++;continue}if(seen.has(fileKey(f))){ignored++;continue}if(total()+(f.size||0)>MAX_MB_TOTAL*1024*1024){ignored++;continue}ST.files.push(f);seen.add(fileKey(f));added++}if(added&&ignored)setStatus(`Se agregaron ${added} archivo(s). Se omitieron ${ignored}.`,"warn");else if(added)setStatus(`${ST.files.length} adjunto(s) listos.`,"ok");else setStatus(`No se agregaron archivos. Revisa tipo, peso o duplicados.`,"bad");renderFiles()};
const clearForm=()=>{$("#supportForm").reset();ST.files=[];ST.faq=null;renderFiles();renderFaq(null);preview();syncUrgentUi();setBusy(false);setStatus("Completa los datos principales y agrega evidencia si la tienes.")};
const validate=()=>{if(!$("#spName").value.trim())return"Falta tu nombre.";if(!$("#spCompany").value.trim())return"Falta la empresa.";if(!validMail($("#spEmail").value.trim()))return"El correo no parece válido.";if($("#spPhone").value.trim()&&digits($("#spPhone").value).length<10)return"El teléfono parece incompleto.";if(!$("#spSystem").value.trim())return"Selecciona el sistema.";if(!$("#spGoal").value.trim())return"Indica qué intentabas hacer.";if(!$("#spTitle").value.trim())return"Falta el título del caso.";if($("#spTitle").value.trim().length<6)return"El título es demasiado corto.";if(!$("#spDesc").value.trim())return"Describe qué ocurrió.";if($("#spDesc").value.trim().length<20)return"Describe un poco más el caso.";if(!$("#spSince").value.trim())return"Indica desde cuándo ocurre.";if(!$("#spAvailability").value.trim())return"Indica un horario disponible para contacto.";if(total()>MAX_MB_TOTAL*1024*1024)return"El total de adjuntos excede el límite permitido.";return""};
const buildBody=()=>({folio_local:`SP-${Date.now().toString().slice(-8)}`,nombre:$("#spName").value.trim(),empresa:$("#spCompany").value.trim(),correo:$("#spEmail").value.trim(),telefono:digits($("#spPhone").value),categoria:$("#spCategory").value,sistema:$("#spSystem").value,objetivo:$("#spGoal").value.trim(),titulo:$("#spTitle").value.trim(),descripcion:$("#spDesc").value.trim(),impacto:$("#spImpact").value,prioridad:impactToPriority($("#spImpact").value),canal:$("#spChannel").value,desde_cuando:$("#spSince").value.trim(),afecta_a:$("#spAffected").value,ultimo_cambio:$("#spLastChange").value,horario_contacto:$("#spAvailability").value.trim(),contexto_adicional:$("#spExtra").value.trim(),anydesk:$("#spAnydesk")?.value?.trim()||"",ventana_urgencia:inUrgentWindow(),adjuntos:ST.files.map(f=>({nombre:f.name,peso:f.size,tipo:f.type||ext(f)||"archivo"})),total_adjuntos:ST.files.length,total_peso:total(),created_at:new Date().toISOString(),origen:"soporte_publico",estado:"abierto",aviso_global_id:ST.notice?.id||null});
const looksLikeTimbradoIssue=()=>{const txt=`${$("#spTitle")?.value||""} ${$("#spDesc")?.value||""} ${$("#spGoal")?.value||""} ${$("#spSystem")?.value||""}`.toLowerCase();return["timbr","cfdi","xml","factura","sat","PAC","pac"].some(x=>txt.includes(x.toLowerCase()))};
const maybeWarnGlobalIssue=()=>{if(!ST.notice||!looksLikeTimbradoIssue())return false;return confirm(`Hay un aviso global activo:\n\n${ST.notice.titulo}\n${ST.notice.mensaje}\n\nSi tu caso corresponde a esta intermitencia general, quizá no necesites levantar un ticket nuevo.\n\n¿Aun así deseas enviarlo?`)===false};
const renderNotice=notice=>{const wrap=$("#supportNoticeWrap"),box=$("#supportGlobalNotice");if(!wrap||!box)return;ST.notice=notice||null;if(!notice){wrap.hidden=true;box.innerHTML="";return}wrap.hidden=false;box.className=`support-global-notice ${esc(notice.severidad||"warn")}`;box.innerHTML=`<div class="notice-ic">${notice.severidad==="danger"?"⚠️":notice.severidad==="info"?"ℹ️":"⏳"}</div><div class="notice-copy"><div class="notice-title">${esc(notice.titulo||"Aviso global")}</div><div class="notice-text">${esc(notice.mensaje||"")}</div></div>`};
const FAQS=[{id:"timbrado",title:"Posible tema de timbrado / CFDI",text:"Parece un caso relacionado con timbrado, CFDI, XML o PAC. Antes de esperar soporte, revisa si el error ocurrió al sellar, validar XML o conectar con el PAC.",link:"#",fill:"Al intentar timbrar / procesar CFDI aparece un error. Ya validé que el problema está relacionado con XML, PAC o timbrado."},{id:"acceso",title:"Posible problema de acceso o apertura",text:"Parece un problema al abrir el sistema, entrar a empresa o iniciar sesión. Ayuda mucho indicar si afecta a todos, solo a un usuario y si hubo cambio de equipo o contraseña.",link:"#",fill:"El sistema no abre o no permite entrar. Confirmo si afecta a todos o solo a un usuario y si hubo cambios recientes."},{id:"xml",title:"Posible problema de XML",text:"Si el caso es de XML, conviene adjuntar un archivo de ejemplo y explicar si el error aparece al importar, validar o relacionar CFDI.",link:"#",fill:"El problema ocurre al importar, validar o relacionar XML / CFDI. Adjuntaré un ejemplo para revisión."},{id:"red",title:"Posible problema de red o servidor",text:"Si el sistema dejó de funcionar tras cambio de red, internet o servidor, indícalo. Eso acelera mucho el diagnóstico.",link:"#",fill:"El problema parece relacionado con red, internet, servidor o acceso remoto. Lo indico para revisión."}];
const faqNeedle=()=>`${$("#spTitle")?.value||""} ${$("#spDesc")?.value||""} ${$("#spGoal")?.value||""} ${$("#spSystem")?.value||""}`.toLowerCase();
const pickFaq=txt=>{if(/timbr|cfdi|xml|pac|factura|sat/.test(txt))return FAQS[0];if(/abrir|acceso|entrar|inicia|login|sesion|empresa/.test(txt))return FAQS[1];if(/xml|cfdi|importar|validar|relacionar/.test(txt))return FAQS[2];if(/red|internet|servidor|remoto|anydesk|vpn/.test(txt))return FAQS[3];return null};
const renderFaq=faq=>{const box=$("#spFaqBox");if(!box)return;ST.faq=faq||null;box.classList.toggle("hidden",!faq);if(!faq)return;$("#spFaqTitle").textContent=faq.title;$("#spFaqText").textContent=faq.text;$("#spFaqLink").href=faq.link||"#"};
const evalFaq=()=>{const txt=faqNeedle();if(txt.trim().length<18)return renderFaq(null);renderFaq(pickFaq(txt))};
const useFaq=()=>{if(!ST.faq)return;const cur=$("#spExtra")?.value?.trim()||"";$("#spExtra").value=`${cur}${cur?"\n\n":""}${ST.faq.fill}`;setStatus("Se agregó una sugerencia útil al contexto adicional.","ok");$("#spExtra")?.focus()};
 
const loadGlobalNotice=async()=>{try{const now=new Date().toISOString();const {data,error}=await sb.from("avisos_globales").select("id,titulo,mensaje,severidad,activo,mostrar_en_soporte,inicio_publicacion,fin_publicacion").eq("activo",true).eq("mostrar_en_soporte",true).lte("inicio_publicacion",now).or(`fin_publicacion.is.null,fin_publicacion.gte.${now}`).order("inicio_publicacion",{ascending:false}).limit(1).maybeSingle();if(error)throw error;renderNotice(data||null)}catch(err){console.warn("SUPPORT_NOTICE_LOAD_ERROR",err);renderNotice(null)}};
const send=async e=>{e.preventDefault();if(ST.sending)return;const err=validate();if(err)return setStatus(err,"bad");if(maybeWarnGlobalIssue())return setStatus("Se canceló el envío para evitar un ticket duplicado por aviso global activo.","warn");setBusy(true);setStatus("Enviando solicitud...");const data=buildBody();try{const fd=new FormData();Object.entries(data).forEach(([k,v])=>{if(k==="adjuntos")return;if(v===undefined||v===null)return;fd.append(k,typeof v==="string"?v:JSON.stringify(v))});ST.files.forEach(f=>fd.append("files",f));const r=await fetch(SUPPORT_ENDPOINT,{method:"POST",body:fd});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"No se pudo registrar la solicitud");const folioReal=j.folio||data.folio_local,magic=j.magic_link||"",exp=j.magic_expires||"",fallbackMagic=j.token?`${location.origin}${location.pathname.replace(/[^/]*$/,"")}${STATUS_PAGE}?folio=${encodeURIComponent(folioReal)}&token=${encodeURIComponent(j.token)}`:"",finalMagic=magic||fallbackMagic;setStatus(finalMagic?`Solicitud enviada correctamente. Folio ${folioReal}. Tu enlace de seguimiento quedó listo.`:`Solicitud enviada correctamente. Folio ${folioReal}. En breve revisaremos tu caso.`,"ok");toast(`Solicitud enviada · ${folioReal}`,"ok");$("#spMagicBox")?.remove();if(finalMagic){const box=document.createElement("div");box.id="spMagicBox";box.className="panel inset";box.innerHTML=`<div class="row-head"><h3>Tu enlace de seguimiento</h3></div><div class="mut">Guárdalo. Desde ahí podrás revisar avances y responder si necesitamos información.</div><div class="actions"><a class="btn btn-brand" href="${esc(finalMagic)}" target="_blank" rel="noopener">Abrir seguimiento</a><button class="btn btn-ghost" type="button" id="spCopyMagic">Copiar enlace</button><button class="btn" type="button" id="spNewTicket">Nuevo ticket</button></div>${exp?`<div class="mut">Disponible hasta: ${esc(new Date(exp).toLocaleString("es-MX"))}</div>`:""}<div class="mut">Folio: ${esc(folioReal)}</div>`;$("#spStatus")?.insertAdjacentElement("afterend",box);$("#spCopyMagic")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(finalMagic);toast("Enlace copiado","ok")}catch{toast("No se pudo copiar","bad")}});$("#spNewTicket")?.addEventListener("click",()=>{$("#spMagicBox")?.remove();clearForm();loadGlobalNotice().catch(()=>{})})}else{clearForm();await loadGlobalNotice()}}catch(ex){console.error("SUPPORT_SEND_ERROR",ex);setStatus(ex?.message||"No se pudo enviar la solicitud.","bad");toast(ex?.message||"Error al enviar la solicitud","bad")}finally{setBusy(false)}};
const fillMap={timbrar:{title:"No puedo timbrar",goal:"Timbrar una factura",desc:"Al intentar timbrar aparece un error y el proceso no termina. Indico qué documento intentaba timbrar, qué mensaje vi y desde cuándo ocurre.",sys:"CONTPAQi Comercial PREMIUM",impact:"alta"},abrir:{title:"No abre el sistema",goal:"Abrir el sistema",desc:"El sistema no abre o se cierra al iniciar. Indico si afecta a todos los usuarios, desde cuándo pasa y si hubo cambios recientes en el equipo.",sys:"",impact:"alta"},xml:{title:"Error con XML",goal:"Importar / validar XML",desc:"Tengo problema al abrir, validar o relacionar XML / CFDI. Indico si el XML es de proveedor o cliente y adjunto un ejemplo si es posible.",sys:"CONTPAQi XML en Línea",impact:"media"},empresa:{title:"Problema con empresa",goal:"Abrir o usar empresa",desc:"La empresa presenta error al abrir, respaldar o procesar información. Indico nombre de la empresa, mensaje visible y acción exacta que intentaba hacer.",sys:"",impact:"alta"}};
const applyFill=k=>{const x=fillMap[k];if(!x)return;$("#spTitle").value=x.title;$("#spGoal").value=x.goal;$("#spDesc").value=x.desc;$("#spSystem").value=x.sys;$("#spImpact").value=x.impact||"media";preview();setStatus("Se cargó una sugerencia rápida.","ok")};
const bind=()=>{$("#supportForm").addEventListener("submit",send);$("#spDraftBtn").addEventListener("click",clearForm);["#spTitle","#spSystem","#spImpact","#spSince","#spAffected"].forEach(sel=>$(sel)?.addEventListener("input",preview));["#spSystem","#spImpact","#spAffected"].forEach(sel=>$(sel)?.addEventListener("change",preview));$("#spImpact")?.addEventListener("change",syncUrgentUi);$("#spFiles").addEventListener("change",e=>{addFiles(e.target.files||[]);e.target.value=""});document.addEventListener("click",e=>{const del=e.target.closest("[data-del]");if(del){ST.files.splice(+del.dataset.del,1);renderFiles();setStatus(ST.files.length?`${ST.files.length} adjunto(s) listos.`:"Completa los datos principales y agrega evidencia si la tienes.");return}const fill=e.target.closest("[data-fill]");if(fill)applyFill(fill.dataset.fill)});["#spName","#spCompany","#spEmail","#spPhone","#spGoal","#spTitle","#spDesc","#spSince","#spAvailability","#spExtra"].forEach(sel=>$(sel)?.addEventListener("input",debounce(preview,120)));["#spTitle","#spDesc","#spGoal","#spSystem"].forEach(sel=>$(sel)?.addEventListener("input",debounce(evalFaq,180)));$("#spSystem")?.addEventListener("change",evalFaq);$("#spFaqUse")?.addEventListener("click",useFaq)};

document.addEventListener("DOMContentLoaded",async()=>{const box=document.createElement("div");box.id="spFilesMeta";box.className="list";$("#spFiles")?.closest(".field")?.appendChild(box);bind();preview();renderFiles();renderFaq(null);evalFaq();syncUrgentUi();await loadGlobalNotice()});
