import{$,$$,toast,esc,debounce}from"./global.js";

const ST={files:[],sending:false},MAX_FILES=10,MAX_MB_FILE=20,MAX_MB_TOTAL=60,ALLOWED_EXT=["jpg","jpeg","png","webp","pdf","xml","xls","xlsx","csv","txt","zip"],ALLOWED_MIME=["image/jpeg","image/png","image/webp","application/pdf","text/xml","application/xml","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv","text/plain","application/zip","application/x-zip-compressed"];
const human=n=>n>=1024*1024?`${(n/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`,digits=v=>(v||"").replace(/\D+/g,""),validMail=v=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),ext=f=>(f?.name?.split(".").pop()||"").toLowerCase(),fileKey=f=>`${(f.name||"").toLowerCase()}__${f.size||0}__${(f.type||"").toLowerCase()}`,total=()=>ST.files.reduce((a,f)=>a+(f.size||0),0);
const SUPPORT_ENDPOINT="https://TU-PROYECTO.supabase.co/functions/v1/submit-support";
const allowedFile=f=>ALLOWED_EXT.includes(ext(f))||ALLOWED_MIME.includes((f.type||"").toLowerCase());
const setBusy=v=>{ST.sending=!!v;$("#spSendBtn")&&($("#spSendBtn").disabled=ST.sending);$("#spDraftBtn")&&($("#spDraftBtn").disabled=ST.sending);$("#spFiles")&&($("#spFiles").disabled=ST.sending)};
const setStatus=(t,type="")=>{$("#spStatus").textContent=t;$("#spStatus").className=`mut ${type}`.trim()};
const preview=()=>{$("#pvTitle").textContent=$("#spTitle").value.trim()||"—";$("#pvSystem").textContent=$("#spSystem").value||"—";$("#pvImpact").textContent=`${$("#spImpact").selectedOptions[0]?.textContent||"—"}${$("#spSince")?.value?.trim()?` · ${$("#spSince").value.trim()}`:""}${$("#spAffected")?.selectedOptions?.[0]?.textContent?` · ${$("#spAffected").selectedOptions[0].textContent}`:""}`};
const renderFiles=()=>{const box=$("#spFilesMeta");if(!box)return;box.innerHTML=ST.files.length?ST.files.map((f,i)=>`<div class="item"><div class="item-title">${esc(f.name)}</div><div class="item-meta">${human(f.size)} · ${esc(ext(f).toUpperCase()||"ARCH")} · <button class="mini btn-ghost" type="button" data-del="${i}">Quitar</button></div></div>`).join(""):`<div class="empty-state">Sin adjuntos.</div>`};
const addFiles=list=>{const incoming=[...(list||[])],seen=new Set(ST.files.map(fileKey));let added=0,ignored=0,reasons=[];for(const f of incoming){if(ST.files.length>=MAX_FILES){ignored++;reasons.push("máximo de archivos");continue}if(!allowedFile(f)){ignored++;reasons.push("tipo no permitido");continue}if((f.size||0)>MAX_MB_FILE*1024*1024){ignored++;reasons.push("archivo excede peso");continue}if(seen.has(fileKey(f))){ignored++;reasons.push("duplicado");continue}if(total()+(f.size||0)>MAX_MB_TOTAL*1024*1024){ignored++;reasons.push("límite total");continue}ST.files.push(f);seen.add(fileKey(f));added++}if(added&&ignored)setStatus(`Se agregaron ${added} archivo(s). Se omitieron ${ignored}.`,"warn");else if(added)setStatus(`${ST.files.length} adjunto(s) listos.`,"ok");else setStatus(`No se agregaron archivos. Revisa tipo, peso o duplicados.`,"bad");renderFiles()};
const clearForm=()=>{$("#supportForm").reset();ST.files=[];renderFiles();preview();setBusy(false);setStatus("Completa los datos principales y agrega evidencia si la tienes.")};
const validate=()=>{if(!$("#spName").value.trim())return"Falta tu nombre.";if(!$("#spCompany").value.trim())return"Falta la empresa.";if(!validMail($("#spEmail").value.trim()))return"El correo no parece válido.";if($("#spPhone").value.trim()&&digits($("#spPhone").value).length<10)return"El teléfono parece incompleto.";if(!$("#spSystem").value.trim())return"Selecciona el sistema.";if(!$("#spGoal").value.trim())return"Indica qué intentabas hacer.";if(!$("#spTitle").value.trim())return"Falta el título del caso.";if($("#spTitle").value.trim().length<6)return"El título es demasiado corto.";if(!$("#spDesc").value.trim())return"Describe qué ocurrió.";if($("#spDesc").value.trim().length<20)return"Describe un poco más el caso.";if(!$("#spSince").value.trim())return"Indica desde cuándo ocurre.";if(!$("#spAvailability").value.trim())return"Indica un horario disponible para contacto.";if(total()>MAX_MB_TOTAL*1024*1024)return"El total de adjuntos excede el límite permitido.";return""};
const buildBody=()=>({folio_local:`SP-${Date.now().toString().slice(-8)}`,nombre:$("#spName").value.trim(),empresa:$("#spCompany").value.trim(),correo:$("#spEmail").value.trim(),telefono:digits($("#spPhone").value),categoria:$("#spCategory").value,sistema:$("#spSystem").value,objetivo:$("#spGoal").value.trim(),titulo:$("#spTitle").value.trim(),descripcion:$("#spDesc").value.trim(),impacto:$("#spImpact").value,prioridad:impactToPriority($("#spImpact").value),canal:$("#spChannel").value,desde_cuando:$("#spSince").value.trim(),afecta_a:$("#spAffected").value,ultimo_cambio:$("#spLastChange").value,horario_contacto:$("#spAvailability").value.trim(),contexto_adicional:$("#spExtra").value.trim(),adjuntos:ST.files.map(f=>({nombre:f.name,peso:f.size,tipo:f.type||ext(f)||"archivo"})),total_adjuntos:ST.files.length,total_peso:total(),created_at:new Date().toISOString(),origen:"soporte_publico",estado:"abierto"});
const send=async e=>{e.preventDefault();if(ST.sending)return;const err=validate();if(err)return setStatus(err,"bad");setBusy(true);setStatus("Enviando solicitud...");const data=buildBody();try{const fd=new FormData();Object.entries(data).forEach(([k,v])=>{if(k==="adjuntos")return;if(v===undefined||v===null)return;fd.append(k,typeof v==="string"?v:JSON.stringify(v))});ST.files.forEach(f=>fd.append("files",f));const r=await fetch(SUPPORT_ENDPOINT,{method:"POST",body:fd});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"No se pudo registrar la solicitud");setStatus(`Solicitud enviada correctamente. Folio ${j.folio||data.folio_local}.`,"ok");toast(`Solicitud enviada · ${j.folio||data.folio_local}`,"ok");clearForm()}catch(ex){setStatus(ex?.message||"No se pudo enviar la solicitud.","bad");toast("Error al enviar la solicitud","bad")}finally{setBusy(false)}};
const fillMap={timbrar:{title:"No puedo timbrar",goal:"Timbrar una factura",desc:"Al intentar timbrar aparece un error y el proceso no termina. Indico qué documento intentaba timbrar, qué mensaje vi y desde cuándo ocurre.",sys:"CONTPAQi Comercial PREMIUM",impact:"alta"},abrir:{title:"No abre el sistema",goal:"Abrir el sistema",desc:"El sistema no abre o se cierra al iniciar. Indico si afecta a todos los usuarios, desde cuándo pasa y si hubo cambios recientes en el equipo.",sys:"",impact:"alta"},xml:{title:"Error con XML",goal:"Importar / validar XML",desc:"Tengo problema al abrir, validar o relacionar XML / CFDI. Indico si el XML es de proveedor o cliente y adjunto un ejemplo si es posible.",sys:"CONTPAQi XML en Línea",impact:"media"},empresa:{title:"Problema con empresa",goal:"Abrir o usar empresa",desc:"La empresa presenta error al abrir, respaldar o procesar información. Indico nombre de la empresa, mensaje visible y acción exacta que intentaba hacer.",sys:"",impact:"alta"}};
const applyFill=k=>{const x=fillMap[k];if(!x)return;$("#spTitle").value=x.title;$("#spGoal").value=x.goal;$("#spDesc").value=x.desc;$("#spSystem").value=x.sys;$("#spImpact").value=x.impact||"media";preview();setStatus("Se cargó una sugerencia rápida.","ok")};
const bind=()=>{$("#supportForm").addEventListener("submit",send);$("#spDraftBtn").addEventListener("click",clearForm);["#spTitle","#spSystem","#spImpact","#spSince","#spAffected"].forEach(sel=>$(sel)?.addEventListener("input",preview));["#spSystem","#spImpact","#spAffected"].forEach(sel=>$(sel)?.addEventListener("change",preview));$("#spFiles").addEventListener("change",e=>{addFiles(e.target.files||[]);e.target.value=""});document.addEventListener("click",e=>{const del=e.target.closest("[data-del]");if(del){ST.files.splice(+del.dataset.del,1);renderFiles();setStatus(ST.files.length?`${ST.files.length} adjunto(s) listos.`:"Completa los datos principales y agrega evidencia si la tienes.");return}const fill=e.target.closest("[data-fill]");if(fill)applyFill(fill.dataset.fill)});["#spName","#spCompany","#spEmail","#spPhone","#spGoal","#spTitle","#spDesc","#spSince","#spAvailability","#spExtra"].forEach(sel=>$(sel)?.addEventListener("input",debounce(preview,120)))};

document.addEventListener("DOMContentLoaded",()=>{const box=document.createElement("div");box.id="spFilesMeta";box.className="list";$("#spFiles")?.closest(".field")?.appendChild(box);bind();preview();renderFiles()});
