import{supabase as s,guardSession,logAction,msg}from"./supabase.js";import{$,toast,ensureAppShell,setAppRole,setRailOpenCount,pushRecentClient,setGlobalSearchData,setBreadcrumb}from"./global.js";
const QS=new URLSearchParams(location.search),ID=QS.get("id")||"",ST={busy:false,menusOpen:false};let T=null,C=null,LOGS=[],HEAT={total30:0,urgent30:0,waitOpen:0,level:"Frío"},FILES=[];
const QR={
xml:{text:"Por favor, adjunta un XML / CFDI de ejemplo y, si es posible, una captura completa del mensaje de error para revisar el caso con mayor precisión.",kind:"solicitud",state:"esperando_cliente"},
captura:{text:"Por favor, comparte una captura completa de pantalla donde se vea el sistema, el mensaje de error y la acción que estabas realizando.",kind:"solicitud",state:"esperando_cliente"},
remoto:{text:"Para avanzar más rápido, comparte tu ID de acceso remoto y un horario disponible para conexión. Si aplica, indica también si debemos entrar al servidor o al equipo local.",kind:"solicitud",state:"esperando_cliente"},
horario:{text:"Compártenos por favor uno o dos horarios disponibles para revisión, y el medio preferido de contacto para continuar con el caso.",kind:"solicitud",state:"esperando_cliente"},
espera:{text:"Quedamos en espera de la información solicitada por parte del cliente para continuar con la revisión del caso.",kind:"seguimiento",state:"esperando_cliente"},
solucion:{text:"Se aplicó ajuste / validación operativa y el caso queda listo para confirmación con el cliente.",kind:"solucion",state:""},
resuelto:{text:"Se aplicó solución y el caso queda resuelto. Pendiente únicamente confirmación final del cliente si aplica.",kind:"solucion",state:"resuelto"}
};
const qrOpen=()=>{$("#quickReplies")&&( $("#quickReplies").hidden=false,$("#quickReplyBtn")?.classList.add("is-active"))};
const qrClose=()=>{$("#quickReplies")&&( $("#quickReplies").hidden=true,$("#quickReplyBtn")?.classList.remove("is-active"))};
const qrToggle=()=>$("#quickReplies")?.hidden?qrOpen():qrClose();
const applyQuickReply=k=>{const q=QR[k];if(!q)return;const box=$("#logText"),kind=$("#logKind"),state=$("#logState");if(box)box.value=(box.value.trim()?`${box.value.trim()}\n\n`:"")+q.text;if(kind&&q.kind)kind.value=q.kind;if(state&&q.state!==undefined)state.value=q.state;qrClose();box?.focus()};
const fileExt=n=>((n||"").split(".").pop()||"").toLowerCase(),isImg=x=>["jpg","jpeg","png","webp","gif","bmp","svg"].includes(fileExt(x?.nombre||x?.name||x?.nombre_archivo||x?.url||""))||String(x?.tipo||x?.type||x?.mime_type||"").startsWith("image/"),isPdf=x=>fileExt(x?.nombre||x?.name||x?.nombre_archivo||x?.url||"")==="pdf"||String(x?.tipo||x?.type||x?.mime_type||"").toLowerCase()==="application/pdf",isText=x=>["xml","txt","json","log","csv"].includes(fileExt(x?.nombre||x?.name||x?.nombre_archivo||x?.url||""))||["text/plain","text/xml","application/xml","application/json","text/csv"].includes(String(x?.tipo||x?.type||x?.mime_type||"").toLowerCase()),safeUrl=u=>{try{return /^https?:\/\//i.test(String(u||""))?u:""}catch{return""}},showEv=()=>{$("#evModal")&&($("#evModal").hidden=false,document.body.classList.add("modal-open"))},hideEv=()=>{$("#evModal")&&($("#evModal").hidden=true,document.body.classList.remove("modal-open"));$("#evBody")&&($("#evBody").innerHTML=`<div class="empty-state">Sin vista previa.</div>`);$("#evTitle")&&($("#evTitle").textContent="Vista previa");$("#evOpenRaw")&&($("#evOpenRaw").setAttribute("href","#"))};
const escHtml=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const openEvidence=async i=>{const files=Array.isArray(T?.adjuntos)?T.adjuntos:[],x=files[i];if(!x)return;const u=safeUrl(x?.url),name=x?.nombre||x?.name||`Adjunto ${Number(i)+1}`;$("#evTitle")&&($("#evTitle").textContent=name);$("#evOpenRaw")&&($("#evOpenRaw").setAttribute("href",u||"#"));if(!u){$("#evBody").innerHTML=`<div class="empty-state">Este adjunto no tiene URL pública para vista previa.</div>`;return showEv()}if(isImg(x)){$("#evBody").innerHTML=`<img class="ev-img" src="${esc(u)}" alt="${esc(name)}">`;return showEv()}if(isPdf(x)){$("#evBody").innerHTML=`<iframe class="ev-frame" src="${esc(u)}" title="${esc(name)}"></iframe>`;return showEv()}if(isText(x)){try{const r=await fetch(u),txt=await r.text();$("#evBody").innerHTML=`<pre class="ev-pre">${escHtml(txt.slice(0,120000))}</pre>`;showEv()}catch{$("#evBody").innerHTML=`<div class="empty-state">No se pudo leer este archivo en vista previa.</div>`;showEv()}return}window.open(u,"_blank","noopener")};
const fmtDT=v=>v?new Date(v).toLocaleString("es-MX"):"—",fmtHM=v=>v?new Date(v).toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"}):"",esc=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),norm=v=>(v||"").toString().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim(),prettyBytes=n=>{const x=Number(n||0);return x>=1048576?`${(x/1048576).toFixed(1)} MB`:x>=1024?`${Math.max(1,Math.round(x/1024))} KB`:`${x} B`};
const rawState=v=>v||"abierto",priCls=v=>{const x=norm(v);return x==="urgente"?"bad":x==="alta"?"warn":x==="media"?"info":"ok"},stateKey=v=>{const x=norm(v);if(["abierto","nuevo"].includes(x))return"abierto";if(["en_proceso","en proceso","proceso"].includes(x))return"en_proceso";if(["esperando_cliente","esperando cliente","espera"].includes(x))return"esperando_cliente";if(["resuelto"].includes(x))return"resuelto";if(["cerrado","closed","done","cancelado"].includes(x))return"cerrado";return"abierto"},stateLabel=v=>stateKey(v)==="en_proceso"?"En proceso":stateKey(v)==="esperando_cliente"?"Esperando cliente":stateKey(v)==="resuelto"?"Resuelto":stateKey(v)==="cerrado"?"Cerrado":"Abierto",stateCls=v=>{const x=stateKey(v);return x==="resuelto"||x==="cerrado"?"ok":x==="esperando_cliente"?"warn":x==="en_proceso"?"info":"neutral"},ticketLink=()=>`${location.origin}${location.pathname}?id=${encodeURIComponent(ID)}`;
const setBusy=v=>{ST.busy=!!v;$("#saveLogBtn")&&($("#saveLogBtn").disabled=ST.busy);$("#tkRefreshBtn")&&($("#tkRefreshBtn").disabled=ST.busy);$("#copyMagicBtn")&&($("#copyMagicBtn").disabled=ST.busy);$("#askXmlBtn")&&($("#askXmlBtn").disabled=ST.busy);$("#askShotBtn")&&($("#askShotBtn").disabled=ST.busy);$("#askRemoteBtn")&&($("#askRemoteBtn").disabled=ST.busy);$("#setWaitBtn")&&($("#setWaitBtn").disabled=ST.busy);$("#setSolveBtn")&&($("#setSolveBtn").disabled=ST.busy);$("#reopenBtn")&&($("#reopenBtn").disabled=ST.busy);$("#closeBtn")&&($("#closeBtn").disabled=ST.busy)};
const logKindLabel=v=>v==="solicitud"?"Solicitud al cliente":v==="solucion"?"Solución aplicada":v==="seguimiento"?"Seguimiento":v==="nota"?"Nota interna":"Actualización";
const publicEntryTitle=v=>v==="solicitud"?"Soporte solicitó información":v==="solucion"?"Soporte confirmó una solución":v==="seguimiento"?"Actualización de soporte":"Actualización";
const humanLog=x=>{const a=String(x?.accion||""),d=x?.detalle||{},txt=d?.texto||d?.nota||d?.mensaje||"";if(a==="ticket_solicitud")return{side:"me",title:"Solicitud al cliente",text:txt||"Se pidió información al cliente.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_nota")return{side:"me",title:"Nota interna",text:txt||"Se registró una nota interna.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_seguimiento")return{side:"me",title:"Seguimiento",text:txt||"Se registró un avance.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_solucion")return{side:"me",title:"Solución aplicada",text:txt||"Se registró una solución.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_set_wait")return{side:"me",title:"Caso en espera de cliente",text:"Se dejó el caso esperando respuesta del cliente.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_set_solved")return{side:"me",title:"Caso resuelto",text:"Se marcó el caso como resuelto.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_reopened")return{side:"me",title:"Caso reabierto",text:"Se reabrió el caso para continuar la atención.",time:fmtHM(x.fecha||x.fecha_creacion)};if(a==="ticket_closed")return{side:"me",title:"Caso cerrado",text:"Se cerró el caso.",time:fmtHM(x.fecha||x.fecha_creacion)};if(txt)return{side:"me",title:logKindLabel(d.kind),text:txt,time:fmtHM(x.fecha||x.fecha_creacion)};return null};
const normalizeFiles=arr=>(Array.isArray(arr)?arr:[]).map((x,i)=>({id:String(x?.id||x?.storage_path||x?.url||i),nombre:x?.nombre||x?.name||x?.nombre_archivo||`Archivo ${i+1}`,tipo:x?.tipo||x?.type||x?.mime_type||"",tamano:x?.peso||x?.size||x?.tamano_bytes||0,url:x?.url||"",storage_path:x?.storage_path||x?.url_archivo||"",origen:x?.origen||"ticket"}));
const closeFileMenus=()=>document.querySelectorAll(".ev-menu.open").forEach(x=>x.classList.remove("open"));
const signedEvidenceUrl=async f=>{if(f.url)return f.url;if(!f.storage_path)return"";try{const{data,error}=await s.storage.from("soporte_adjuntos").createSignedUrl(f.storage_path,60*60*8);if(error)return"";return data?.signedUrl||""}catch{return""}};

const nextStep=t=>{const s=stateKey(t?.estado),d=norm(`${t?.titulo||""} ${t?.descripcion||""}`);if(s==="esperando_cliente")return"Esperar respuesta del cliente";if(s==="resuelto")return"Cerrar al confirmar";if(d.includes("xml"))return"Pedir XML";if(d.includes("captura")||d.includes("pantalla"))return"Revisar evidencia";if(d.includes("remoto")||d.includes("anydesk")||d.includes("teamviewer"))return"Coordinar acceso remoto";return s==="abierto"?"Hacer triage":"Dar seguimiento"};
const renderContext=()=>{$("#tkImpact").textContent=T?.impacto||T?.impact||"—";$("#tkAffected").textContent=T?.afecta_a||T?.afectados||"—";$("#tkSince").textContent=T?.desde_cuando||T?.since||"—";$("#tkNext").textContent=nextStep(T);$("#tkLastChange").textContent=T?.ultimo_cambio||"—";$("#tkAvailability").textContent=T?.horario_contacto||"—"};
const renderIdentity=()=>{const matchLabel=T?.match_nivel?`${T.match_nivel}${T?.match_score?` · score ${T.match_score}`:""}`:"—",identityOk=!!T?.cliente_id&&!T?.requiere_consolidacion;$("#tkCapturedCompany").textContent=T?.empresa_capturada||"—";$("#tkCapturedName").textContent=T?.nombre_capturado||T?.nombre_cliente_contacto||"—";$("#tkCapturedEmail").textContent=T?.correo_capturado||T?.correo_cliente||"—";$("#tkCapturedPhone").textContent=T?.telefono_capturada||T?.telefono_capturado||"—";$("#tkSuggestedClient").textContent=T?.cliente_id_sugerido?`ID ${T.cliente_id_sugerido}`:"—";$("#tkSuggestedContact").textContent=T?.contacto_id_sugerido?`ID ${T.contacto_id_sugerido}`:"—";$("#tkMatchMeta").textContent=matchLabel;$("#tkConsolidationState").textContent=T?.requiere_consolidacion?"Pendiente de revisión":identityOk?"Consolidado con cliente":"Sin pendiente operativo";$("#tkIdentityChips").innerHTML=`${T?.requiere_consolidacion?`<span class="tag warn">Por consolidar</span>`:identityOk?`<span class="tag ok">Consolidado con cliente</span>`:`<span class="tag ok">Sin pendiente</span>`}${!T?.cliente_id?`<span class="tag bad">Sin cliente ligado</span>`:""}${T?.match_nivel==="alto"?`<span class="tag ok">Match alto</span>`:T?.match_nivel==="medio"?`<span class="tag warn">Match medio</span>`:T?.match_nivel==="bajo"?`<span class="tag">Match bajo</span>`:""}${T?.contacto_es_nuevo?`<span class="tag info">Contacto nuevo</span>`:""}${T?.match_confirmado?`<span class="tag ok">Empresa confirmada</span>`:""}${T?.contacto_confirmado?`<span class="tag ok">Contacto confirmado</span>`:""}`;$("#tkUseSuggestedClientBtn")&&($("#tkUseSuggestedClientBtn").disabled=!T?.cliente_id_sugerido||!!T?.cliente_id);$("#tkMarkNewContactBtn")&&($("#tkMarkNewContactBtn").disabled=!T?.requiere_consolidacion);$("#tkMarkConsolidatedBtn")&&($("#tkMarkConsolidatedBtn").disabled=!T?.requiere_consolidacion)};
const useSuggestedClient=async()=>{if(!T?.cliente_id_sugerido)return toast("No hay cliente sugerido.","warn");const payload={cliente_id:T.cliente_id_sugerido,match_confirmado:true,requiere_consolidacion:false,fecha_actualizacion:new Date().toISOString()};const up=await s.from("tickets").update(payload).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_identity_use_suggested_client",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),cliente_id_sugerido:T?.cliente_id_sugerido||null,match_confirmado:true,requiere_consolidacion:false}}).catch(()=>{});await load();toast("Cliente sugerido aplicado.","ok")};
const markNewContact=async()=>{const payload={contacto_es_nuevo:true,contacto_confirmado:false,requiere_consolidacion:true,fecha_actualizacion:new Date().toISOString()};const up=await s.from("tickets").update(payload).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_identity_mark_new_contact",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),contacto_es_nuevo:true,contacto_confirmado:false,requiere_consolidacion:true}}).catch(()=>{});await load();toast("Caso marcado con contacto nuevo.","ok")};
const markConsolidated=async()=>{const payload={requiere_consolidacion:false,match_confirmado:!!T?.cliente_id,fecha_actualizacion:new Date().toISOString()};const up=await s.from("tickets").update(payload).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_identity_consolidated",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),requiere_consolidacion:false,match_confirmado:!!T?.cliente_id}}).catch(()=>{});await load();toast("Caso marcado como consolidado.","ok")};
const heatLevel=x=>x>=6?"🔥 Caliente":x>=3?"🟠 Sensible":"🟢 Estable";
const renderHeat=()=>{$("#tkHeatTotal").textContent=String(HEAT.total30??0);$("#tkHeatUrgent").textContent=String(HEAT.urgent30??0);$("#tkHeatWait").textContent=String(HEAT.waitOpen??0);$("#tkHeatLevel").textContent=HEAT.level||"🟢 Estable";$("#tkHeatChips").innerHTML=`<span class="tag ${HEAT.urgent30>0?"bad":"ok"}">${HEAT.urgent30>0?`${HEAT.urgent30} urgente(s) 30d`:"Sin urgentes 30d"}</span><span class="tag ${HEAT.waitOpen>0?"warn":"ok"}">${HEAT.waitOpen>0?`${HEAT.waitOpen} en espera`:"Sin espera activa"}</span><span class="tag ${HEAT.total30>=6?"bad":HEAT.total30>=3?"warn":"info"}">${HEAT.total30} ticket(s) 30d</span>`};
const slaMeta=t=>{const d=t?.sla_deadline?new Date(t.sla_deadline).getTime():0;if(!d)return{cls:"",txt:"Sin SLA"};const left=d-Date.now(),h=Math.max(0,Math.round(left/36e5));if(left<=0)return{cls:"bad",txt:"Vencido"};if(left<=2*36e5)return{cls:"warn",txt:`${h}h restantes`};return{cls:"ok",txt:`${h}h restantes`}};

const renderHeader=()=>{const sla=slaMeta(T);$("#tkTitle").textContent=T?.titulo||"Ticket";$("#tkClient").textContent=C?.nombre||T?.empresa_capturada||"—";$("#tkSystem").textContent=T?.tipo||"—";$("#tkState").textContent=stateLabel(rawState(T?.estado));$("#tkPriority").textContent=T?.prioridad||"—";$("#tkSla").textContent=sla.txt;$("#tkSla").className=`v small ${sla.cls}`.trim();$("#tkCreated").textContent=fmtDT(T?.fecha_creacion);$("#tkId").textContent=ID||"—";$("#tkStateTag").textContent=stateLabel(rawState(T?.estado));$("#tkPriorityTag").textContent=T?.prioridad||"—";$("#tkStateTag").className=`tag ${stateCls(T?.estado)}`.trim();$("#tkPriorityTag").className=`tag ${priCls(T?.prioridad)}`.trim();$("#tkTopChips").innerHTML=`<span class="tag ${stateCls(T?.estado)}">${esc(stateLabel(rawState(T?.estado)))}</span><span class="tag ${priCls(T?.prioridad)}">${esc(T?.prioridad||"media")}</span><span class="tag ${sla.cls}">${sla.txt}</span>${T?.tipo?`<span class="tag">${esc(T.tipo)}</span>`:""}`};
const renderSummary=()=>{const lines=[C?.nombre?`Cliente: ${C.nombre}`:T?.empresa_capturada?`Empresa capturada: ${T.empresa_capturada}`:"",T?.tipo?`Tipo: ${T.tipo}`:"",T?.prioridad?`Prioridad: ${T.prioridad}`:"",T?.impacto?`Impacto: ${T.impacto}`:"",T?.afecta_a?`Afecta: ${T.afecta_a}`:"",T?.desde_cuando?`Desde: ${T.desde_cuando}`:"",T?.ultimo_cambio?`Cambio previo: ${T.ultimo_cambio}`:"",T?.horario_contacto?`Horario: ${T.horario_contacto}`:"",T?.estado?`Estado: ${stateLabel(rawState(T.estado))}`:"",T?.descripcion?`Resumen: ${T.descripcion}`:"Sin descripción."].filter(Boolean);$("#tkSummary").textContent=lines.join(" · ")};
const renderEvidence=()=>{$("#tkEvidence").innerHTML=FILES.length?FILES.map((x,i)=>`<div class="item"><div><div class="item-title">${esc(x.nombre)}</div><div class="item-meta">${esc(x.tipo||"Archivo")} · ${prettyBytes(x.tamano||0)}</div></div><div class="actions"><button class="btn btn-ghost" type="button" data-ev-open="${i}">Ver</button><div class="ev-menu-wrap"><button class="btn btn-ghost" type="button" data-ev-menu="${i}">⋯</button><div class="ev-menu" id="evMenu${i}"><button class="mini btn-ghost" type="button" data-ev-copy="${i}">Copiar enlace</button><button class="mini btn-ghost" type="button" data-ev-open-new="${i}">Abrir</button><button class="mini btn-ghost" type="button" data-ev-download="${i}">Descargar</button><button class="mini btn-ghost" type="button" data-ev-close="${i}">✕</button></div></div></div></div>`).join(""):`<div class="empty-state">Aún no hay archivos del caso.</div>`};
const renderLogs=()=>{const head=`<div class="log-sys">Caso recibido · ${fmtDT(T?.fecha_creacion)}</div><div class="log-msg"><div class="log-meta"><span>Reporte inicial</span><span>${fmtHM(T?.fecha_creacion)}</span></div>${esc(T?.descripcion||"Sin descripción")}</div>`;const tail=(LOGS||[]).map(humanLog).filter(Boolean).map(x=>`<div class="log-msg ${x.side==="me"?"me":""}"><div class="log-meta"><span>${esc(x.title)}</span><span>${esc(x.time)}</span></div>${esc(x.text)}</div>`).join("");$("#logArea").innerHTML=head+tail};
const render=()=>{renderHeader();renderSummary();renderContext();renderIdentity();renderHeat();renderEvidence();renderLogs()};
const load=async()=>{await guardSession("index.html");const profile=(await s.from("perfiles").select("*").limit(1).maybeSingle()).data||{rol:"soporte"};ensureAppShell({page:"ticket",role:profile.rol||"soporte",title:"Ticket",kicker:"Expiriti · seguimiento operativo",actionsHtml:`<a class="mini btn-ghost" href="tickets.html">Volver</a><button class="mini btn-ghost" id="tkRefreshBtn" type="button">Actualizar</button><button class="mini" data-theme-toggle>🌓 <span data-theme-label>Claro</span></button>`});setAppRole(profile.rol||"soporte");if(!ID)return toast("Falta ID del ticket","bad");const tk=await s.from("tickets").select("*").eq("id",ID).single();if(tk.error||!tk.data)return toast("Ticket no encontrado","bad");T=tk.data;const since30=new Date(Date.now()-30*864e5).toISOString();const[cl,lg,heatRows,archRows]=await Promise.all([T.cliente_id?s.from("clientes").select("id,nombre").eq("id",T.cliente_id).single():Promise.resolve({data:null}),s.from("bitacora").select("*").eq("detalle->>ticket_id",String(ID)).order("fecha",{ascending:true}),T.cliente_id?s.from("tickets").select("id,prioridad,estado,fecha_creacion,fecha_actualizacion").eq("cliente_id",T.cliente_id).gte("fecha_creacion",since30):Promise.resolve({data:[]}),s.from("ticket_archivos").select("*").eq("ticket_id",ID).order("created_at",{ascending:true})]);C=cl.data||null;LOGS=lg.data||[];const hr=Array.isArray(heatRows?.data)?heatRows.data:[];HEAT.total30=hr.length;HEAT.urgent30=hr.filter(x=>norm(x.prioridad)==="urgente").length;HEAT.waitOpen=hr.filter(x=>stateKey(x.estado)==="esperando_cliente").length;HEAT.level=heatLevel(HEAT.total30+(HEAT.urgent30*2)+(HEAT.waitOpen));FILES=[...normalizeFiles(T?.adjuntos),...normalizeFiles(archRows?.data)].filter((x,i,a)=>a.findIndex(y=>String(y.storage_path||y.url||y.nombre)===String(x.storage_path||x.url||x.nombre))===i);setRailOpenCount(1);if(C?.id&&C?.nombre)pushRecentClient({id:C.id,nombre:C.nombre});setGlobalSearchData({clientes:C?[C]:[],tickets:T?[{...T,clientes:C||null}]:[]});setBreadcrumb([{label:"Panel",href:"dashboard.html"},{label:"Tickets",href:"tickets.html"},{label:T?.titulo||"Caso"}]);render()};
const saveLog=async()=>{const texto=$("#logText").value.trim(),kind=$("#logKind")?.value||"nota",nextState=$("#logState")?.value||"";if(!texto){$("#logStatus").textContent="Escribe un avance antes de guardar.";return}$("#logStatus").textContent="Guardando...";setBusy(true);const ins=await s.from("bitacora").insert({accion:`ticket_${kind}`,cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),texto,kind,estado:nextState||null},fecha:new Date().toISOString()});if(ins.error){setBusy(false);$("#logStatus").textContent=msg(ins.error);return toast(msg(ins.error),"bad")}const timeline=Array.isArray(T?.timeline_publica)?T.timeline_publica:[],publicKinds=["solicitud","solucion","seguimiento"],now=new Date().toISOString(),entry=publicKinds.includes(kind)?{titulo:publicEntryTitle(kind),texto,fecha:now}:null,payload={fecha_actualizacion:now};if(nextState)payload.estado=stateKey(nextState);if(entry)payload.timeline_publica=[...timeline,entry];const up=await s.from("tickets").update(payload).eq("id",ID).select().single();if(!up.error&&up.data)T=up.data;$("#logText").value="";$("#logState").value="";$("#logStatus").textContent="Seguimiento guardado correctamente.";setBusy(false);await load();toast("Seguimiento guardado","ok")};
const copyMagic=async()=>{const link=publicMagicLink()||ticketLink();await navigator.clipboard.writeText(link).catch(()=>{});toast(publicMagicLink()?"Enlace público copiado":"Enlace copiado","ok")};
const appendTemplate=txt=>{$("#logText").value=($("#logText").value.trim()?$("#logText").value.trim()+"\n\n":"")+txt;$("#logText").focus()};
const askXml=()=>appendTemplate("Solicitar al cliente XML / CFDI de ejemplo, captura del error y pasos exactos para reproducirlo.");
const askShot=()=>appendTemplate("Solicitar captura completa de pantalla donde se vea sistema, mensaje de error y acción realizada.");
const askRemote=()=>appendTemplate("Solicitar acceso remoto / AnyDesk / TeamViewer y confirmar horario disponible para conexión.");
const setWait=async()=>{const up=await s.from("tickets").update({estado:"esperando_cliente",fecha_actualizacion:new Date().toISOString()}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_set_wait",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"esperando_cliente"}}).catch(()=>{});await load();toast("Ticket en espera de cliente","ok")};
const setSolve=async()=>{const up=await s.from("tickets").update({estado:"resuelto",fecha_actualizacion:new Date().toISOString()}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_set_solved",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"resuelto"}}).catch(()=>{});await load();toast("Ticket marcado como resuelto","ok")};
const reopenTicket=async()=>{const up=await s.from("tickets").update({estado:"abierto",fecha_actualizacion:new Date().toISOString(),fecha_cierre:null}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_reopened",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"abierto"}}).catch(()=>{});await load();toast("Ticket reabierto","ok")};
const closeTicket=async()=>{const up=await s.from("tickets").update({estado:"cerrado",fecha_actualizacion:new Date().toISOString(),fecha_cierre:new Date().toISOString()}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_closed",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"cerrado"}}).catch(()=>{});await load();toast("Ticket cerrado","ok")};
const bind=()=>{if(document.documentElement.dataset.ticketBound)return;document.documentElement.dataset.ticketBound="1";$("#saveLogBtn").onclick=saveLog;$("#copyMagicBtn").onclick=copyMagic;$("#askXmlBtn").onclick=askXml;$("#askShotBtn").onclick=askShot;$("#askRemoteBtn").onclick=askRemote;$("#setWaitBtn").onclick=setWait;$("#setSolveBtn").onclick=setSolve;$("#reopenBtn").onclick=reopenTicket;$("#closeBtn").onclick=closeTicket;$("#tkUseSuggestedClientBtn")&&($("#tkUseSuggestedClientBtn").onclick=useSuggestedClient);$("#tkMarkNewContactBtn")&&($("#tkMarkNewContactBtn").onclick=markNewContact);$("#tkMarkConsolidatedBtn")&&($("#tkMarkConsolidatedBtn").onclick=markConsolidated);$("#quickReplyBtn")&&($("#quickReplyBtn").onclick=qrToggle);$("#evClose")&&($("#evClose").onclick=hideEv);document.addEventListener("click",async e=>{const b=e.target.closest("#tkRefreshBtn");if(b)return load().catch(err=>toast(msg(err),"bad"));const q=e.target.closest("[data-qr]");if(q)return applyQuickReply(q.dataset.qr);const m=e.target.closest("[data-ev-menu]");if(m){e.preventDefault();e.stopPropagation();const box=$(`#evMenu${m.dataset.evMenu}`);closeFileMenus();return box?.classList.toggle("open")}const c=e.target.closest("[data-ev-close]");if(c){e.preventDefault();return closeFileMenus()}const o=e.target.closest("[data-ev-open]");if(o)return openEvidence(+o.dataset.evOpen);const openNew=e.target.closest("[data-ev-open-new]");if(openNew){const f=FILES[+openNew.dataset.evOpenNew],u=await signedEvidenceUrl(f);if(u)window.open(u,"_blank","noopener");closeFileMenus();return}const dl=e.target.closest("[data-ev-download]");if(dl){const f=FILES[+dl.dataset.evDownload],u=await signedEvidenceUrl(f);if(u){const a=document.createElement("a");a.href=u;a.download=f.nombre||"archivo";document.body.appendChild(a);a.click();a.remove()}closeFileMenus();return}const cp=e.target.closest("[data-ev-copy]");if(cp){const f=FILES[+cp.dataset.evCopy],u=await signedEvidenceUrl(f);if(u)await navigator.clipboard.writeText(u).catch(()=>{}),toast("Enlace copiado","ok");closeFileMenus();return}if(!e.target.closest(".ev-menu-wrap"))closeFileMenus();if(!e.target.closest("#quickReplies")&&!e.target.closest("#quickReplyBtn"))qrClose();if(e.target===document.querySelector("#evModal"))hideEv()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){qrClose();closeFileMenus();hideEv()}if((e.ctrlKey||e.metaKey)&&e.key==="/"){e.preventDefault();qrToggle()}});$("#logText")&&$("#logText").addEventListener("keydown",e=>{if(e.key==="/")setTimeout(()=>qrOpen(),0)})};
document.addEventListener("DOMContentLoaded",()=>{bind();load().catch(err=>toast(msg(err),"bad"))});
