import{supabase as s,guardSession,logAction,msg}from"./supabase.js";import{$,toast,ensureAppShell,setAppRole,setRailOpenCount,pushRecentClient,setGlobalSearchData,setBreadcrumb}from"./global.js";
const QS=new URLSearchParams(location.search),ID=QS.get("id")||"",ST={busy:false};let T=null,C=null,LOGS=[],HEAT={total30:0,urgent30:0,waitOpen:0,level:"Frío"};
const QR={
xml:{text:"Por favor, adjunta un XML / CFDI de ejemplo y, si es posible, una captura completa del mensaje de error para revisar el caso con mayor precisión.",kind:"solicitud",state:"esperando_cliente"},
captura:{text:"Por favor, comparte una captura completa de pantalla donde se vea el sistema, el mensaje de error y la acción que estabas realizando.",kind:"solicitud",state:"esperando_cliente"},
remoto:{text:"Para avanzar más rápido, comparte tu ID de acceso remoto y un horario disponible para conexión. Si aplica, indica también si debemos entrar al servidor o al equipo local.",kind:"solicitud",state:"esperando_cliente"},
horario:{text:"Compártenos por favor uno o dos horarios disponibles para revisión, y el medio preferido de contacto para continuar con el caso.",kind:"solicitud",state:"esperando_cliente"},
espera:{text:"Quedamos en espera de la información solicitada por parte del cliente para continuar con la revisión del caso.",kind:"seguimiento",state:"esperando_cliente"},
solucion:{text:"Se aplicó ajuste / validación operativa y el caso queda listo para confirmación con el cliente.",kind:"solucion",state:""},
resuelto:{text:"Se aplicó solución y el caso queda resuelto. Pendiente únicamente confirmación final del cliente si aplica.",kind:"solucion",state:"resuelto"}
};
const qrOpen=()=>{$("#quickReplies")&&( $("#quickReplies").hidden=false,$("#quickReplyBtn")?.classList.add("is-active"))};
const qrClose=()=>{$("#quickReplies")&&( $("#quickReplies").hidden=true,$("#quickReplyBtn")?.classList.remove("is-active"))};
const qrToggle=()=>$("#quickReplies")?.hidden?qrOpen():qrClose();
const applyQuickReply=k=>{const q=QR[k];if(!q)return;const box=$("#logText"),kind=$("#logKind"),state=$("#logState");if(box)box.value=(box.value.trim()?`${box.value.trim()}\n\n`:"")+q.text;if(kind&&q.kind)kind.value=q.kind;if(state&&q.state!==undefined)state.value=q.state;qrClose();box?.focus()};
const fileExt=n=>((n||"").split(".").pop()||"").toLowerCase(),isImg=x=>["jpg","jpeg","png","webp","gif","bmp","svg"].includes(fileExt(x?.nombre||x?.name||x?.url||""))||String(x?.tipo||x?.type||"").startsWith("image/"),isPdf=x=>fileExt(x?.nombre||x?.name||x?.url||"")==="pdf"||String(x?.tipo||x?.type||"").toLowerCase()==="application/pdf",isText=x=>["xml","txt","json","log","csv"].includes(fileExt(x?.nombre||x?.name||x?.url||""))||["text/plain","text/xml","application/xml","application/json","text/csv"].includes(String(x?.tipo||x?.type||"").toLowerCase()),safeUrl=u=>{try{return /^https?:\/\//i.test(String(u||""))?u:""}catch{return""}},showEv=()=>{$("#evModal")&&( $("#evModal").hidden=false,document.body.classList.add("modal-open"))},hideEv=()=>{$("#evModal")&&( $("#evModal").hidden=true,document.body.classList.remove("modal-open"));$("#evBody")&&($("#evBody").innerHTML=`<div class="empty-state">Sin vista previa.</div>`);$("#evTitle")&&($("#evTitle").textContent="Vista previa");$("#evOpenRaw")&&($("#evOpenRaw").setAttribute("href","#"))};
const escHtml=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const openEvidence=async i=>{const files=Array.isArray(T?.adjuntos)?T.adjuntos:[],x=files[i];if(!x)return;const u=safeUrl(x?.url),name=x?.nombre||x?.name||`Adjunto ${Number(i)+1}`;$("#evTitle")&&($("#evTitle").textContent=name);$("#evOpenRaw")&&($("#evOpenRaw").setAttribute("href",u||"#"));if(!u){$("#evBody").innerHTML=`<div class="empty-state">Este adjunto no tiene URL pública para vista previa.</div>`;return showEv()}if(isImg(x)){$("#evBody").innerHTML=`<img class="ev-img" src="${esc(u)}" alt="${esc(name)}">`;return showEv()}if(isPdf(x)){$("#evBody").innerHTML=`<iframe class="ev-frame" src="${esc(u)}" title="${esc(name)}"></iframe>`;return showEv()}if(isText(x)){try{const r=await fetch(u),txt=await r.text();$("#evBody").innerHTML=`<pre class="ev-pre">${escHtml(txt.slice(0,120000))}</pre>`;showEv()}catch{$("#evBody").innerHTML=`<div class="empty-state">No se pudo leer este archivo en vista previa.</div>`;showEv()}return}window.open(u,"_blank","noopener")};
const fmtDT=v=>v?new Date(v).toLocaleString("es-MX"):"—",fmtHM=v=>v?new Date(v).toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"}):"",esc=v=>(v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),norm=v=>(v||"").toString().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim();
const rawState=v=>v||"abierto",priCls=v=>{const x=norm(v);return x==="urgente"?"bad":x==="alta"?"warn":x==="media"?"info":"ok"},stateKey=v=>{const x=norm(v);if(["abierto","nuevo"].includes(x))return"abierto";if(["en_proceso","en proceso","proceso"].includes(x))return"en_proceso";if(["esperando_cliente","esperando cliente","espera"].includes(x))return"esperando_cliente";if(["resuelto"].includes(x))return"resuelto";if(["cerrado","closed","done","cancelado"].includes(x))return"cerrado";return"abierto"},stateLabel=v=>stateKey(v)==="en_proceso"?"En proceso":stateKey(v)==="esperando_cliente"?"Esperando cliente":stateKey(v)==="resuelto"?"Resuelto":stateKey(v)==="cerrado"?"Cerrado":"Abierto",stateCls=v=>{const x=stateKey(v);return x==="resuelto"||x==="cerrado"?"ok":x==="esperando_cliente"?"warn":x==="en_proceso"?"info":"neutral"},logText=x=>x?.detalle?.texto||x?.detalle?.nota||x?.detalle?.mensaje||JSON.stringify(x?.detalle||{}),ticketLink=()=>`${location.origin}${location.pathname}?id=${encodeURIComponent(ID)}`;
const setBusy=v=>{ST.busy=!!v;$("#saveLogBtn")&&($("#saveLogBtn").disabled=ST.busy);$("#tkRefreshBtn")&&($("#tkRefreshBtn").disabled=ST.busy);$("#copyMagicBtn")&&($("#copyMagicBtn").disabled=ST.busy);$("#askXmlBtn")&&($("#askXmlBtn").disabled=ST.busy);$("#askShotBtn")&&($("#askShotBtn").disabled=ST.busy);$("#askRemoteBtn")&&($("#askRemoteBtn").disabled=ST.busy);$("#setWaitBtn")&&($("#setWaitBtn").disabled=ST.busy);$("#setSolveBtn")&&($("#setSolveBtn").disabled=ST.busy);$("#reopenBtn")&&($("#reopenBtn").disabled=ST.busy);$("#closeBtn")&&($("#closeBtn").disabled=ST.busy)};
const nextStep=t=>{const s=stateKey(t?.estado),d=norm(`${t?.titulo||""} ${t?.descripcion||""}`);if(s==="esperando_cliente")return"Esperar respuesta del cliente";if(s==="resuelto")return"Cerrar al confirmar";if(d.includes("xml"))return"Pedir XML";if(d.includes("captura")||d.includes("pantalla"))return"Revisar evidencia";if(d.includes("remoto")||d.includes("anydesk")||d.includes("teamviewer"))return"Coordinar acceso remoto";return s==="abierto"?"Hacer triage":"Dar seguimiento"};
const renderContext=()=>{$("#tkImpact").textContent=T?.impacto||T?.impact||"—";$("#tkAffected").textContent=T?.afecta_a||T?.afectados||"—";$("#tkSince").textContent=T?.desde_cuando||T?.since||"—";$("#tkNext").textContent=nextStep(T);$("#tkLastChange").textContent=T?.ultimo_cambio||"—";$("#tkAvailability").textContent=T?.horario_contacto||"—"};
const heatLevel=x=>x>=6?"🔥 Caliente":x>=3?"🟠 Sensible":"🟢 Estable";
const renderHeat=()=>{$("#tkHeatTotal").textContent=HEAT.total30;$("#tkHeatUrgent").textContent=HEAT.urgent30;$("#tkHeatWait").textContent=HEAT.waitOpen;$("#tkHeatLevel").textContent=HEAT.level;$("#tkHeatChips").innerHTML=`<span class="tag ${HEAT.total30>=6?"bad":HEAT.total30>=3?"warn":"ok"}">${HEAT.level}</span>${HEAT.total30?`<span class="tag">${HEAT.total30} tickets en 30d</span>`:""}${HEAT.urgent30?`<span class="tag warn">${HEAT.urgent30} urgentes</span>`:""}${HEAT.waitOpen?`<span class="tag info">${HEAT.waitOpen} en espera</span>`:""}${!HEAT.total30&&!HEAT.urgent30&&!HEAT.waitOpen?`<span class="tag">Sin señales recientes</span>`:""}`};

const renderHeader=()=>{$("#tkTitle").textContent=T?.titulo||"Ticket";$("#tkClient").textContent=C?.nombre||"—";$("#tkSystem").textContent=T?.tipo||"—";$("#tkState").textContent=stateLabel(rawState(T?.estado));$("#tkPriority").textContent=T?.prioridad||"—";$("#tkCreated").textContent=fmtDT(T?.fecha_creacion);$("#tkId").textContent=ID||"—";$("#tkStateTag").textContent=stateLabel(rawState(T?.estado));$("#tkPriorityTag").textContent=T?.prioridad||"—";$("#tkStateTag").className=`tag ${stateCls(T?.estado)}`.trim();$("#tkPriorityTag").className=`tag ${priCls(T?.prioridad)}`.trim();$("#tkTopChips").innerHTML=`<span class="tag ${stateCls(T?.estado)}">${esc(stateLabel(rawState(T?.estado)))}</span><span class="tag ${priCls(T?.prioridad)}">${esc(T?.prioridad||"media")}</span>${T?.tipo?`<span class="tag">${esc(T.tipo)}</span>`:""}`};
const renderSummary=()=>{const lines=[C?.nombre?`Cliente: ${C.nombre}`:"",T?.tipo?`Tipo: ${T.tipo}`:"",T?.prioridad?`Prioridad: ${T.prioridad}`:"",T?.impacto?`Impacto: ${T.impacto}`:"",T?.afecta_a?`Afecta: ${T.afecta_a}`:"",T?.desde_cuando?`Desde cuándo: ${T.desde_cuando}`:"",T?.ultimo_cambio?`Último cambio: ${T.ultimo_cambio}`:"",T?.horario_contacto?`Horario: ${T.horario_contacto}`:"",T?.estado?`Estado actual: ${stateLabel(rawState(T.estado))}`:"",T?.descripcion?`Caso: ${T.descripcion}`:"Sin descripción."].filter(Boolean);$("#tkSummary").textContent=lines.join(" · ")};
const renderEvidence=()=>{const files=Array.isArray(T?.adjuntos)?T.adjuntos:[];$("#tkEvidence").innerHTML=files.length?files.map((x,i)=>{const previewable=!!safeUrl(x?.url)&&(isImg(x)||isPdf(x)||isText(x));return`<div class="item"><div class="item-title">${esc(x?.nombre||x?.name||`Adjunto ${i+1}`)}</div><div class="item-meta">${esc(x?.tipo||x?.type||"Archivo")}</div><div class="actions">${previewable?`<button class="btn btn-ghost" type="button" data-ev-open="${i}">Ver aquí</button>`:""}${x?.url?`<a class="btn btn-ghost" href="${esc(x.url)}" target="_blank" rel="noopener">Abrir</a>`:""}</div></div>`}).join(""):`<div class="empty-state">Aún no hay evidencia adjunta.</div>`};
const renderLogs=()=>{const head=`<div class="log-sys">Ticket creado · ${fmtDT(T?.fecha_creacion)}</div><div class="log-msg"><div class="log-meta"><span>Reporte inicial</span><span>${fmtHM(T?.fecha_creacion)}</span></div>${esc(T?.descripcion||"Sin descripción")}</div>`;const tail=(LOGS||[]).map(x=>`<div class="log-msg me"><div class="log-meta"><span>${esc(x.accion||"Log")}</span><span>${fmtHM(x.fecha||x.fecha_creacion)}</span></div>${esc(logText(x))}</div>`).join("");$("#logArea").innerHTML=head+tail};
const render=()=>{renderHeader();renderSummary();renderContext();renderHeat();renderEvidence();renderLogs()};
const load=async()=>{await guardSession("index.html");const profile=(await s.from("perfiles").select("*").limit(1).maybeSingle()).data||{rol:"soporte"};ensureAppShell({page:"ticket",role:profile.rol||"soporte",title:"Ticket",kicker:"Expiriti · seguimiento operativo",actionsHtml:`<a class="mini btn-ghost" href="tickets.html">Volver</a><button class="mini btn-ghost" id="tkRefreshBtn" type="button">Actualizar</button><button class="mini" data-theme-toggle>🌓 <span data-theme-label>Claro</span></button>`});setAppRole(profile.rol||"soporte");if(!ID)return toast("Falta ID del ticket","bad");const tk=await s.from("tickets").select("*").eq("id",ID).single();if(tk.error||!tk.data)return toast("Ticket no encontrado","bad");T=tk.data;const since30=new Date(Date.now()-30*864e5).toISOString(); const[cl,lg,heatRows]=await Promise.all([T.cliente_id?s.from("clientes").select("id,nombre").eq("id",T.cliente_id).single():Promise.resolve({data:null}),s.from("bitacora").select("*").eq("detalle->>ticket_id",String(ID)).order("fecha",{ascending:true}),T.cliente_id?s.from("tickets").select("id,prioridad,estado,fecha_creacion,fecha_actualizacion").eq("cliente_id",T.cliente_id).gte("fecha_creacion",since30):Promise.resolve({data:[]})]);C=cl.data||null;LOGS=lg.data||[];const hr=heatRows?.data||[];HEAT.total30=hr.length;HEAT.urgent30=hr.filter(x=>norm(x.prioridad)==="urgente").length;HEAT.waitOpen=hr.filter(x=>stateKey(x.estado)==="esperando_cliente").length;HEAT.level=heatLevel(HEAT.total30+(HEAT.urgent30*2)+(HEAT.waitOpen));setRailOpenCount(1);if(C?.id&&C?.nombre)pushRecentClient({id:C.id,nombre:C.nombre});setGlobalSearchData({clientes:C?[C]:[],tickets:T?[{...T,clientes:C||null}]:[]});setBreadcrumb([{label:"Panel",href:"dashboard.html"},{label:"Tickets",href:"tickets.html"},{label:T?.titulo||"Ticket"}]);render()};
const saveLog=async()=>{const texto=$("#logText").value.trim(),kind=$("#logKind")?.value||"nota",nextState=$("#logState")?.value||"";if(!texto){$("#logStatus").textContent="Escribe una nota antes de guardar.";return}$("#logStatus").textContent="Guardando...";setBusy(true);const ins=await s.from("bitacora").insert({accion:`ticket_${kind}`,cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),texto,kind,estado:nextState||null},fecha:new Date().toISOString()});if(ins.error){setBusy(false);$("#logStatus").textContent=msg(ins.error);return toast(msg(ins.error),"bad")}if(nextState){const up=await s.from("tickets").update({estado:stateKey(nextState),fecha_actualizacion:new Date().toISOString()}).eq("id",ID).select().single();if(!up.error&&up.data)T=up.data}await logAction({accion:"ticket_log",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),kind,estado:nextState?stateKey(nextState):null}}).catch(()=>{});$("#logText").value="";$("#logState").value="";$("#logStatus").textContent="Log guardado correctamente.";setBusy(false);await load();toast("Log guardado","ok")};
const copyMagic=async()=>{await navigator.clipboard.writeText(ticketLink()).catch(()=>{});toast("Enlace copiado","ok")};
const appendTemplate=txt=>{$("#logText").value=($("#logText").value.trim()?$("#logText").value.trim()+"\n\n":"")+txt;$("#logText").focus()};
const askXml=()=>appendTemplate("Solicitar al cliente XML / CFDI de ejemplo, captura del error y pasos exactos para reproducirlo.");
const askShot=()=>appendTemplate("Solicitar captura completa de pantalla donde se vea sistema, mensaje de error y acción realizada.");
const askRemote=()=>appendTemplate("Solicitar acceso remoto / AnyDesk / TeamViewer y confirmar horario disponible para conexión.");
const setWait=async()=>{const up=await s.from("tickets").update({estado:"esperando_cliente",fecha_actualizacion:new Date().toISOString()}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_set_wait",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"esperando_cliente"}}).catch(()=>{});await load();toast("Ticket en espera de cliente","ok")};
const setSolve=async()=>{const up=await s.from("tickets").update({estado:"resuelto",fecha_actualizacion:new Date().toISOString()}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_set_solved",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"resuelto"}}).catch(()=>{});await load();toast("Ticket marcado como resuelto","ok")};
const reopenTicket=async()=>{const up=await s.from("tickets").update({estado:"abierto",fecha_actualizacion:new Date().toISOString(),fecha_cierre:null}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_reopened",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"abierto"}}).catch(()=>{});await load();toast("Ticket reabierto","ok")};
const closeTicket=async()=>{const up=await s.from("tickets").update({estado:"cerrado",fecha_actualizacion:new Date().toISOString(),fecha_cierre:new Date().toISOString()}).eq("id",ID).select().single();if(up.error)return toast(msg(up.error),"bad");T=up.data;await logAction({accion:"ticket_closed",cliente_id:T?.cliente_id||null,detalle:{ticket_id:String(ID),estado:"cerrado"}}).catch(()=>{});await load();toast("Ticket cerrado","ok")};
const bind=()=>{if(document.documentElement.dataset.ticketBound)return;document.documentElement.dataset.ticketBound="1";$("#saveLogBtn").onclick=saveLog;$("#copyMagicBtn").onclick=copyMagic;$("#askXmlBtn").onclick=askXml;$("#askShotBtn").onclick=askShot;$("#askRemoteBtn").onclick=askRemote;$("#setWaitBtn").onclick=setWait;$("#setSolveBtn").onclick=setSolve;$("#reopenBtn").onclick=reopenTicket;$("#closeBtn").onclick=closeTicket;$("#quickReplyBtn")&&($("#quickReplyBtn").onclick=qrToggle);document.addEventListener("click",e=>{const b=e.target.closest("#tkRefreshBtn");if(b)return load().catch(err=>toast(msg(err),"bad"));const q=e.target.closest("[data-qr]");if(q)return applyQuickReply(q.dataset.qr);if(!e.target.closest("#quickReplies")&&!e.target.closest("#quickReplyBtn"))qrClose()});document.addEventListener("keydown",e=>{if(e.key==="Escape")qrClose();if((e.ctrlKey||e.metaKey)&&e.key==="/"){e.preventDefault();qrToggle()}});$("#logText")&&$("#logText").addEventListener("keydown",e=>{if(e.key==="/")setTimeout(()=>qrOpen(),0)})};
document.addEventListener("DOMContentLoaded",()=>{bind();load().catch(err=>toast(msg(err),"bad"))});
