import{supabase as s,guardSession,msg}from"./supabase.js";
import{$,$$,toast,debounce,show,hide,bindModal,norm,ensureAppShell,setAppRole,setRailOpenCount,setGlobalSearchData,setBreadcrumb,fmtDT,daysSince,ticketStateKey,ticketStateLabel,ticketPriorityCls}from"./global.js";
let TK=[],FILTER={q:"",priority:"",state:"",type:"",client:"",clienteId:"",noEvidence:false,readyClose:false,impactHigh:false,urgentStale:false,needsIdentity:false,noClientLinked:false,matchMedium:false,frBreach:false,rsBreach:false,slaSoon:false},VIEW=localStorage.getItem("expiriti_tickets_view")||"kanban",SELECTED_ID="",EDIT_MODE=localStorage.getItem("expiriti_tickets_edit_mode")==="1",DRAG_COL=null,FOCUS_ON=localStorage.getItem("expiriti_focus_mode")==="1",FOCUS_INDEX=0,BOARD_NOTIF=JSON.parse(localStorage.getItem("expiriti_tickets_notif")||'{"visual":true,"sound":true,"strongOnly":false,"volume":0.5,"muted":false}');
$("#metricUrgent")?.addEventListener("click",()=>{$("#tkFilterPriority").value="urgente";applyFilters()});$("#metricWait")?.addEventListener("click",()=>{$("#tkFilterState").value="esperando_cliente";applyFilters()});$("#metricStale")?.addEventListener("click",()=>{FILTER.urgentStale=!FILTER.urgentStale;syncFilterUI();renderAll()});$("#metricSolved")?.addEventListener("click",()=>{$("#tkFilterState").value="resuelto";applyFilters()});$("#metricIdentity")?.addEventListener("click",()=>{FILTER.needsIdentity=true;syncFilterUI();renderAll()});$("#metricNoClient")?.addEventListener("click",()=>{FILTER.noClientLinked=true;syncFilterUI();renderAll()});$("#metricFrBreach")?.addEventListener("click",()=>{FILTER.frBreach=true;syncFilterUI();renderAll()});$("#metricRsBreach")?.addEventListener("click",()=>{FILTER.rsBreach=true;syncFilterUI();renderAll()});$("#metricSlaSoon")?.addEventListener("click",()=>{FILTER.slaSoon=true;syncFilterUI();renderAll()});setKpiExpanded(KPI_EXPANDED());setKpiExpanded(KPI_EXPANDED());
const saveBoardNotif=()=>localStorage.setItem("expiriti_tickets_notif",JSON.stringify(BOARD_NOTIF));
const syncBoardNotifUI=()=>{$("#tkNotifVisual")&&($("#tkNotifVisual").checked=!!BOARD_NOTIF.visual);$("#tkNotifSound")&&($("#tkNotifSound").checked=!!BOARD_NOTIF.sound);$("#tkNotifStrongOnly")&&($("#tkNotifStrongOnly").checked=!!BOARD_NOTIF.strongOnly);$("#tkNotifVolume")&&($("#tkNotifVolume").value=String(Number(BOARD_NOTIF.volume??0.5)))};


const rawState=t=>t?.estado||t?.estatus||t?.status||"abierto";
const staleCls=t=>daysSince(t.fecha_actualizacion||t.fecha_creacion)>=1&&!["resuelto","cerrado"].includes(ticketStateKey(rawState(t)))?"is-stale":"";
const isCritical=t=>norm(t.prioridad)==="urgente"||daysSince(t.fecha_actualizacion||t.fecha_creacion)>=3&&!["resuelto","cerrado"].includes(ticketStateKey(rawState(t)));
const evidenceCount=t=>Array.isArray(t?.adjuntos)?t.adjuntos.length:Number(t?.evidencia_count||t?.attachments_count||t?.files_count||0)||0;
const impactKey=t=>{const x=norm(t?.impacto||t?.impact||"");return x==="alta"?"alta":x==="media"?"media":x==="baja"?"baja":x==="preventiva"?"preventiva":""};
const normTipo=v=>{const x=norm(v||"");return x==="renovacion"?"renovacion":"soporte"};
const needsIdentity=t=>!!t?.requiere_consolidacion;
const noClientLinked=t=>!t?.cliente_id;
const hasLinkedContact=t=>!!t?.cliente_id&&!!t?.contacto_id;
const noLinkedContact=t=>!!t?.cliente_id&&!t?.contacto_id;
const existingClientPending=t=>!!t?.cliente_id&&!!t?.requiere_consolidacion;
const matchLevel=t=>norm(t?.match_nivel||"");
const consolidated=t=>!!t?.cliente_id&&!t?.requiere_consolidacion;

const nextAction=t=>{const s=ticketStateKey(rawState(t)),d=norm(`${t?.titulo||""} ${t?.descripcion||""}`);if(s==="esperando_cliente")return"Esperar respuesta o archivo";if(s==="resuelto")return"Listo para cierre";if(d.includes("xml"))return"Pedir archivo de ejemplo";if(d.includes("captura")||d.includes("pantalla"))return"Revisar imagen o evidencia";if(d.includes("remoto")||d.includes("anydesk")||d.includes("teamviewer"))return"Coordinar acceso remoto";if(s==="abierto")return"Primera revisión";return"Dar seguimiento"};
const readyToClose=t=>ticketStateKey(rawState(t))==="resuelto"; const slaPack=p=>{const x=norm(p||"media");if(x==="urgente")return{policy:"urgent_2h_8h",fr:2,res:8};if(x==="alta")return{policy:"high_4h_24h",fr:4,res:24};if(x==="media")return{policy:"medium_8h_48h",fr:8,res:48};return{policy:"low_24h_72h",fr:24,res:72}};
const healthTag=t=>{const s=ticketStateKey(rawState(t)),stale=daysSince(t.fecha_actualizacion||t.fecha_creacion),ev=evidenceCount(t),impact=impactKey(t);if(readyToClose(t))return{txt:"Listo para concluir",cls:"ok"};if(s==="esperando_cliente")return{txt:"Esperando respuesta",cls:"warn"};if(norm(t.prioridad)==="urgente"||impact==="alta"||stale>=3)return{txt:"Atención prioritaria",cls:"bad"};if(!ev)return{txt:"Falta información",cls:"warn"};return{txt:"En buen curso",cls:"info"}};
const slaMeta=t=>{const now=Date.now(),fr=t?.sla_first_response_deadline?new Date(t.sla_first_response_deadline).getTime():0,rs=t?.sla_resolution_deadline?new Date(t.sla_resolution_deadline).getTime():0,frDone=!!t?.primera_respuesta_en,frLeft=fr?fr-now:null,rsLeft=rs?rs-now:null;if(!fr&&!rs)return{cls:"",txt:"Sin SLA"};if(!frDone&&t?.sla_breached_first_response)return{cls:"bad",txt:"1ra resp. vencida"};if(ticketStateKey(rawState(t))!=="resuelto"&&ticketStateKey(rawState(t))!=="cerrado"&&t?.sla_breached_resolution)return{cls:"bad",txt:"Resolución vencida"};if(!frDone&&frLeft!==null){const h=Math.max(0,Math.round(frLeft/36e5));return frLeft<=2*36e5?{cls:"warn",txt:`1ra resp. ${h}h`}:{cls:"ok",txt:`1ra resp. ${h}h`}}if(rsLeft!==null&&ticketStateKey(rawState(t))!=="resuelto"&&ticketStateKey(rawState(t))!=="cerrado"){const h=Math.max(0,Math.round(rsLeft/36e5));return rsLeft<=4*36e5?{cls:"warn",txt:`Resol. ${h}h`}:{cls:"ok",txt:`Resol. ${h}h`}}return{cls:"ok",txt:"SLA OK"}};
const slaFrBreached=t=>!t?.primera_respuesta_en&&!!t?.sla_breached_first_response;
const slaRsBreached=t=>ticketStateKey(rawState(t))!=="resuelto"&&ticketStateKey(rawState(t))!=="cerrado"&&!!t?.sla_breached_resolution;
const slaSoon=t=>{const now=Date.now(),fr=t?.sla_first_response_deadline?new Date(t.sla_first_response_deadline).getTime():0,rs=t?.sla_resolution_deadline?new Date(t.sla_resolution_deadline).getTime():0,frDone=!!t?.primera_respuesta_en,frLeft=fr?fr-now:null,rsLeft=rs?rs-now:null;if(!frDone&&frLeft!==null&&frLeft>0&&frLeft<=2*36e5)return true;if(ticketStateKey(rawState(t))!=="resuelto"&&ticketStateKey(rawState(t))!=="cerrado"&&rsLeft!==null&&rsLeft>0&&rsLeft<=4*36e5)return true;return false};
const triageScore=t=>{const s=ticketStateKey(rawState(t)),p=norm(t?.prioridad),impact=impactKey(t),stale=daysSince(t?.fecha_actualizacion||t?.fecha_creacion),ev=evidenceCount(t),now=Date.now(),fr=t?.sla_first_response_deadline?new Date(t.sla_first_response_deadline).getTime()-now:null,rs=t?.sla_resolution_deadline?new Date(t.sla_resolution_deadline).getTime()-now:null,frDone=!!t?.primera_respuesta_en;let n=0;if(s==="abierto")n+=40;if(s==="en_proceso")n+=28;if(s==="esperando_cliente")n+=14;if(s==="resuelto")n+=4;if(p==="urgente")n+=40;else if(p==="alta")n+=26;else if(p==="media")n+=12;else n+=4;if(impact==="alta")n+=24;else if(impact==="media")n+=10;else if(impact==="baja")n+=4;if(stale>=3)n+=26;else if(stale>=1)n+=12;if(ev===0)n+=10;else if(ev>=1)n-=2;if(!frDone&&t?.sla_breached_first_response)n+=34;else if(!frDone&&fr!==null&&fr<=2*36e5)n+=20;if(t?.sla_breached_resolution)n+=30;else if(rs!==null&&rs<=4*36e5&&s!=="resuelto"&&s!=="cerrado")n+=18;if(s==="cerrado")n=-999;return n};
const randToken=()=>crypto.randomUUID().replace(/-/g,"")+crypto.randomUUID().replace(/-/g,"");
const nextFolioSimple=async()=>{const{count,error}=await s.from("tickets").select("*",{count:"exact",head:true});if(error)throw error;return`SP-${Number(count||0)+1}`};
const qp=k=>new URLSearchParams(location.search).get(k)||"";
const resetFilters=()=>FILTER={q:"",priority:"",state:"",type:"",client:"",clienteId:"",noEvidence:false,readyClose:false,impactHigh:false,urgentStale:false,needsIdentity:false,noClientLinked:false,matchMedium:false,frBreach:false,rsBreach:false,slaSoon:false};
const syncFilterUI=()=>{$("#tkSearch")&&($("#tkSearch").value=FILTER.q||"");$("#tkFilterPriority")&&($("#tkFilterPriority").value=FILTER.priority||"");$("#tkFilterState")&&($("#tkFilterState").value=FILTER.state||"");$("#tkFilterType")&&($("#tkFilterType").value=FILTER.type||"");$("#tkFilterClient")&&($("#tkFilterClient").value=FILTER.client||"");["tkNoEvidence","tkReadyClose","tkImpactHigh","tkUrgentStale","tkNeedsIdentity","tkNoClientLinked","tkMatchMedium","tkFrBreach","tkRsBreach","tkSlaSoon"].forEach(id=>$("#"+id)?.classList.toggle("btn-brand",id==="tkNoEvidence"?FILTER.noEvidence:id==="tkReadyClose"?FILTER.readyClose:id==="tkImpactHigh"?FILTER.impactHigh:id==="tkUrgentStale"?FILTER.urgentStale:id==="tkNeedsIdentity"?FILTER.needsIdentity:id==="tkNoClientLinked"?FILTER.noClientLinked:id==="tkMatchMedium"?FILTER.matchMedium:id==="tkFrBreach"?FILTER.frBreach:id==="tkRsBreach"?FILTER.rsBreach:FILTER.slaSoon));$("#metricUrgent")?.classList.toggle("is-active",FILTER.priority==="urgente");$("#metricWait")?.classList.toggle("is-active",FILTER.state==="esperando_cliente");$("#metricStale")?.classList.toggle("is-active",FILTER.urgentStale===true);$("#metricSolved")?.classList.toggle("is-active",FILTER.state==="resuelto");$("#metricIdentity")?.classList.toggle("is-active",FILTER.needsIdentity===true);$("#metricNoClient")?.classList.toggle("is-active",FILTER.noClientLinked===true);$("#metricFrBreach")?.classList.toggle("is-active",FILTER.frBreach===true);$("#metricRsBreach")?.classList.toggle("is-active",FILTER.rsBreach===true);$("#metricSlaSoon")?.classList.toggle("is-active",FILTER.slaSoon===true)};
const applyUrlFilters=()=>{resetFilters();const view=qp("view"),state=qp("state"),priority=qp("priority"),clienteId=qp("cliente_id"),type=qp("type"),q=qp("q"),needsIdentityParam=qp("needsIdentity"),noClient=qp("noClient"),match=qp("match");if(q)FILTER.q=q;if(view==="identity_pending")FILTER.needsIdentity=true;if(view==="open")FILTER.state="";if(view==="waiting_client")FILTER.state="esperando_cliente";if(view==="urgent")FILTER.priority="urgente";if(state)FILTER.state=state;if(priority)FILTER.priority=priority;if(type)FILTER.type=type;if(clienteId){FILTER.clienteId=String(clienteId);const t=TK.find(x=>String(x?.cliente_id)===String(clienteId));FILTER.client=t?.clientes?.nombre||""}if(needsIdentityParam==="1")FILTER.needsIdentity=true;if(noClient==="1")FILTER.noClientLinked=true;if(match==="medio")FILTER.matchMedium=true;syncFilterUI()};
const ticketBlob=t=>norm([t.titulo,t.descripcion,t.tipo,t.prioridad,t.estado,t.clientes?.nombre].join(" | "));
const byId=id=>TK.find(x=>String(x.id)===String(id));
const board=$("#tkBoard");
const setEditMode=v=>{EDIT_MODE=!!v;localStorage.setItem("expiriti_tickets_edit_mode",EDIT_MODE?"1":"0");document.body.classList.toggle("view-edit-mode",EDIT_MODE);$("#tkEditBtn")?.classList.toggle("is-active",EDIT_MODE);$("#tkEditHelp")?.classList.toggle("hidden",!EDIT_MODE);$$(".kanban-col").forEach(col=>col.draggable=EDIT_MODE)};
const boardOrder=()=>$$(".kanban-board .kanban-col").map(col=>col.querySelector(".col-body")?.id||"");
const saveBoardOrder=()=>localStorage.setItem("expiriti_tickets_col_order",JSON.stringify(boardOrder()));
 
const KPI_EXPANDED=()=>localStorage.getItem("expiriti_tickets_kpi_more")==="1";
const setKpiExpanded=v=>{localStorage.setItem("expiriti_tickets_kpi_more",v?"1":"0");$("#tkMetricsExtra")?.classList.toggle("hidden",!v);$("#tkMetricsMoreBtn")?.classList.toggle("hidden",v);$("#tkMetricsLessBtn")?.classList.toggle("hidden",!v);$("#tkMetricsMoreBtn")?.setAttribute("aria-expanded",v?"true":"false");$("#tkMetricsLessBtn")?.setAttribute("aria-expanded",v?"true":"false")};

const focusRows=()=>filtered().filter(t=>!["cerrado"].includes(ticketStateKey(rawState(t)))).sort((a,b)=>triageScore(b)-triageScore(a)||new Date(b.fecha_actualizacion||b.fecha_creacion)-new Date(a.fecha_actualizacion||a.fecha_creacion));
const focusCurrent=()=>focusRows()[FOCUS_INDEX]||focusRows()[0]||null;
const setFocusMode=v=>{FOCUS_ON=!!v;localStorage.setItem("expiriti_focus_mode",FOCUS_ON?"1":"0");document.body.classList.toggle("focus-mode",FOCUS_ON);$("#tkFocusBtn")&&($("#tkFocusBtn").textContent=FOCUS_ON?"Salir foco":"Modo foco");if(FOCUS_ON)renderFocus();else{$("#tkFocusPanel")?.classList.add("hidden");if(VIEW==="compact"){$("#tkCompact")?.classList.remove("hidden");$("#tkBoard")?.classList.add("hidden")}else{$("#tkBoard")?.classList.remove("hidden");$("#tkCompact")?.classList.add("hidden")}}};
const renderFocus=()=>{const t=focusCurrent();$("#tkFocusPanel")?.classList.remove("hidden");$("#tkBoard")?.classList.add("hidden");$("#tkCompact")?.classList.add("hidden");if(!t){$("#fkTitle").textContent="Sin casos por atender";$("#fkMeta").innerHTML=`<span class="tag ok">Todo en orden</span>`;$("#fkDesc").textContent="No hay casos abiertos que necesiten atención inmediata con los filtros actuales.";$("#fkClient").textContent="—";$("#fkSystem").textContent="—";$("#fkState").textContent="—";$("#fkPriority").textContent="—";$("#fkImpact").textContent="—";$("#fkAction").textContent="—";$("#fkSummary").textContent="No hay pendientes relevantes.";$("#fkOpen").href="javascript:void(0)";return}const ev=evidenceCount(t),stale=daysSince(t.fecha_actualizacion||t.fecha_creacion),health=healthTag(t),sla=slaMeta(t),reasons=[];if(t?.sla_breached_first_response)reasons.push("primera respuesta vencida");if(t?.sla_breached_resolution)reasons.push("resolución vencida");if(norm(t?.prioridad)==="urgente")reasons.push("prioridad urgente");if(impactKey(t)==="alta")reasons.push("impacto alto");if(stale>=1&&!["resuelto","cerrado"].includes(ticketStateKey(rawState(t))))reasons.push(`sin avance ${stale}d`);if(!ev)reasons.push("sin evidencia");$("#fkTitle").textContent=t.titulo||"Sin título";$("#fkMeta").innerHTML=`<span class="tag ${ticketPriorityCls(t.prioridad)}">${t.prioridad||"media"}</span><span class="tag ${health.cls}">${health.txt}</span><span class="tag ${sla.cls}">${sla.txt}</span><span class="tag">${ticketStateLabel(rawState(t))}</span>${stale>=1&&!["resuelto","cerrado"].includes(ticketStateKey(rawState(t)))?`<span class="tag warn">Sin avance ${stale}d</span>`:""}<span class="tag">${ev?`${ev} archivo${ev>1?"s":""}`:"Sin archivos"}</span>`;$("#fkDesc").textContent=`Este caso salió primero por: ${reasons.length?reasons.join(", "):"prioridad operativa general"}.`;$("#fkClient").textContent=t.clientes?.nombre||"—";$("#fkSystem").textContent=normTipo(t.tipo)==="renovacion"?"Renovación":"Soporte";$("#fkState").textContent=ticketStateLabel(rawState(t));$("#fkPriority").textContent=t.prioridad||"—";$("#fkImpact").textContent=t.impacto||t.impact||"—";$("#fkAction").textContent=nextAction(t);$("#fkSummary").textContent=t.descripcion||"Sin descripción.";$("#fkOpen").href=`ticket.html?id=${t.id}`};
const focusNext=()=>{const rows=focusRows();if(!rows.length)return renderFocus();FOCUS_INDEX=(FOCUS_INDEX+1)%rows.length;renderFocus()};
const openCount=arr=>(arr||[]).filter(t=>!["resuelto","cerrado"].includes(ticketStateKey(rawState(t)))).length;
const load=async()=>{await guardSession("index.html");const profile=(await s.from("perfiles").select("*").limit(1).maybeSingle()).data||{rol:"soporte"};ensureAppShell({page:"tickets",role:profile.rol||"soporte",title:"Tickets",kicker:"Expiriti · mesa operativa",actionsHtml:`<a class="mini btn-ghost" href="dashboard.html">Dashboard</a><button class="mini" data-theme-toggle>🌓 <span data-theme-label>Claro</span></button>`});setAppRole(profile.rol||"soporte");const {data,error}=await s.from("tickets").select("*,clientes:clientes!tickets_cliente_id_fkey(id,nombre)").order("fecha_actualizacion",{ascending:false});if(error)return toast(msg(error),"bad");TK=Array.isArray(data)?data:[];setGlobalSearchData({tickets:TK,clientes:TK.map(t=>t.clientes).filter(Boolean)});setBreadcrumb([{label:"Panel",href:"dashboard.html"},{label:"Tickets"}]);setRailOpenCount(openCount(TK));applyBoardOrder();setEditMode(EDIT_MODE);if(FOCUS_ON){setFocusMode(true)}else if(VIEW==="compact"){$("#tkBoard")?.classList.add("hidden");$("#tkCompact")?.classList.remove("hidden");$("#tkFocusPanel")?.classList.add("hidden")}else{$("#tkBoard")?.classList.remove("hidden");$("#tkCompact")?.classList.add("hidden");$("#tkFocusPanel")?.classList.add("hidden")}applyUrlFilters();renderAll();if(!FOCUS_ON){const first=filtered()[0];SELECTED_ID=first?String(first.id):"";document.querySelectorAll(".k-card,.compact-row").forEach(x=>x.classList.toggle("is-selected",String(x.dataset.id)===String(SELECTED_ID)))}};
const renderMetrics=()=>{const rows=TK,today=new Date().toDateString();$("#mUrgent").textContent=rows.filter(x=>norm(x.prioridad)==="urgente"&&!["resuelto","cerrado"].includes(ticketStateKey(rawState(x)))).length;$("#mWait").textContent=rows.filter(x=>ticketStateKey(rawState(x))==="esperando_cliente").length;$("#mStale").textContent=rows.filter(x=>!["resuelto","cerrado"].includes(ticketStateKey(rawState(x)))&&new Date(x.fecha_actualizacion||x.fecha_creacion).toDateString()!==today).length;$("#mSolved").textContent=rows.filter(x=>ticketStateKey(rawState(x))==="resuelto"&&new Date(x.fecha_actualizacion||x.fecha_creacion).toDateString()===today).length;$("#mPendingIdentity")&&($("#mPendingIdentity").textContent=rows.filter(needsIdentity).length);$("#mNoClient")&&($("#mNoClient").textContent=rows.filter(noClientLinked).length);$("#mFrBreach")&&($("#mFrBreach").textContent=rows.filter(slaFrBreached).length);$("#mRsBreach")&&($("#mRsBreach").textContent=rows.filter(slaRsBreached).length);$("#mSlaSoon")&&($("#mSlaSoon").textContent=rows.filter(slaSoon).length)};
const card=t=>{const stale=daysSince(t.fecha_actualizacion||t.fecha_creacion),crit=isCritical(t),health=healthTag(t),ev=evidenceCount(t),impact=impactKey(t),sla=slaMeta(t),cls=`k-card ${crit?"is-critical":""} ${staleCls(t)} ${String(t.id)===String(SELECTED_ID)?"is-selected":""}`.trim();return`<article class="${cls}" draggable="${EDIT_MODE?"true":"false"}" data-id="${t.id}"><div class="k-head"><div class="k-title">${t.titulo||"Sin título"}</div><div class="k-tags"><span class="tag ${ticketPriorityCls(t.prioridad)}">${t.prioridad||"media"}</span><span class="tag ${health.cls}">${health.txt}</span><span class="tag ${sla.cls}">${sla.txt}</span>${impact?`<span class="tag ${impact==="alta"?"bad":impact==="media"?"warn":"info"}">Impacto ${impact}</span>`:""}${stale>=1&&!["resuelto","cerrado"].includes(ticketStateKey(rawState(t)))?`<span class="tag warn">Sin avance ${stale}d</span>`:""}</div></div><div class="k-desc">${(t.descripcion||"Sin descripción").slice(0,120)}</div><div class="k-meta"><span>${t.clientes?.nombre||t.empresa_capturada||"Sin cliente"}</span><span>${normTipo(t.tipo)==="renovacion"?"Renovación":"Soporte"}</span></div><div class="k-tags"><span class="tag ${ev?`ok`:`warn`}">${ev?`${ev} archivo${ev>1?"s":""}`:"Sin archivos"}</span><span class="tag">${nextAction(t)}</span></div><div class="actions quick-inline"><button class="mini btn-ghost" type="button" data-ticket-state="${t.id}|en_proceso">En proceso</button><button class="mini btn-ghost" type="button" data-ticket-state="${t.id}|esperando_cliente">Espera cliente</button><button class="mini btn-ghost" type="button" data-ticket-state="${t.id}|resuelto">Resuelto</button><button class="btn btn-ghost" type="button" data-open-ticket="${t.id}">Abrir caso</button></div></article>`};
const renderBoard=()=>{const rows=filtered().filter(t=>ticketStateKey(rawState(t))!=="cerrado"),cols={abierto:[],en_proceso:[],esperando_cliente:[],resuelto:[]};rows.forEach(t=>{const k=ticketStateKey(rawState(t));if(cols[k])cols[k].push(t)});Object.keys(cols).forEach(k=>cols[k].sort((a,b)=>triageScore(b)-triageScore(a)||new Date(b.fecha_actualizacion||b.fecha_creacion)-new Date(a.fecha_actualizacion||a.fecha_creacion)));$("#col-abierto").innerHTML=cols.abierto.map(card).join("")||`<div class="empty-state">Sin tickets.</div>`;$("#col-en_proceso").innerHTML=cols.en_proceso.map(card).join("")||`<div class="empty-state">Sin tickets.</div>`;$("#col-esperando_cliente").innerHTML=cols.esperando_cliente.map(card).join("")||`<div class="empty-state">Sin tickets.</div>`;$("#col-resuelto").innerHTML=cols.resuelto.map(card).join("")||`<div class="empty-state">Sin tickets.</div>`;$("#count-abierto").textContent=cols.abierto.length;$("#count-en_proceso").textContent=cols.en_proceso.length;$("#count-esperando_cliente").textContent=cols.esperando_cliente.length;$("#count-resuelto").textContent=cols.resuelto.length};
const compactRow=t=>{const stale=daysSince(t.fecha_actualizacion||t.fecha_creacion),crit=isCritical(t),ev=evidenceCount(t),sla=slaMeta(t),idTxt=t?.requiere_consolidacion?"Por consolidar":hasLinkedContact(t)?"Contacto ligado":noLinkedContact(t)?"Falta contacto":consolidated(t)?"Consolidado":!t?.cliente_id?"Sin cliente":existingClientPending(t)?"Cliente ya identificado":"—";return`<div class="compact-row ${crit?"is-critical":""}" data-id="${t.id}"><div><span class="tag ${ticketPriorityCls(t.prioridad)}">${t.prioridad||"media"}</span></div><div>${t.clientes?.nombre||t.empresa_capturada||"—"}</div><div class="compact-title">${t.titulo||"Sin título"}</div><div>${normTipo(t.tipo)==="renovacion"?"Renovación":"Soporte"}</div><div>${ticketStateLabel(rawState(t))}</div><div>${idTxt} · ${sla.txt} · ${stale===0?"Hoy":`Sin avance ${stale}d`} · ${ev?`${ev} archivo${ev>1?"s":""}`:"sin archivos"} · <button class="mini btn-ghost" type="button" data-open-ticket="${t.id}">Abrir caso</button></div></div>`;};
const renderCompact=()=>{$("#tkCompactRows").innerHTML=filtered().length?filtered().map(compactRow).join(""):`<div class="empty-state">Sin tickets.</div>`};

const applyFilters=()=>{FILTER.q=$("#tkSearch")?.value||"";FILTER.priority=$("#tkFilterPriority")?.value||"";FILTER.state=$("#tkFilterState")?.value||"";FILTER.type=$("#tkFilterType")?.value||"";FILTER.client=$("#tkFilterClient")?.value||"";if(FILTER.clienteId&&FILTER.client&&!norm(FILTER.client).includes(norm(TK.find(x=>String(x?.cliente_id)===String(FILTER.clienteId))?.clientes?.nombre||"")))FILTER.clienteId="";FOCUS_INDEX=0;syncFilterUI();renderAll();if(!FOCUS_ON){const first=filtered()[0];SELECTED_ID=first?String(first.id):"";document.querySelectorAll(".k-card,.compact-row").forEach(x=>x.classList.toggle("is-selected",String(x.dataset.id)===String(SELECTED_ID)))}}; 
const renderAll=()=>{renderMetrics();renderBoard();renderCompact();bindDynamic();if(FOCUS_ON)renderFocus()};
const clientIdFromInput=async raw=>{const x=(raw||"").trim();if(!x)return null;if(/^[0-9a-f-]{8,}$/i.test(x))return x;const {data,error}=await s.from("clientes").select("id,nombre").ilike("nombre",`%${x}%`).limit(1);if(error||!data?.length)return null;return data[0].id};
const saveTicket=async()=>{const titulo=$("#tkTitulo").value.trim(),desc=$("#tkDesc").value.trim(),tipo=normTipo($("#tkTipo").value),prioridad=$("#tkPrioridad").value,clienteRaw=$("#tkCliente").value.trim();if(!titulo)return $("#tkStatus").textContent="El título es obligatorio.";$("#tkStatus").textContent="Guardando...";const cliente_id=await clientIdFromInput(clienteRaw),folio=await nextFolioSimple(),token_publico=randToken(),token_publico_expira=new Date(Date.now()+30*864e5).toISOString(),timeline_publica=[{titulo:"Ticket recibido",texto:"Tu caso fue registrado y ya está en nuestra mesa de soporte.",fecha:new Date().toISOString()}],sla=slaPack(prioridad),payload={titulo,descripcion:desc,tipo,prioridad,estado:"abierto",fecha_actualizacion:new Date().toISOString(),cliente_id:cliente_id||null,origen:"tickets",folio,token_publico,token_publico_expira,timeline_publica,sla_policy:sla.policy,sla_first_response_deadline:new Date(Date.now()+sla.fr*36e5).toISOString(),sla_resolution_deadline:new Date(Date.now()+sla.res*36e5).toISOString(),sla_breached_first_response:false,sla_breached_resolution:false};const {error}=await s.from("tickets").insert(payload);if(error){$("#tkStatus").textContent=msg(error);return}$("#tkStatus").textContent="Ticket creado.";hide("#tkModal");$("#tkCliente").value="";$("#tkTitulo").value="";$("#tkDesc").value="";$("#tkTipo").value="soporte";$("#tkPrioridad").value="media";toast("Ticket creado","ok");await load()};
const moveTicket=async(id,next)=>{const estado=ticketStateKey(next),now=new Date().toISOString(),t=byId(id),patch={estado,fecha_actualizacion:now};if(estado==="en_proceso"&&!t?.primera_respuesta_en)patch.primera_respuesta_en=now;if(estado==="resuelto")patch.fecha_cierre=now;const {error}=await s.from("tickets").update(patch).eq("id",id);if(error)return toast(msg(error),"bad");if(t){t.estado=estado;t.fecha_actualizacion=now;if(patch.primera_respuesta_en)t.primera_respuesta_en=patch.primera_respuesta_en;if(patch.fecha_cierre)t.fecha_cierre=patch.fecha_cierre}toast("Estado actualizado","ok");renderAll();SELECTED_ID=String(id);document.querySelectorAll(".k-card,.compact-row").forEach(x=>x.classList.toggle("is-selected",String(x.dataset.id)===String(SELECTED_ID)))};
const bindDynamic=()=>{if(document.documentElement.dataset.ticketsDynamicBound)return;document.documentElement.dataset.ticketsDynamicBound="1";document.addEventListener("click",async e=>{const stateBtn=e.target.closest("[data-ticket-state]");if(stateBtn){const[id,next]=String(stateBtn.dataset.ticketState||"").split("|");if(id&&next)return await moveTicket(id,next)}const openBtn=e.target.closest("[data-open-ticket]");if(openBtn)return location.href=`ticket.html?id=${openBtn.dataset.openTicket}`;const card=e.target.closest(".k-card,.compact-row");if(card&&!EDIT_MODE){SELECTED_ID=String(card.dataset.id);document.querySelectorAll(".k-card,.compact-row").forEach(x=>x.classList.toggle("is-selected",String(x.dataset.id)===String(SELECTED_ID)));if(!e.target.closest("a,button,input,select,textarea,label"))location.href=`ticket.html?id=${card.dataset.id}`}});document.addEventListener("dragstart",e=>{const col=e.target.closest(".kanban-col");if(EDIT_MODE&&col){DRAG_COL=col;col.classList.add("drag-col");e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",col.querySelector(".col-body")?.id||"");return}const card=e.target.closest(".k-card");if(card&&!EDIT_MODE)e.dataTransfer.setData("text/plain",card.dataset.id)});document.addEventListener("dragend",()=>{$$(".kanban-col").forEach(col=>col.classList.remove("drag-col","drag-over"));DRAG_COL=null});$$(".kanban-col").forEach(col=>{col.ondragover=e=>{if(!EDIT_MODE)return;e.preventDefault();col.classList.add("drag-over")};col.ondragleave=()=>col.classList.remove("drag-over");col.ondrop=e=>{if(!EDIT_MODE||!DRAG_COL||DRAG_COL===col)return;e.preventDefault();col.classList.remove("drag-over");const cols=$$(".kanban-board .kanban-col"),from=cols.indexOf(DRAG_COL),to=cols.indexOf(col);if(from<0||to<0)return;from<to?col.after(DRAG_COL):col.before(DRAG_COL);saveBoardOrder()}});$$(".col-body").forEach(col=>{col.addEventListener("dragover",e=>{if(EDIT_MODE)return;e.preventDefault();col.classList.add("drag-over")});col.addEventListener("dragleave",()=>{if(EDIT_MODE)return;col.classList.remove("drag-over")});col.addEventListener("drop",async e=>{if(EDIT_MODE)return;e.preventDefault();col.classList.remove("drag-over");const id=e.dataTransfer.getData("text/plain"),next=col.id.replace("col-","");if(id&&byId(id)&&ticketStateKey(rawState(byId(id)))!==next)await moveTicket(id,next)})})};
const toggleView=()=>{if(FOCUS_ON)return;VIEW=VIEW==="kanban"?"compact":"kanban";$("#tkBoard")?.classList.toggle("hidden",VIEW==="compact");$("#tkCompact")?.classList.toggle("hidden",VIEW!=="compact");localStorage.setItem("expiriti_tickets_view",VIEW);const b=$("#tkEditBtn");if(b)b.textContent=VIEW==="kanban"?"Vista compacta":"Vista tablero"};
const bindStatic=()=>{if(document.documentElement.dataset.ticketsBound)return;document.documentElement.dataset.ticketsBound="1"; $("#metricUrgent")?.addEventListener("click",()=>{$("#tkFilterPriority").value="urgente";applyFilters()});$("#metricWait")?.addEventListener("click",()=>{$("#tkFilterState").value="esperando_cliente";applyFilters()});$("#metricStale")?.addEventListener("click",()=>{FILTER.urgentStale=!FILTER.urgentStale;syncFilterUI();renderAll()});$("#metricSolved")?.addEventListener("click",()=>{$("#tkFilterState").value="resuelto";applyFilters()});$("#metricIdentity")?.addEventListener("click",()=>{FILTER.needsIdentity=true;syncFilterUI();renderAll()});$("#metricNoClient")?.addEventListener("click",()=>{FILTER.noClientLinked=true;syncFilterUI();renderAll()});$("#metricFrBreach")?.addEventListener("click",()=>{FILTER.frBreach=true;syncFilterUI();renderAll()});$("#metricRsBreach")?.addEventListener("click",()=>{FILTER.rsBreach=true;syncFilterUI();renderAll()});$("#metricSlaSoon")?.addEventListener("click",()=>{FILTER.slaSoon=true;syncFilterUI();renderAll()});$("#tkRefresh")?.addEventListener("click",()=>{load().catch(err=>toast(msg(err),"bad"));const menu=$("#tkGearMenu");menu?.classList.add("hidden");menu&&(menu.hidden=true)});$("#tkNewBtn")?.addEventListener("click",()=>show("#tkModal"));$("#tkClose")?.addEventListener("click",()=>hide("#tkModal"));$("#tkCancel")?.addEventListener("click",()=>hide("#tkModal"));$("#tkSave")?.addEventListener("click",saveTicket);$("#tkGearBtn")?.addEventListener("click",e=>{e.stopPropagation();const menu=$("#tkGearMenu"),open=menu?.classList.contains("hidden");menu?.classList.toggle("hidden",!open);menu&&(menu.hidden=!open)});$("#tkMetricsMoreBtn")?.addEventListener("click",()=>setKpiExpanded(true));$("#tkMetricsLessBtn")?.addEventListener("click",()=>setKpiExpanded(false));$("#tkEditBtn")?.addEventListener("click",()=>{toggleView();const menu=$("#tkGearMenu");menu?.classList.add("hidden");menu&&(menu.hidden=true)});$("#tkEditModeChk")?.addEventListener("change",e=>setEditMode(!!e.target.checked));$("#tkNotifVisual")?.addEventListener("change",e=>{BOARD_NOTIF.visual=!!e.target.checked;saveBoardNotif()});$("#tkNotifSound")?.addEventListener("change",e=>{BOARD_NOTIF.sound=!!e.target.checked;saveBoardNotif()});$("#tkNotifStrongOnly")?.addEventListener("change",e=>{BOARD_NOTIF.strongOnly=!!e.target.checked;saveBoardNotif()});$("#tkNotifVolume")?.addEventListener("input",e=>{BOARD_NOTIF.volume=Number(e.target.value||0.5);saveBoardNotif()});$("#tkMuteBoardBtn")?.addEventListener("click",()=>{BOARD_NOTIF.muted=!BOARD_NOTIF.muted;saveBoardNotif();toast(BOARD_NOTIF.muted?"Mesa silenciada":"Mesa reactivada","ok")});document.addEventListener("click",e=>{const inside=e.target.closest(".tickets-gear-wrap");if(!inside){const menu=$("#tkGearMenu");menu?.classList.add("hidden");menu&&(menu.hidden=true)}})};

document.addEventListener("DOMContentLoaded",()=>{bindStatic();load().catch(err=>toast(msg(err),"bad"))});
